ALTER TABLE products
ADD COLUMN IF NOT EXISTS primary_image VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS secondary_images TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS is_visible BOOLEAN NOT NULL DEFAULT FALSE;
