wal_level = logical
max_replication_slots = 10
max_wal_senders = 10

# Activar el colector de logs
logging_collector = on
log_directory = 'pg_log'

# 1. Nombre de archivo fijo basado en el día de la semana (log_mon, log_tue, etc.)
log_filename = 'postgresql-%a.log'

# 2. Forzar rotación cada 24 horas (para que cambie de archivo a medianoche)
log_rotation_age = 1d

# 3. Desactivar rotación por tamaño (opcional, para que el tiempo sea el único factor)
log_rotation_size = 0

# 4. TRUCO CLAVE: Sobrescribir el archivo existente del mismo nombre
# En lugar de añadir contenido al final del archivo de la semana pasada, lo borra.
log_truncate_on_rotation = on

max_wal_size = 1GB
min_wal_size = 80MB

listen_addresses = '*'
