// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package master

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Module is an object representing the database table.
type Module struct {
	ID                     int64         `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name                   string        `boil:"name" json:"name" toml:"name" yaml:"name"`
	PriceMonthly           types.Decimal `boil:"price_monthly" json:"price_monthly" toml:"price_monthly" yaml:"price_monthly"`
	PriceYearly            types.Decimal `boil:"price_yearly" json:"price_yearly" toml:"price_yearly" yaml:"price_yearly"`
	Description            string        `boil:"description" json:"description" toml:"description" yaml:"description"`
	Features               string        `boil:"features" json:"features" toml:"features" yaml:"features"`
	AmountImagesPerProduct int           `boil:"amount_images_per_product" json:"amount_images_per_product" toml:"amount_images_per_product" yaml:"amount_images_per_product"`
	CreatedAt              time.Time     `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt              time.Time     `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DeletedAt              null.Time     `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *moduleR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L moduleL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ModuleColumns = struct {
	ID                     string
	Name                   string
	PriceMonthly           string
	PriceYearly            string
	Description            string
	Features               string
	AmountImagesPerProduct string
	CreatedAt              string
	UpdatedAt              string
	DeletedAt              string
}{
	ID:                     "id",
	Name:                   "name",
	PriceMonthly:           "price_monthly",
	PriceYearly:            "price_yearly",
	Description:            "description",
	Features:               "features",
	AmountImagesPerProduct: "amount_images_per_product",
	CreatedAt:              "created_at",
	UpdatedAt:              "updated_at",
	DeletedAt:              "deleted_at",
}

var ModuleTableColumns = struct {
	ID                     string
	Name                   string
	PriceMonthly           string
	PriceYearly            string
	Description            string
	Features               string
	AmountImagesPerProduct string
	CreatedAt              string
	UpdatedAt              string
	DeletedAt              string
}{
	ID:                     "modules.id",
	Name:                   "modules.name",
	PriceMonthly:           "modules.price_monthly",
	PriceYearly:            "modules.price_yearly",
	Description:            "modules.description",
	Features:               "modules.features",
	AmountImagesPerProduct: "modules.amount_images_per_product",
	CreatedAt:              "modules.created_at",
	UpdatedAt:              "modules.updated_at",
	DeletedAt:              "modules.deleted_at",
}

// Generated where

type whereHelpertypes_Decimal struct{ field string }

func (w whereHelpertypes_Decimal) EQ(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_Decimal) NEQ(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_Decimal) LT(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_Decimal) LTE(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_Decimal) GT(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_Decimal) GTE(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var ModuleWhere = struct {
	ID                     whereHelperint64
	Name                   whereHelperstring
	PriceMonthly           whereHelpertypes_Decimal
	PriceYearly            whereHelpertypes_Decimal
	Description            whereHelperstring
	Features               whereHelperstring
	AmountImagesPerProduct whereHelperint
	CreatedAt              whereHelpertime_Time
	UpdatedAt              whereHelpertime_Time
	DeletedAt              whereHelpernull_Time
}{
	ID:                     whereHelperint64{field: "\"modules\".\"id\""},
	Name:                   whereHelperstring{field: "\"modules\".\"name\""},
	PriceMonthly:           whereHelpertypes_Decimal{field: "\"modules\".\"price_monthly\""},
	PriceYearly:            whereHelpertypes_Decimal{field: "\"modules\".\"price_yearly\""},
	Description:            whereHelperstring{field: "\"modules\".\"description\""},
	Features:               whereHelperstring{field: "\"modules\".\"features\""},
	AmountImagesPerProduct: whereHelperint{field: "\"modules\".\"amount_images_per_product\""},
	CreatedAt:              whereHelpertime_Time{field: "\"modules\".\"created_at\""},
	UpdatedAt:              whereHelpertime_Time{field: "\"modules\".\"updated_at\""},
	DeletedAt:              whereHelpernull_Time{field: "\"modules\".\"deleted_at\""},
}

// ModuleRels is where relationship names are stored.
var ModuleRels = struct {
	TenantModules string
}{
	TenantModules: "TenantModules",
}

// moduleR is where relationships are stored.
type moduleR struct {
	TenantModules TenantModuleSlice `boil:"TenantModules" json:"TenantModules" toml:"TenantModules" yaml:"TenantModules"`
}

// NewStruct creates a new relationship struct
func (*moduleR) NewStruct() *moduleR {
	return &moduleR{}
}

func (o *Module) GetTenantModules() TenantModuleSlice {
	if o == nil {
		return nil
	}

	return o.R.GetTenantModules()
}

func (r *moduleR) GetTenantModules() TenantModuleSlice {
	if r == nil {
		return nil
	}

	return r.TenantModules
}

// moduleL is where Load methods for each relationship are stored.
type moduleL struct{}

var (
	moduleAllColumns            = []string{"id", "name", "price_monthly", "price_yearly", "description", "features", "amount_images_per_product", "created_at", "updated_at", "deleted_at"}
	moduleColumnsWithoutDefault = []string{"name", "amount_images_per_product"}
	moduleColumnsWithDefault    = []string{"id", "price_monthly", "price_yearly", "description", "features", "created_at", "updated_at", "deleted_at"}
	modulePrimaryKeyColumns     = []string{"id"}
	moduleGeneratedColumns      = []string{}
)

type (
	// ModuleSlice is an alias for a slice of pointers to Module.
	// This should almost always be used instead of []Module.
	ModuleSlice []*Module
	// ModuleHook is the signature for custom Module hook methods
	ModuleHook func(context.Context, boil.ContextExecutor, *Module) error

	moduleQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	moduleType                 = reflect.TypeOf(&Module{})
	moduleMapping              = queries.MakeStructMapping(moduleType)
	modulePrimaryKeyMapping, _ = queries.BindMapping(moduleType, moduleMapping, modulePrimaryKeyColumns)
	moduleInsertCacheMut       sync.RWMutex
	moduleInsertCache          = make(map[string]insertCache)
	moduleUpdateCacheMut       sync.RWMutex
	moduleUpdateCache          = make(map[string]updateCache)
	moduleUpsertCacheMut       sync.RWMutex
	moduleUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var moduleAfterSelectMu sync.Mutex
var moduleAfterSelectHooks []ModuleHook

var moduleBeforeInsertMu sync.Mutex
var moduleBeforeInsertHooks []ModuleHook
var moduleAfterInsertMu sync.Mutex
var moduleAfterInsertHooks []ModuleHook

var moduleBeforeUpdateMu sync.Mutex
var moduleBeforeUpdateHooks []ModuleHook
var moduleAfterUpdateMu sync.Mutex
var moduleAfterUpdateHooks []ModuleHook

var moduleBeforeDeleteMu sync.Mutex
var moduleBeforeDeleteHooks []ModuleHook
var moduleAfterDeleteMu sync.Mutex
var moduleAfterDeleteHooks []ModuleHook

var moduleBeforeUpsertMu sync.Mutex
var moduleBeforeUpsertHooks []ModuleHook
var moduleAfterUpsertMu sync.Mutex
var moduleAfterUpsertHooks []ModuleHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Module) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range moduleAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Module) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range moduleBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Module) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range moduleAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Module) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range moduleBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Module) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range moduleAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Module) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range moduleBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Module) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range moduleAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Module) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range moduleBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Module) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range moduleAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddModuleHook registers your hook function for all future operations.
func AddModuleHook(hookPoint boil.HookPoint, moduleHook ModuleHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		moduleAfterSelectMu.Lock()
		moduleAfterSelectHooks = append(moduleAfterSelectHooks, moduleHook)
		moduleAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		moduleBeforeInsertMu.Lock()
		moduleBeforeInsertHooks = append(moduleBeforeInsertHooks, moduleHook)
		moduleBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		moduleAfterInsertMu.Lock()
		moduleAfterInsertHooks = append(moduleAfterInsertHooks, moduleHook)
		moduleAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		moduleBeforeUpdateMu.Lock()
		moduleBeforeUpdateHooks = append(moduleBeforeUpdateHooks, moduleHook)
		moduleBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		moduleAfterUpdateMu.Lock()
		moduleAfterUpdateHooks = append(moduleAfterUpdateHooks, moduleHook)
		moduleAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		moduleBeforeDeleteMu.Lock()
		moduleBeforeDeleteHooks = append(moduleBeforeDeleteHooks, moduleHook)
		moduleBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		moduleAfterDeleteMu.Lock()
		moduleAfterDeleteHooks = append(moduleAfterDeleteHooks, moduleHook)
		moduleAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		moduleBeforeUpsertMu.Lock()
		moduleBeforeUpsertHooks = append(moduleBeforeUpsertHooks, moduleHook)
		moduleBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		moduleAfterUpsertMu.Lock()
		moduleAfterUpsertHooks = append(moduleAfterUpsertHooks, moduleHook)
		moduleAfterUpsertMu.Unlock()
	}
}

// OneG returns a single module record from the query using the global executor.
func (q moduleQuery) OneG(ctx context.Context) (*Module, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single module record from the query.
func (q moduleQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Module, error) {
	o := &Module{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "master: failed to execute a one query for modules")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all Module records from the query using the global executor.
func (q moduleQuery) AllG(ctx context.Context) (ModuleSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all Module records from the query.
func (q moduleQuery) All(ctx context.Context, exec boil.ContextExecutor) (ModuleSlice, error) {
	var o []*Module

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "master: failed to assign all query results to Module slice")
	}

	if len(moduleAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all Module records in the query using the global executor
func (q moduleQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all Module records in the query.
func (q moduleQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "master: failed to count modules rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q moduleQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q moduleQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "master: failed to check if modules exists")
	}

	return count > 0, nil
}

// TenantModules retrieves all the tenant_module's TenantModules with an executor.
func (o *Module) TenantModules(mods ...qm.QueryMod) tenantModuleQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"tenant_modules\".\"module_id\"=?", o.ID),
	)

	return TenantModules(queryMods...)
}

// LoadTenantModules allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (moduleL) LoadTenantModules(ctx context.Context, e boil.ContextExecutor, singular bool, maybeModule any, mods queries.Applicator) error {
	var slice []*Module
	var object *Module

	if singular {
		var ok bool
		object, ok = maybeModule.(*Module)
		if !ok {
			object = new(Module)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeModule)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeModule))
			}
		}
	} else {
		s, ok := maybeModule.(*[]*Module)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeModule)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeModule))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &moduleR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &moduleR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tenant_modules`),
		qm.WhereIn(`tenant_modules.module_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load tenant_modules")
	}

	var resultSlice []*TenantModule
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice tenant_modules")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on tenant_modules")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tenant_modules")
	}

	if len(tenantModuleAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.TenantModules = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &tenantModuleR{}
			}
			foreign.R.Module = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.ModuleID {
				local.R.TenantModules = append(local.R.TenantModules, foreign)
				if foreign.R == nil {
					foreign.R = &tenantModuleR{}
				}
				foreign.R.Module = local
				break
			}
		}
	}

	return nil
}

// AddTenantModulesG adds the given related objects to the existing relationships
// of the module, optionally inserting them as new records.
// Appends related to o.R.TenantModules.
// Sets related.R.Module appropriately.
// Uses the global database handle.
func (o *Module) AddTenantModulesG(ctx context.Context, insert bool, related ...*TenantModule) error {
	return o.AddTenantModules(ctx, boil.GetContextDB(), insert, related...)
}

// AddTenantModules adds the given related objects to the existing relationships
// of the module, optionally inserting them as new records.
// Appends related to o.R.TenantModules.
// Sets related.R.Module appropriately.
func (o *Module) AddTenantModules(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*TenantModule) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.ModuleID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"tenant_modules\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"module_id"}),
				strmangle.WhereClause("\"", "\"", 2, tenantModulePrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.ModuleID = o.ID
		}
	}

	if o.R == nil {
		o.R = &moduleR{
			TenantModules: related,
		}
	} else {
		o.R.TenantModules = append(o.R.TenantModules, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &tenantModuleR{
				Module: o,
			}
		} else {
			rel.R.Module = o
		}
	}
	return nil
}

// Modules retrieves all the records using an executor.
func Modules(mods ...qm.QueryMod) moduleQuery {
	mods = append(mods, qm.From("\"modules\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"modules\".*"})
	}

	return moduleQuery{q}
}

// FindModuleG retrieves a single record by ID.
func FindModuleG(ctx context.Context, iD int64, selectCols ...string) (*Module, error) {
	return FindModule(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindModule retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindModule(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*Module, error) {
	moduleObj := &Module{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"modules\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, moduleObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "master: unable to select from modules")
	}

	if err = moduleObj.doAfterSelectHooks(ctx, exec); err != nil {
		return moduleObj, err
	}

	return moduleObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Module) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Module) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("master: no modules provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(moduleColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	moduleInsertCacheMut.RLock()
	cache, cached := moduleInsertCache[key]
	moduleInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			moduleAllColumns,
			moduleColumnsWithDefault,
			moduleColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(moduleType, moduleMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(moduleType, moduleMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"modules\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"modules\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "master: unable to insert into modules")
	}

	if !cached {
		moduleInsertCacheMut.Lock()
		moduleInsertCache[key] = cache
		moduleInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single Module record using the global executor.
// See Update for more documentation.
func (o *Module) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the Module.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Module) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	moduleUpdateCacheMut.RLock()
	cache, cached := moduleUpdateCache[key]
	moduleUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			moduleAllColumns,
			modulePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("master: unable to update modules, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"modules\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, modulePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(moduleType, moduleMapping, append(wl, modulePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to update modules row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "master: failed to get rows affected by update for modules")
	}

	if !cached {
		moduleUpdateCacheMut.Lock()
		moduleUpdateCache[key] = cache
		moduleUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q moduleQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q moduleQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to update all for modules")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to retrieve rows affected for modules")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o ModuleSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ModuleSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("master: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), modulePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"modules\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, modulePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to update all in module slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to retrieve rows affected all in update all module")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Module) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Module) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("master: no modules provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(moduleColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	moduleUpsertCacheMut.RLock()
	cache, cached := moduleUpsertCache[key]
	moduleUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			moduleAllColumns,
			moduleColumnsWithDefault,
			moduleColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			moduleAllColumns,
			modulePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("master: unable to upsert modules, could not build update column list")
		}

		ret := strmangle.SetComplement(moduleAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(modulePrimaryKeyColumns) == 0 {
				return errors.New("master: unable to upsert modules, could not build conflict column list")
			}

			conflict = make([]string, len(modulePrimaryKeyColumns))
			copy(conflict, modulePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"modules\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(moduleType, moduleMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(moduleType, moduleMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "master: unable to upsert modules")
	}

	if !cached {
		moduleUpsertCacheMut.Lock()
		moduleUpsertCache[key] = cache
		moduleUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single Module record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Module) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single Module record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Module) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("master: no Module provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), modulePrimaryKeyMapping)
	sql := "DELETE FROM \"modules\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to delete from modules")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "master: failed to get rows affected by delete for modules")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q moduleQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q moduleQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("master: no moduleQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to delete all from modules")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "master: failed to get rows affected by deleteall for modules")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o ModuleSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ModuleSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(moduleBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), modulePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"modules\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, modulePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to delete all from module slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "master: failed to get rows affected by deleteall for modules")
	}

	if len(moduleAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Module) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("master: no Module provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Module) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindModule(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ModuleSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("master: empty ModuleSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ModuleSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ModuleSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), modulePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"modules\".* FROM \"modules\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, modulePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "master: unable to reload all in ModuleSlice")
	}

	*o = slice

	return nil
}

// ModuleExistsG checks if the Module row exists.
func ModuleExistsG(ctx context.Context, iD int64) (bool, error) {
	return ModuleExists(ctx, boil.GetContextDB(), iD)
}

// ModuleExists checks if the Module row exists.
func ModuleExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"modules\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "master: unable to check if modules exists")
	}

	return exists, nil
}

// Exists checks if the Module row exists.
func (o *Module) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ModuleExists(ctx, exec, o.ID)
}
