// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package master

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// PayTenant is an object representing the database table.
type PayTenant struct {
	ID          int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	TenantID    int64     `boil:"tenant_id" json:"tenant_id" toml:"tenant_id" yaml:"tenant_id"`
	AdminID     int64     `boil:"admin_id" json:"admin_id" toml:"admin_id" yaml:"admin_id"`
	AmountMonth int64     `boil:"amount_month" json:"amount_month" toml:"amount_month" yaml:"amount_month"`
	CreatedAt   time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *payTenantR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L payTenantL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PayTenantColumns = struct {
	ID          string
	TenantID    string
	AdminID     string
	AmountMonth string
	CreatedAt   string
}{
	ID:          "id",
	TenantID:    "tenant_id",
	AdminID:     "admin_id",
	AmountMonth: "amount_month",
	CreatedAt:   "created_at",
}

var PayTenantTableColumns = struct {
	ID          string
	TenantID    string
	AdminID     string
	AmountMonth string
	CreatedAt   string
}{
	ID:          "pay_tenants.id",
	TenantID:    "pay_tenants.tenant_id",
	AdminID:     "pay_tenants.admin_id",
	AmountMonth: "pay_tenants.amount_month",
	CreatedAt:   "pay_tenants.created_at",
}

// Generated where

var PayTenantWhere = struct {
	ID          whereHelperint64
	TenantID    whereHelperint64
	AdminID     whereHelperint64
	AmountMonth whereHelperint64
	CreatedAt   whereHelpertime_Time
}{
	ID:          whereHelperint64{field: "\"pay_tenants\".\"id\""},
	TenantID:    whereHelperint64{field: "\"pay_tenants\".\"tenant_id\""},
	AdminID:     whereHelperint64{field: "\"pay_tenants\".\"admin_id\""},
	AmountMonth: whereHelperint64{field: "\"pay_tenants\".\"amount_month\""},
	CreatedAt:   whereHelpertime_Time{field: "\"pay_tenants\".\"created_at\""},
}

// PayTenantRels is where relationship names are stored.
var PayTenantRels = struct {
	Admin      string
	Tenant     string
	PayDetails string
}{
	Admin:      "Admin",
	Tenant:     "Tenant",
	PayDetails: "PayDetails",
}

// payTenantR is where relationships are stored.
type payTenantR struct {
	Admin      *Admin         `boil:"Admin" json:"Admin" toml:"Admin" yaml:"Admin"`
	Tenant     *Tenant        `boil:"Tenant" json:"Tenant" toml:"Tenant" yaml:"Tenant"`
	PayDetails PayDetailSlice `boil:"PayDetails" json:"PayDetails" toml:"PayDetails" yaml:"PayDetails"`
}

// NewStruct creates a new relationship struct
func (*payTenantR) NewStruct() *payTenantR {
	return &payTenantR{}
}

func (o *PayTenant) GetAdmin() *Admin {
	if o == nil {
		return nil
	}

	return o.R.GetAdmin()
}

func (r *payTenantR) GetAdmin() *Admin {
	if r == nil {
		return nil
	}

	return r.Admin
}

func (o *PayTenant) GetTenant() *Tenant {
	if o == nil {
		return nil
	}

	return o.R.GetTenant()
}

func (r *payTenantR) GetTenant() *Tenant {
	if r == nil {
		return nil
	}

	return r.Tenant
}

func (o *PayTenant) GetPayDetails() PayDetailSlice {
	if o == nil {
		return nil
	}

	return o.R.GetPayDetails()
}

func (r *payTenantR) GetPayDetails() PayDetailSlice {
	if r == nil {
		return nil
	}

	return r.PayDetails
}

// payTenantL is where Load methods for each relationship are stored.
type payTenantL struct{}

var (
	payTenantAllColumns            = []string{"id", "tenant_id", "admin_id", "amount_month", "created_at"}
	payTenantColumnsWithoutDefault = []string{"tenant_id", "admin_id", "amount_month"}
	payTenantColumnsWithDefault    = []string{"id", "created_at"}
	payTenantPrimaryKeyColumns     = []string{"id"}
	payTenantGeneratedColumns      = []string{}
)

type (
	// PayTenantSlice is an alias for a slice of pointers to PayTenant.
	// This should almost always be used instead of []PayTenant.
	PayTenantSlice []*PayTenant
	// PayTenantHook is the signature for custom PayTenant hook methods
	PayTenantHook func(context.Context, boil.ContextExecutor, *PayTenant) error

	payTenantQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	payTenantType                 = reflect.TypeOf(&PayTenant{})
	payTenantMapping              = queries.MakeStructMapping(payTenantType)
	payTenantPrimaryKeyMapping, _ = queries.BindMapping(payTenantType, payTenantMapping, payTenantPrimaryKeyColumns)
	payTenantInsertCacheMut       sync.RWMutex
	payTenantInsertCache          = make(map[string]insertCache)
	payTenantUpdateCacheMut       sync.RWMutex
	payTenantUpdateCache          = make(map[string]updateCache)
	payTenantUpsertCacheMut       sync.RWMutex
	payTenantUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var payTenantAfterSelectMu sync.Mutex
var payTenantAfterSelectHooks []PayTenantHook

var payTenantBeforeInsertMu sync.Mutex
var payTenantBeforeInsertHooks []PayTenantHook
var payTenantAfterInsertMu sync.Mutex
var payTenantAfterInsertHooks []PayTenantHook

var payTenantBeforeUpdateMu sync.Mutex
var payTenantBeforeUpdateHooks []PayTenantHook
var payTenantAfterUpdateMu sync.Mutex
var payTenantAfterUpdateHooks []PayTenantHook

var payTenantBeforeDeleteMu sync.Mutex
var payTenantBeforeDeleteHooks []PayTenantHook
var payTenantAfterDeleteMu sync.Mutex
var payTenantAfterDeleteHooks []PayTenantHook

var payTenantBeforeUpsertMu sync.Mutex
var payTenantBeforeUpsertHooks []PayTenantHook
var payTenantAfterUpsertMu sync.Mutex
var payTenantAfterUpsertHooks []PayTenantHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PayTenant) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range payTenantAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PayTenant) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range payTenantBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PayTenant) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range payTenantAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PayTenant) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range payTenantBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PayTenant) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range payTenantAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PayTenant) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range payTenantBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PayTenant) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range payTenantAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PayTenant) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range payTenantBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PayTenant) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range payTenantAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPayTenantHook registers your hook function for all future operations.
func AddPayTenantHook(hookPoint boil.HookPoint, payTenantHook PayTenantHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		payTenantAfterSelectMu.Lock()
		payTenantAfterSelectHooks = append(payTenantAfterSelectHooks, payTenantHook)
		payTenantAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		payTenantBeforeInsertMu.Lock()
		payTenantBeforeInsertHooks = append(payTenantBeforeInsertHooks, payTenantHook)
		payTenantBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		payTenantAfterInsertMu.Lock()
		payTenantAfterInsertHooks = append(payTenantAfterInsertHooks, payTenantHook)
		payTenantAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		payTenantBeforeUpdateMu.Lock()
		payTenantBeforeUpdateHooks = append(payTenantBeforeUpdateHooks, payTenantHook)
		payTenantBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		payTenantAfterUpdateMu.Lock()
		payTenantAfterUpdateHooks = append(payTenantAfterUpdateHooks, payTenantHook)
		payTenantAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		payTenantBeforeDeleteMu.Lock()
		payTenantBeforeDeleteHooks = append(payTenantBeforeDeleteHooks, payTenantHook)
		payTenantBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		payTenantAfterDeleteMu.Lock()
		payTenantAfterDeleteHooks = append(payTenantAfterDeleteHooks, payTenantHook)
		payTenantAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		payTenantBeforeUpsertMu.Lock()
		payTenantBeforeUpsertHooks = append(payTenantBeforeUpsertHooks, payTenantHook)
		payTenantBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		payTenantAfterUpsertMu.Lock()
		payTenantAfterUpsertHooks = append(payTenantAfterUpsertHooks, payTenantHook)
		payTenantAfterUpsertMu.Unlock()
	}
}

// OneG returns a single payTenant record from the query using the global executor.
func (q payTenantQuery) OneG(ctx context.Context) (*PayTenant, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single payTenant record from the query.
func (q payTenantQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PayTenant, error) {
	o := &PayTenant{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "master: failed to execute a one query for pay_tenants")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all PayTenant records from the query using the global executor.
func (q payTenantQuery) AllG(ctx context.Context) (PayTenantSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all PayTenant records from the query.
func (q payTenantQuery) All(ctx context.Context, exec boil.ContextExecutor) (PayTenantSlice, error) {
	var o []*PayTenant

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "master: failed to assign all query results to PayTenant slice")
	}

	if len(payTenantAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all PayTenant records in the query using the global executor
func (q payTenantQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all PayTenant records in the query.
func (q payTenantQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "master: failed to count pay_tenants rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q payTenantQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q payTenantQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "master: failed to check if pay_tenants exists")
	}

	return count > 0, nil
}

// Admin pointed to by the foreign key.
func (o *PayTenant) Admin(mods ...qm.QueryMod) adminQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.AdminID),
	}

	queryMods = append(queryMods, mods...)

	return Admins(queryMods...)
}

// Tenant pointed to by the foreign key.
func (o *PayTenant) Tenant(mods ...qm.QueryMod) tenantQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.TenantID),
	}

	queryMods = append(queryMods, mods...)

	return Tenants(queryMods...)
}

// PayDetails retrieves all the pay_detail's PayDetails with an executor.
func (o *PayTenant) PayDetails(mods ...qm.QueryMod) payDetailQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"pay_details\".\"pay_tenant_id\"=?", o.ID),
	)

	return PayDetails(queryMods...)
}

// LoadAdmin allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (payTenantL) LoadAdmin(ctx context.Context, e boil.ContextExecutor, singular bool, maybePayTenant any, mods queries.Applicator) error {
	var slice []*PayTenant
	var object *PayTenant

	if singular {
		var ok bool
		object, ok = maybePayTenant.(*PayTenant)
		if !ok {
			object = new(PayTenant)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePayTenant)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePayTenant))
			}
		}
	} else {
		s, ok := maybePayTenant.(*[]*PayTenant)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePayTenant)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePayTenant))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &payTenantR{}
		}
		args[object.AdminID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &payTenantR{}
			}

			args[obj.AdminID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`admins`),
		qm.WhereIn(`admins.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Admin")
	}

	var resultSlice []*Admin
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Admin")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for admins")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for admins")
	}

	if len(adminAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Admin = foreign
		if foreign.R == nil {
			foreign.R = &adminR{}
		}
		foreign.R.PayTenants = append(foreign.R.PayTenants, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.AdminID == foreign.ID {
				local.R.Admin = foreign
				if foreign.R == nil {
					foreign.R = &adminR{}
				}
				foreign.R.PayTenants = append(foreign.R.PayTenants, local)
				break
			}
		}
	}

	return nil
}

// LoadTenant allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (payTenantL) LoadTenant(ctx context.Context, e boil.ContextExecutor, singular bool, maybePayTenant any, mods queries.Applicator) error {
	var slice []*PayTenant
	var object *PayTenant

	if singular {
		var ok bool
		object, ok = maybePayTenant.(*PayTenant)
		if !ok {
			object = new(PayTenant)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePayTenant)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePayTenant))
			}
		}
	} else {
		s, ok := maybePayTenant.(*[]*PayTenant)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePayTenant)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePayTenant))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &payTenantR{}
		}
		args[object.TenantID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &payTenantR{}
			}

			args[obj.TenantID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tenants`),
		qm.WhereIn(`tenants.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Tenant")
	}

	var resultSlice []*Tenant
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Tenant")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for tenants")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tenants")
	}

	if len(tenantAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Tenant = foreign
		if foreign.R == nil {
			foreign.R = &tenantR{}
		}
		foreign.R.PayTenants = append(foreign.R.PayTenants, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TenantID == foreign.ID {
				local.R.Tenant = foreign
				if foreign.R == nil {
					foreign.R = &tenantR{}
				}
				foreign.R.PayTenants = append(foreign.R.PayTenants, local)
				break
			}
		}
	}

	return nil
}

// LoadPayDetails allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (payTenantL) LoadPayDetails(ctx context.Context, e boil.ContextExecutor, singular bool, maybePayTenant any, mods queries.Applicator) error {
	var slice []*PayTenant
	var object *PayTenant

	if singular {
		var ok bool
		object, ok = maybePayTenant.(*PayTenant)
		if !ok {
			object = new(PayTenant)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePayTenant)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePayTenant))
			}
		}
	} else {
		s, ok := maybePayTenant.(*[]*PayTenant)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePayTenant)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePayTenant))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &payTenantR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &payTenantR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`pay_details`),
		qm.WhereIn(`pay_details.pay_tenant_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load pay_details")
	}

	var resultSlice []*PayDetail
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice pay_details")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on pay_details")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for pay_details")
	}

	if len(payDetailAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.PayDetails = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &payDetailR{}
			}
			foreign.R.PayTenant = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.PayTenantID {
				local.R.PayDetails = append(local.R.PayDetails, foreign)
				if foreign.R == nil {
					foreign.R = &payDetailR{}
				}
				foreign.R.PayTenant = local
				break
			}
		}
	}

	return nil
}

// SetAdminG of the payTenant to the related item.
// Sets o.R.Admin to related.
// Adds o to related.R.PayTenants.
// Uses the global database handle.
func (o *PayTenant) SetAdminG(ctx context.Context, insert bool, related *Admin) error {
	return o.SetAdmin(ctx, boil.GetContextDB(), insert, related)
}

// SetAdmin of the payTenant to the related item.
// Sets o.R.Admin to related.
// Adds o to related.R.PayTenants.
func (o *PayTenant) SetAdmin(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Admin) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"pay_tenants\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"admin_id"}),
		strmangle.WhereClause("\"", "\"", 2, payTenantPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.AdminID = related.ID
	if o.R == nil {
		o.R = &payTenantR{
			Admin: related,
		}
	} else {
		o.R.Admin = related
	}

	if related.R == nil {
		related.R = &adminR{
			PayTenants: PayTenantSlice{o},
		}
	} else {
		related.R.PayTenants = append(related.R.PayTenants, o)
	}

	return nil
}

// SetTenantG of the payTenant to the related item.
// Sets o.R.Tenant to related.
// Adds o to related.R.PayTenants.
// Uses the global database handle.
func (o *PayTenant) SetTenantG(ctx context.Context, insert bool, related *Tenant) error {
	return o.SetTenant(ctx, boil.GetContextDB(), insert, related)
}

// SetTenant of the payTenant to the related item.
// Sets o.R.Tenant to related.
// Adds o to related.R.PayTenants.
func (o *PayTenant) SetTenant(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Tenant) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"pay_tenants\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"tenant_id"}),
		strmangle.WhereClause("\"", "\"", 2, payTenantPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TenantID = related.ID
	if o.R == nil {
		o.R = &payTenantR{
			Tenant: related,
		}
	} else {
		o.R.Tenant = related
	}

	if related.R == nil {
		related.R = &tenantR{
			PayTenants: PayTenantSlice{o},
		}
	} else {
		related.R.PayTenants = append(related.R.PayTenants, o)
	}

	return nil
}

// AddPayDetailsG adds the given related objects to the existing relationships
// of the pay_tenant, optionally inserting them as new records.
// Appends related to o.R.PayDetails.
// Sets related.R.PayTenant appropriately.
// Uses the global database handle.
func (o *PayTenant) AddPayDetailsG(ctx context.Context, insert bool, related ...*PayDetail) error {
	return o.AddPayDetails(ctx, boil.GetContextDB(), insert, related...)
}

// AddPayDetails adds the given related objects to the existing relationships
// of the pay_tenant, optionally inserting them as new records.
// Appends related to o.R.PayDetails.
// Sets related.R.PayTenant appropriately.
func (o *PayTenant) AddPayDetails(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*PayDetail) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.PayTenantID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"pay_details\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"pay_tenant_id"}),
				strmangle.WhereClause("\"", "\"", 2, payDetailPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.PayTenantID = o.ID
		}
	}

	if o.R == nil {
		o.R = &payTenantR{
			PayDetails: related,
		}
	} else {
		o.R.PayDetails = append(o.R.PayDetails, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &payDetailR{
				PayTenant: o,
			}
		} else {
			rel.R.PayTenant = o
		}
	}
	return nil
}

// PayTenants retrieves all the records using an executor.
func PayTenants(mods ...qm.QueryMod) payTenantQuery {
	mods = append(mods, qm.From("\"pay_tenants\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"pay_tenants\".*"})
	}

	return payTenantQuery{q}
}

// FindPayTenantG retrieves a single record by ID.
func FindPayTenantG(ctx context.Context, iD int64, selectCols ...string) (*PayTenant, error) {
	return FindPayTenant(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindPayTenant retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPayTenant(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*PayTenant, error) {
	payTenantObj := &PayTenant{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"pay_tenants\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, payTenantObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "master: unable to select from pay_tenants")
	}

	if err = payTenantObj.doAfterSelectHooks(ctx, exec); err != nil {
		return payTenantObj, err
	}

	return payTenantObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *PayTenant) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PayTenant) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("master: no pay_tenants provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(payTenantColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	payTenantInsertCacheMut.RLock()
	cache, cached := payTenantInsertCache[key]
	payTenantInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			payTenantAllColumns,
			payTenantColumnsWithDefault,
			payTenantColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(payTenantType, payTenantMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(payTenantType, payTenantMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"pay_tenants\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"pay_tenants\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "master: unable to insert into pay_tenants")
	}

	if !cached {
		payTenantInsertCacheMut.Lock()
		payTenantInsertCache[key] = cache
		payTenantInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single PayTenant record using the global executor.
// See Update for more documentation.
func (o *PayTenant) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the PayTenant.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PayTenant) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	payTenantUpdateCacheMut.RLock()
	cache, cached := payTenantUpdateCache[key]
	payTenantUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			payTenantAllColumns,
			payTenantPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("master: unable to update pay_tenants, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"pay_tenants\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, payTenantPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(payTenantType, payTenantMapping, append(wl, payTenantPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to update pay_tenants row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "master: failed to get rows affected by update for pay_tenants")
	}

	if !cached {
		payTenantUpdateCacheMut.Lock()
		payTenantUpdateCache[key] = cache
		payTenantUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q payTenantQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q payTenantQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to update all for pay_tenants")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to retrieve rows affected for pay_tenants")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o PayTenantSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PayTenantSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("master: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), payTenantPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"pay_tenants\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, payTenantPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to update all in payTenant slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to retrieve rows affected all in update all payTenant")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *PayTenant) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PayTenant) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("master: no pay_tenants provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(payTenantColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	payTenantUpsertCacheMut.RLock()
	cache, cached := payTenantUpsertCache[key]
	payTenantUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			payTenantAllColumns,
			payTenantColumnsWithDefault,
			payTenantColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			payTenantAllColumns,
			payTenantPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("master: unable to upsert pay_tenants, could not build update column list")
		}

		ret := strmangle.SetComplement(payTenantAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(payTenantPrimaryKeyColumns) == 0 {
				return errors.New("master: unable to upsert pay_tenants, could not build conflict column list")
			}

			conflict = make([]string, len(payTenantPrimaryKeyColumns))
			copy(conflict, payTenantPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"pay_tenants\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(payTenantType, payTenantMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(payTenantType, payTenantMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "master: unable to upsert pay_tenants")
	}

	if !cached {
		payTenantUpsertCacheMut.Lock()
		payTenantUpsertCache[key] = cache
		payTenantUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single PayTenant record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *PayTenant) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single PayTenant record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PayTenant) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("master: no PayTenant provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), payTenantPrimaryKeyMapping)
	sql := "DELETE FROM \"pay_tenants\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to delete from pay_tenants")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "master: failed to get rows affected by delete for pay_tenants")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q payTenantQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q payTenantQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("master: no payTenantQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to delete all from pay_tenants")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "master: failed to get rows affected by deleteall for pay_tenants")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o PayTenantSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PayTenantSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(payTenantBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), payTenantPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"pay_tenants\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, payTenantPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to delete all from payTenant slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "master: failed to get rows affected by deleteall for pay_tenants")
	}

	if len(payTenantAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *PayTenant) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("master: no PayTenant provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PayTenant) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPayTenant(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PayTenantSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("master: empty PayTenantSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PayTenantSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PayTenantSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), payTenantPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"pay_tenants\".* FROM \"pay_tenants\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, payTenantPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "master: unable to reload all in PayTenantSlice")
	}

	*o = slice

	return nil
}

// PayTenantExistsG checks if the PayTenant row exists.
func PayTenantExistsG(ctx context.Context, iD int64) (bool, error) {
	return PayTenantExists(ctx, boil.GetContextDB(), iD)
}

// PayTenantExists checks if the PayTenant row exists.
func PayTenantExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"pay_tenants\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "master: unable to check if pay_tenants exists")
	}

	return exists, nil
}

// Exists checks if the PayTenant row exists.
func (o *PayTenant) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PayTenantExists(ctx, exec, o.ID)
}
