// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package master

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Tenant is an object representing the database table.
type Tenant struct {
	ID            int64       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name          string      `boil:"name" json:"name" toml:"name" yaml:"name"`
	Identifier    string      `boil:"identifier" json:"identifier" toml:"identifier" yaml:"identifier"`
	Address       string      `boil:"address" json:"address" toml:"address" yaml:"address"`
	Phone         string      `boil:"phone" json:"phone" toml:"phone" yaml:"phone"`
	Email         string      `boil:"email" json:"email" toml:"email" yaml:"email"`
	CuitPDV       string      `boil:"cuit_pdv" json:"cuit_pdv" toml:"cuit_pdv" yaml:"cuit_pdv"`
	IsActive      bool        `boil:"is_active" json:"is_active" toml:"is_active" yaml:"is_active"`
	PlanID        int64       `boil:"plan_id" json:"plan_id" toml:"plan_id" yaml:"plan_id"`
	Connection    string      `boil:"connection" json:"connection" toml:"connection" yaml:"connection"`
	Expiration    null.Time   `boil:"expiration" json:"expiration,omitempty" toml:"expiration" yaml:"expiration,omitempty"`
	AcceptedTerms bool        `boil:"accepted_terms" json:"accepted_terms" toml:"accepted_terms" yaml:"accepted_terms"`
	IP            null.String `boil:"ip" json:"ip,omitempty" toml:"ip" yaml:"ip,omitempty"`
	DateAccepted  null.Time   `boil:"date_accepted" json:"date_accepted,omitempty" toml:"date_accepted" yaml:"date_accepted,omitempty"`
	CreatedAt     time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt     time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DeletedAt     null.Time   `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *tenantR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L tenantL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TenantColumns = struct {
	ID            string
	Name          string
	Identifier    string
	Address       string
	Phone         string
	Email         string
	CuitPDV       string
	IsActive      string
	PlanID        string
	Connection    string
	Expiration    string
	AcceptedTerms string
	IP            string
	DateAccepted  string
	CreatedAt     string
	UpdatedAt     string
	DeletedAt     string
}{
	ID:            "id",
	Name:          "name",
	Identifier:    "identifier",
	Address:       "address",
	Phone:         "phone",
	Email:         "email",
	CuitPDV:       "cuit_pdv",
	IsActive:      "is_active",
	PlanID:        "plan_id",
	Connection:    "connection",
	Expiration:    "expiration",
	AcceptedTerms: "accepted_terms",
	IP:            "ip",
	DateAccepted:  "date_accepted",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
	DeletedAt:     "deleted_at",
}

var TenantTableColumns = struct {
	ID            string
	Name          string
	Identifier    string
	Address       string
	Phone         string
	Email         string
	CuitPDV       string
	IsActive      string
	PlanID        string
	Connection    string
	Expiration    string
	AcceptedTerms string
	IP            string
	DateAccepted  string
	CreatedAt     string
	UpdatedAt     string
	DeletedAt     string
}{
	ID:            "tenants.id",
	Name:          "tenants.name",
	Identifier:    "tenants.identifier",
	Address:       "tenants.address",
	Phone:         "tenants.phone",
	Email:         "tenants.email",
	CuitPDV:       "tenants.cuit_pdv",
	IsActive:      "tenants.is_active",
	PlanID:        "tenants.plan_id",
	Connection:    "tenants.connection",
	Expiration:    "tenants.expiration",
	AcceptedTerms: "tenants.accepted_terms",
	IP:            "tenants.ip",
	DateAccepted:  "tenants.date_accepted",
	CreatedAt:     "tenants.created_at",
	UpdatedAt:     "tenants.updated_at",
	DeletedAt:     "tenants.deleted_at",
}

// Generated where

var TenantWhere = struct {
	ID            whereHelperint64
	Name          whereHelperstring
	Identifier    whereHelperstring
	Address       whereHelperstring
	Phone         whereHelperstring
	Email         whereHelperstring
	CuitPDV       whereHelperstring
	IsActive      whereHelperbool
	PlanID        whereHelperint64
	Connection    whereHelperstring
	Expiration    whereHelpernull_Time
	AcceptedTerms whereHelperbool
	IP            whereHelpernull_String
	DateAccepted  whereHelpernull_Time
	CreatedAt     whereHelpertime_Time
	UpdatedAt     whereHelpertime_Time
	DeletedAt     whereHelpernull_Time
}{
	ID:            whereHelperint64{field: "\"tenants\".\"id\""},
	Name:          whereHelperstring{field: "\"tenants\".\"name\""},
	Identifier:    whereHelperstring{field: "\"tenants\".\"identifier\""},
	Address:       whereHelperstring{field: "\"tenants\".\"address\""},
	Phone:         whereHelperstring{field: "\"tenants\".\"phone\""},
	Email:         whereHelperstring{field: "\"tenants\".\"email\""},
	CuitPDV:       whereHelperstring{field: "\"tenants\".\"cuit_pdv\""},
	IsActive:      whereHelperbool{field: "\"tenants\".\"is_active\""},
	PlanID:        whereHelperint64{field: "\"tenants\".\"plan_id\""},
	Connection:    whereHelperstring{field: "\"tenants\".\"connection\""},
	Expiration:    whereHelpernull_Time{field: "\"tenants\".\"expiration\""},
	AcceptedTerms: whereHelperbool{field: "\"tenants\".\"accepted_terms\""},
	IP:            whereHelpernull_String{field: "\"tenants\".\"ip\""},
	DateAccepted:  whereHelpernull_Time{field: "\"tenants\".\"date_accepted\""},
	CreatedAt:     whereHelpertime_Time{field: "\"tenants\".\"created_at\""},
	UpdatedAt:     whereHelpertime_Time{field: "\"tenants\".\"updated_at\""},
	DeletedAt:     whereHelpernull_Time{field: "\"tenants\".\"deleted_at\""},
}

// TenantRels is where relationship names are stored.
var TenantRels = struct {
	Plan          string
	Credential    string
	SettingTenant string
	PayTenants    string
	TenantModules string
	Users         string
}{
	Plan:          "Plan",
	Credential:    "Credential",
	SettingTenant: "SettingTenant",
	PayTenants:    "PayTenants",
	TenantModules: "TenantModules",
	Users:         "Users",
}

// tenantR is where relationships are stored.
type tenantR struct {
	Plan          *Plan             `boil:"Plan" json:"Plan" toml:"Plan" yaml:"Plan"`
	Credential    *Credential       `boil:"Credential" json:"Credential" toml:"Credential" yaml:"Credential"`
	SettingTenant *SettingTenant    `boil:"SettingTenant" json:"SettingTenant" toml:"SettingTenant" yaml:"SettingTenant"`
	PayTenants    PayTenantSlice    `boil:"PayTenants" json:"PayTenants" toml:"PayTenants" yaml:"PayTenants"`
	TenantModules TenantModuleSlice `boil:"TenantModules" json:"TenantModules" toml:"TenantModules" yaml:"TenantModules"`
	Users         UserSlice         `boil:"Users" json:"Users" toml:"Users" yaml:"Users"`
}

// NewStruct creates a new relationship struct
func (*tenantR) NewStruct() *tenantR {
	return &tenantR{}
}

func (o *Tenant) GetPlan() *Plan {
	if o == nil {
		return nil
	}

	return o.R.GetPlan()
}

func (r *tenantR) GetPlan() *Plan {
	if r == nil {
		return nil
	}

	return r.Plan
}

func (o *Tenant) GetCredential() *Credential {
	if o == nil {
		return nil
	}

	return o.R.GetCredential()
}

func (r *tenantR) GetCredential() *Credential {
	if r == nil {
		return nil
	}

	return r.Credential
}

func (o *Tenant) GetSettingTenant() *SettingTenant {
	if o == nil {
		return nil
	}

	return o.R.GetSettingTenant()
}

func (r *tenantR) GetSettingTenant() *SettingTenant {
	if r == nil {
		return nil
	}

	return r.SettingTenant
}

func (o *Tenant) GetPayTenants() PayTenantSlice {
	if o == nil {
		return nil
	}

	return o.R.GetPayTenants()
}

func (r *tenantR) GetPayTenants() PayTenantSlice {
	if r == nil {
		return nil
	}

	return r.PayTenants
}

func (o *Tenant) GetTenantModules() TenantModuleSlice {
	if o == nil {
		return nil
	}

	return o.R.GetTenantModules()
}

func (r *tenantR) GetTenantModules() TenantModuleSlice {
	if r == nil {
		return nil
	}

	return r.TenantModules
}

func (o *Tenant) GetUsers() UserSlice {
	if o == nil {
		return nil
	}

	return o.R.GetUsers()
}

func (r *tenantR) GetUsers() UserSlice {
	if r == nil {
		return nil
	}

	return r.Users
}

// tenantL is where Load methods for each relationship are stored.
type tenantL struct{}

var (
	tenantAllColumns            = []string{"id", "name", "identifier", "address", "phone", "email", "cuit_pdv", "is_active", "plan_id", "connection", "expiration", "accepted_terms", "ip", "date_accepted", "created_at", "updated_at", "deleted_at"}
	tenantColumnsWithoutDefault = []string{"name", "identifier", "address", "phone", "email", "cuit_pdv", "plan_id", "connection"}
	tenantColumnsWithDefault    = []string{"id", "is_active", "expiration", "accepted_terms", "ip", "date_accepted", "created_at", "updated_at", "deleted_at"}
	tenantPrimaryKeyColumns     = []string{"id"}
	tenantGeneratedColumns      = []string{}
)

type (
	// TenantSlice is an alias for a slice of pointers to Tenant.
	// This should almost always be used instead of []Tenant.
	TenantSlice []*Tenant
	// TenantHook is the signature for custom Tenant hook methods
	TenantHook func(context.Context, boil.ContextExecutor, *Tenant) error

	tenantQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	tenantType                 = reflect.TypeOf(&Tenant{})
	tenantMapping              = queries.MakeStructMapping(tenantType)
	tenantPrimaryKeyMapping, _ = queries.BindMapping(tenantType, tenantMapping, tenantPrimaryKeyColumns)
	tenantInsertCacheMut       sync.RWMutex
	tenantInsertCache          = make(map[string]insertCache)
	tenantUpdateCacheMut       sync.RWMutex
	tenantUpdateCache          = make(map[string]updateCache)
	tenantUpsertCacheMut       sync.RWMutex
	tenantUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var tenantAfterSelectMu sync.Mutex
var tenantAfterSelectHooks []TenantHook

var tenantBeforeInsertMu sync.Mutex
var tenantBeforeInsertHooks []TenantHook
var tenantAfterInsertMu sync.Mutex
var tenantAfterInsertHooks []TenantHook

var tenantBeforeUpdateMu sync.Mutex
var tenantBeforeUpdateHooks []TenantHook
var tenantAfterUpdateMu sync.Mutex
var tenantAfterUpdateHooks []TenantHook

var tenantBeforeDeleteMu sync.Mutex
var tenantBeforeDeleteHooks []TenantHook
var tenantAfterDeleteMu sync.Mutex
var tenantAfterDeleteHooks []TenantHook

var tenantBeforeUpsertMu sync.Mutex
var tenantBeforeUpsertHooks []TenantHook
var tenantAfterUpsertMu sync.Mutex
var tenantAfterUpsertHooks []TenantHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Tenant) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tenantAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Tenant) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tenantBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Tenant) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tenantAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Tenant) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tenantBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Tenant) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tenantAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Tenant) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tenantBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Tenant) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tenantAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Tenant) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tenantBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Tenant) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tenantAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTenantHook registers your hook function for all future operations.
func AddTenantHook(hookPoint boil.HookPoint, tenantHook TenantHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		tenantAfterSelectMu.Lock()
		tenantAfterSelectHooks = append(tenantAfterSelectHooks, tenantHook)
		tenantAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		tenantBeforeInsertMu.Lock()
		tenantBeforeInsertHooks = append(tenantBeforeInsertHooks, tenantHook)
		tenantBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		tenantAfterInsertMu.Lock()
		tenantAfterInsertHooks = append(tenantAfterInsertHooks, tenantHook)
		tenantAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		tenantBeforeUpdateMu.Lock()
		tenantBeforeUpdateHooks = append(tenantBeforeUpdateHooks, tenantHook)
		tenantBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		tenantAfterUpdateMu.Lock()
		tenantAfterUpdateHooks = append(tenantAfterUpdateHooks, tenantHook)
		tenantAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		tenantBeforeDeleteMu.Lock()
		tenantBeforeDeleteHooks = append(tenantBeforeDeleteHooks, tenantHook)
		tenantBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		tenantAfterDeleteMu.Lock()
		tenantAfterDeleteHooks = append(tenantAfterDeleteHooks, tenantHook)
		tenantAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		tenantBeforeUpsertMu.Lock()
		tenantBeforeUpsertHooks = append(tenantBeforeUpsertHooks, tenantHook)
		tenantBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		tenantAfterUpsertMu.Lock()
		tenantAfterUpsertHooks = append(tenantAfterUpsertHooks, tenantHook)
		tenantAfterUpsertMu.Unlock()
	}
}

// OneG returns a single tenant record from the query using the global executor.
func (q tenantQuery) OneG(ctx context.Context) (*Tenant, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single tenant record from the query.
func (q tenantQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Tenant, error) {
	o := &Tenant{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "master: failed to execute a one query for tenants")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all Tenant records from the query using the global executor.
func (q tenantQuery) AllG(ctx context.Context) (TenantSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all Tenant records from the query.
func (q tenantQuery) All(ctx context.Context, exec boil.ContextExecutor) (TenantSlice, error) {
	var o []*Tenant

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "master: failed to assign all query results to Tenant slice")
	}

	if len(tenantAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all Tenant records in the query using the global executor
func (q tenantQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all Tenant records in the query.
func (q tenantQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "master: failed to count tenants rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q tenantQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q tenantQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "master: failed to check if tenants exists")
	}

	return count > 0, nil
}

// Plan pointed to by the foreign key.
func (o *Tenant) Plan(mods ...qm.QueryMod) planQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.PlanID),
	}

	queryMods = append(queryMods, mods...)

	return Plans(queryMods...)
}

// Credential pointed to by the foreign key.
func (o *Tenant) Credential(mods ...qm.QueryMod) credentialQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"tenant_id\" = ?", o.ID),
	}

	queryMods = append(queryMods, mods...)

	return Credentials(queryMods...)
}

// SettingTenant pointed to by the foreign key.
func (o *Tenant) SettingTenant(mods ...qm.QueryMod) settingTenantQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"tenant_id\" = ?", o.ID),
	}

	queryMods = append(queryMods, mods...)

	return SettingTenants(queryMods...)
}

// PayTenants retrieves all the pay_tenant's PayTenants with an executor.
func (o *Tenant) PayTenants(mods ...qm.QueryMod) payTenantQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"pay_tenants\".\"tenant_id\"=?", o.ID),
	)

	return PayTenants(queryMods...)
}

// TenantModules retrieves all the tenant_module's TenantModules with an executor.
func (o *Tenant) TenantModules(mods ...qm.QueryMod) tenantModuleQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"tenant_modules\".\"tenant_id\"=?", o.ID),
	)

	return TenantModules(queryMods...)
}

// Users retrieves all the user's Users with an executor.
func (o *Tenant) Users(mods ...qm.QueryMod) userQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.InnerJoin("\"user_tenants\" on \"users\".\"id\" = \"user_tenants\".\"user_id\""),
		qm.Where("\"user_tenants\".\"tenant_id\"=?", o.ID),
	)

	return Users(queryMods...)
}

// LoadPlan allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (tenantL) LoadPlan(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTenant any, mods queries.Applicator) error {
	var slice []*Tenant
	var object *Tenant

	if singular {
		var ok bool
		object, ok = maybeTenant.(*Tenant)
		if !ok {
			object = new(Tenant)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTenant)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTenant))
			}
		}
	} else {
		s, ok := maybeTenant.(*[]*Tenant)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTenant)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTenant))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &tenantR{}
		}
		args[object.PlanID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &tenantR{}
			}

			args[obj.PlanID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`plans`),
		qm.WhereIn(`plans.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Plan")
	}

	var resultSlice []*Plan
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Plan")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for plans")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for plans")
	}

	if len(planAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Plan = foreign
		if foreign.R == nil {
			foreign.R = &planR{}
		}
		foreign.R.Tenants = append(foreign.R.Tenants, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.PlanID == foreign.ID {
				local.R.Plan = foreign
				if foreign.R == nil {
					foreign.R = &planR{}
				}
				foreign.R.Tenants = append(foreign.R.Tenants, local)
				break
			}
		}
	}

	return nil
}

// LoadCredential allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-1 relationship.
func (tenantL) LoadCredential(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTenant any, mods queries.Applicator) error {
	var slice []*Tenant
	var object *Tenant

	if singular {
		var ok bool
		object, ok = maybeTenant.(*Tenant)
		if !ok {
			object = new(Tenant)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTenant)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTenant))
			}
		}
	} else {
		s, ok := maybeTenant.(*[]*Tenant)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTenant)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTenant))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &tenantR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &tenantR{}
			}

			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`credentials`),
		qm.WhereIn(`credentials.tenant_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Credential")
	}

	var resultSlice []*Credential
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Credential")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for credentials")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for credentials")
	}

	if len(credentialAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Credential = foreign
		if foreign.R == nil {
			foreign.R = &credentialR{}
		}
		foreign.R.Tenant = object
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ID == foreign.TenantID {
				local.R.Credential = foreign
				if foreign.R == nil {
					foreign.R = &credentialR{}
				}
				foreign.R.Tenant = local
				break
			}
		}
	}

	return nil
}

// LoadSettingTenant allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-1 relationship.
func (tenantL) LoadSettingTenant(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTenant any, mods queries.Applicator) error {
	var slice []*Tenant
	var object *Tenant

	if singular {
		var ok bool
		object, ok = maybeTenant.(*Tenant)
		if !ok {
			object = new(Tenant)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTenant)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTenant))
			}
		}
	} else {
		s, ok := maybeTenant.(*[]*Tenant)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTenant)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTenant))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &tenantR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &tenantR{}
			}

			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`setting_tenants`),
		qm.WhereIn(`setting_tenants.tenant_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load SettingTenant")
	}

	var resultSlice []*SettingTenant
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice SettingTenant")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for setting_tenants")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for setting_tenants")
	}

	if len(settingTenantAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.SettingTenant = foreign
		if foreign.R == nil {
			foreign.R = &settingTenantR{}
		}
		foreign.R.Tenant = object
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ID == foreign.TenantID {
				local.R.SettingTenant = foreign
				if foreign.R == nil {
					foreign.R = &settingTenantR{}
				}
				foreign.R.Tenant = local
				break
			}
		}
	}

	return nil
}

// LoadPayTenants allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (tenantL) LoadPayTenants(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTenant any, mods queries.Applicator) error {
	var slice []*Tenant
	var object *Tenant

	if singular {
		var ok bool
		object, ok = maybeTenant.(*Tenant)
		if !ok {
			object = new(Tenant)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTenant)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTenant))
			}
		}
	} else {
		s, ok := maybeTenant.(*[]*Tenant)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTenant)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTenant))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &tenantR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &tenantR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`pay_tenants`),
		qm.WhereIn(`pay_tenants.tenant_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load pay_tenants")
	}

	var resultSlice []*PayTenant
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice pay_tenants")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on pay_tenants")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for pay_tenants")
	}

	if len(payTenantAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.PayTenants = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &payTenantR{}
			}
			foreign.R.Tenant = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.TenantID {
				local.R.PayTenants = append(local.R.PayTenants, foreign)
				if foreign.R == nil {
					foreign.R = &payTenantR{}
				}
				foreign.R.Tenant = local
				break
			}
		}
	}

	return nil
}

// LoadTenantModules allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (tenantL) LoadTenantModules(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTenant any, mods queries.Applicator) error {
	var slice []*Tenant
	var object *Tenant

	if singular {
		var ok bool
		object, ok = maybeTenant.(*Tenant)
		if !ok {
			object = new(Tenant)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTenant)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTenant))
			}
		}
	} else {
		s, ok := maybeTenant.(*[]*Tenant)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTenant)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTenant))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &tenantR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &tenantR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tenant_modules`),
		qm.WhereIn(`tenant_modules.tenant_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load tenant_modules")
	}

	var resultSlice []*TenantModule
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice tenant_modules")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on tenant_modules")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tenant_modules")
	}

	if len(tenantModuleAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.TenantModules = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &tenantModuleR{}
			}
			foreign.R.Tenant = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.TenantID {
				local.R.TenantModules = append(local.R.TenantModules, foreign)
				if foreign.R == nil {
					foreign.R = &tenantModuleR{}
				}
				foreign.R.Tenant = local
				break
			}
		}
	}

	return nil
}

// LoadUsers allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (tenantL) LoadUsers(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTenant any, mods queries.Applicator) error {
	var slice []*Tenant
	var object *Tenant

	if singular {
		var ok bool
		object, ok = maybeTenant.(*Tenant)
		if !ok {
			object = new(Tenant)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTenant)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTenant))
			}
		}
	} else {
		s, ok := maybeTenant.(*[]*Tenant)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTenant)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTenant))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &tenantR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &tenantR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.Select("\"users\".\"id\", \"users\".\"first_name\", \"users\".\"last_name\", \"users\".\"email\", \"users\".\"username\", \"users\".\"address\", \"users\".\"created_at\", \"users\".\"updated_at\", \"a\".\"tenant_id\""),
		qm.From("\"users\""),
		qm.InnerJoin("\"user_tenants\" as \"a\" on \"users\".\"id\" = \"a\".\"user_id\""),
		qm.WhereIn("\"a\".\"tenant_id\" in ?", argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load users")
	}

	var resultSlice []*User

	var localJoinCols []int64
	for results.Next() {
		one := new(User)
		var localJoinCol int64

		err = results.Scan(&one.ID, &one.FirstName, &one.LastName, &one.Email, &one.Username, &one.Address, &one.CreatedAt, &one.UpdatedAt, &localJoinCol)
		if err != nil {
			return errors.Wrap(err, "failed to scan eager loaded results for users")
		}
		if err = results.Err(); err != nil {
			return errors.Wrap(err, "failed to plebian-bind eager loaded slice users")
		}

		resultSlice = append(resultSlice, one)
		localJoinCols = append(localJoinCols, localJoinCol)
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Users = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &userR{}
			}
			foreign.R.Tenants = append(foreign.R.Tenants, object)
		}
		return nil
	}

	for i, foreign := range resultSlice {
		localJoinCol := localJoinCols[i]
		for _, local := range slice {
			if local.ID == localJoinCol {
				local.R.Users = append(local.R.Users, foreign)
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.Tenants = append(foreign.R.Tenants, local)
				break
			}
		}
	}

	return nil
}

// SetPlanG of the tenant to the related item.
// Sets o.R.Plan to related.
// Adds o to related.R.Tenants.
// Uses the global database handle.
func (o *Tenant) SetPlanG(ctx context.Context, insert bool, related *Plan) error {
	return o.SetPlan(ctx, boil.GetContextDB(), insert, related)
}

// SetPlan of the tenant to the related item.
// Sets o.R.Plan to related.
// Adds o to related.R.Tenants.
func (o *Tenant) SetPlan(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Plan) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"tenants\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"plan_id"}),
		strmangle.WhereClause("\"", "\"", 2, tenantPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.PlanID = related.ID
	if o.R == nil {
		o.R = &tenantR{
			Plan: related,
		}
	} else {
		o.R.Plan = related
	}

	if related.R == nil {
		related.R = &planR{
			Tenants: TenantSlice{o},
		}
	} else {
		related.R.Tenants = append(related.R.Tenants, o)
	}

	return nil
}

// SetCredentialG of the tenant to the related item.
// Sets o.R.Credential to related.
// Adds o to related.R.Tenant.
// Uses the global database handle.
func (o *Tenant) SetCredentialG(ctx context.Context, insert bool, related *Credential) error {
	return o.SetCredential(ctx, boil.GetContextDB(), insert, related)
}

// SetCredential of the tenant to the related item.
// Sets o.R.Credential to related.
// Adds o to related.R.Tenant.
func (o *Tenant) SetCredential(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Credential) error {
	var err error

	if insert {
		related.TenantID = o.ID

		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	} else {
		updateQuery := fmt.Sprintf(
			"UPDATE \"credentials\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, []string{"tenant_id"}),
			strmangle.WhereClause("\"", "\"", 2, credentialPrimaryKeyColumns),
		)
		values := []any{o.ID, related.ID}

		if boil.IsDebug(ctx) {
			writer := boil.DebugWriterFrom(ctx)
			fmt.Fprintln(writer, updateQuery)
			fmt.Fprintln(writer, values)
		}
		if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
			return errors.Wrap(err, "failed to update foreign table")
		}

		related.TenantID = o.ID
	}

	if o.R == nil {
		o.R = &tenantR{
			Credential: related,
		}
	} else {
		o.R.Credential = related
	}

	if related.R == nil {
		related.R = &credentialR{
			Tenant: o,
		}
	} else {
		related.R.Tenant = o
	}
	return nil
}

// SetSettingTenantG of the tenant to the related item.
// Sets o.R.SettingTenant to related.
// Adds o to related.R.Tenant.
// Uses the global database handle.
func (o *Tenant) SetSettingTenantG(ctx context.Context, insert bool, related *SettingTenant) error {
	return o.SetSettingTenant(ctx, boil.GetContextDB(), insert, related)
}

// SetSettingTenant of the tenant to the related item.
// Sets o.R.SettingTenant to related.
// Adds o to related.R.Tenant.
func (o *Tenant) SetSettingTenant(ctx context.Context, exec boil.ContextExecutor, insert bool, related *SettingTenant) error {
	var err error

	if insert {
		related.TenantID = o.ID

		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	} else {
		updateQuery := fmt.Sprintf(
			"UPDATE \"setting_tenants\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, []string{"tenant_id"}),
			strmangle.WhereClause("\"", "\"", 2, settingTenantPrimaryKeyColumns),
		)
		values := []any{o.ID, related.ID}

		if boil.IsDebug(ctx) {
			writer := boil.DebugWriterFrom(ctx)
			fmt.Fprintln(writer, updateQuery)
			fmt.Fprintln(writer, values)
		}
		if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
			return errors.Wrap(err, "failed to update foreign table")
		}

		related.TenantID = o.ID
	}

	if o.R == nil {
		o.R = &tenantR{
			SettingTenant: related,
		}
	} else {
		o.R.SettingTenant = related
	}

	if related.R == nil {
		related.R = &settingTenantR{
			Tenant: o,
		}
	} else {
		related.R.Tenant = o
	}
	return nil
}

// AddPayTenantsG adds the given related objects to the existing relationships
// of the tenant, optionally inserting them as new records.
// Appends related to o.R.PayTenants.
// Sets related.R.Tenant appropriately.
// Uses the global database handle.
func (o *Tenant) AddPayTenantsG(ctx context.Context, insert bool, related ...*PayTenant) error {
	return o.AddPayTenants(ctx, boil.GetContextDB(), insert, related...)
}

// AddPayTenants adds the given related objects to the existing relationships
// of the tenant, optionally inserting them as new records.
// Appends related to o.R.PayTenants.
// Sets related.R.Tenant appropriately.
func (o *Tenant) AddPayTenants(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*PayTenant) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.TenantID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"pay_tenants\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"tenant_id"}),
				strmangle.WhereClause("\"", "\"", 2, payTenantPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.TenantID = o.ID
		}
	}

	if o.R == nil {
		o.R = &tenantR{
			PayTenants: related,
		}
	} else {
		o.R.PayTenants = append(o.R.PayTenants, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &payTenantR{
				Tenant: o,
			}
		} else {
			rel.R.Tenant = o
		}
	}
	return nil
}

// AddTenantModulesG adds the given related objects to the existing relationships
// of the tenant, optionally inserting them as new records.
// Appends related to o.R.TenantModules.
// Sets related.R.Tenant appropriately.
// Uses the global database handle.
func (o *Tenant) AddTenantModulesG(ctx context.Context, insert bool, related ...*TenantModule) error {
	return o.AddTenantModules(ctx, boil.GetContextDB(), insert, related...)
}

// AddTenantModules adds the given related objects to the existing relationships
// of the tenant, optionally inserting them as new records.
// Appends related to o.R.TenantModules.
// Sets related.R.Tenant appropriately.
func (o *Tenant) AddTenantModules(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*TenantModule) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.TenantID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"tenant_modules\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"tenant_id"}),
				strmangle.WhereClause("\"", "\"", 2, tenantModulePrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.TenantID = o.ID
		}
	}

	if o.R == nil {
		o.R = &tenantR{
			TenantModules: related,
		}
	} else {
		o.R.TenantModules = append(o.R.TenantModules, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &tenantModuleR{
				Tenant: o,
			}
		} else {
			rel.R.Tenant = o
		}
	}
	return nil
}

// AddUsersG adds the given related objects to the existing relationships
// of the tenant, optionally inserting them as new records.
// Appends related to o.R.Users.
// Sets related.R.Tenants appropriately.
// Uses the global database handle.
func (o *Tenant) AddUsersG(ctx context.Context, insert bool, related ...*User) error {
	return o.AddUsers(ctx, boil.GetContextDB(), insert, related...)
}

// AddUsers adds the given related objects to the existing relationships
// of the tenant, optionally inserting them as new records.
// Appends related to o.R.Users.
// Sets related.R.Tenants appropriately.
func (o *Tenant) AddUsers(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*User) error {
	var err error
	for _, rel := range related {
		if insert {
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		}
	}

	for _, rel := range related {
		query := "insert into \"user_tenants\" (\"tenant_id\", \"user_id\") values ($1, $2)"
		values := []any{o.ID, rel.ID}

		if boil.IsDebug(ctx) {
			writer := boil.DebugWriterFrom(ctx)
			fmt.Fprintln(writer, query)
			fmt.Fprintln(writer, values)
		}
		_, err = exec.ExecContext(ctx, query, values...)
		if err != nil {
			return errors.Wrap(err, "failed to insert into join table")
		}
	}
	if o.R == nil {
		o.R = &tenantR{
			Users: related,
		}
	} else {
		o.R.Users = append(o.R.Users, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &userR{
				Tenants: TenantSlice{o},
			}
		} else {
			rel.R.Tenants = append(rel.R.Tenants, o)
		}
	}
	return nil
}

// SetUsersG removes all previously related items of the
// tenant replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Tenants's Users accordingly.
// Replaces o.R.Users with related.
// Sets related.R.Tenants's Users accordingly.
// Uses the global database handle.
func (o *Tenant) SetUsersG(ctx context.Context, insert bool, related ...*User) error {
	return o.SetUsers(ctx, boil.GetContextDB(), insert, related...)
}

// SetUsers removes all previously related items of the
// tenant replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Tenants's Users accordingly.
// Replaces o.R.Users with related.
// Sets related.R.Tenants's Users accordingly.
func (o *Tenant) SetUsers(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*User) error {
	query := "delete from \"user_tenants\" where \"tenant_id\" = $1"
	values := []any{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	removeUsersFromTenantsSlice(o, related)
	if o.R != nil {
		o.R.Users = nil
	}

	return o.AddUsers(ctx, exec, insert, related...)
}

// RemoveUsersG relationships from objects passed in.
// Removes related items from R.Users (uses pointer comparison, removal does not keep order)
// Sets related.R.Tenants.
// Uses the global database handle.
func (o *Tenant) RemoveUsersG(ctx context.Context, related ...*User) error {
	return o.RemoveUsers(ctx, boil.GetContextDB(), related...)
}

// RemoveUsers relationships from objects passed in.
// Removes related items from R.Users (uses pointer comparison, removal does not keep order)
// Sets related.R.Tenants.
func (o *Tenant) RemoveUsers(ctx context.Context, exec boil.ContextExecutor, related ...*User) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	query := fmt.Sprintf(
		"delete from \"user_tenants\" where \"tenant_id\" = $1 and \"user_id\" in (%s)",
		strmangle.Placeholders(dialect.UseIndexPlaceholders, len(related), 2, 1),
	)
	values := []any{o.ID}
	for _, rel := range related {
		values = append(values, rel.ID)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}
	removeUsersFromTenantsSlice(o, related)
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.Users {
			if rel != ri {
				continue
			}

			ln := len(o.R.Users)
			if ln > 1 && i < ln-1 {
				o.R.Users[i] = o.R.Users[ln-1]
			}
			o.R.Users = o.R.Users[:ln-1]
			break
		}
	}

	return nil
}

func removeUsersFromTenantsSlice(o *Tenant, related []*User) {
	for _, rel := range related {
		if rel.R == nil {
			continue
		}
		for i, ri := range rel.R.Tenants {
			if o.ID != ri.ID {
				continue
			}

			ln := len(rel.R.Tenants)
			if ln > 1 && i < ln-1 {
				rel.R.Tenants[i] = rel.R.Tenants[ln-1]
			}
			rel.R.Tenants = rel.R.Tenants[:ln-1]
			break
		}
	}
}

// Tenants retrieves all the records using an executor.
func Tenants(mods ...qm.QueryMod) tenantQuery {
	mods = append(mods, qm.From("\"tenants\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"tenants\".*"})
	}

	return tenantQuery{q}
}

// FindTenantG retrieves a single record by ID.
func FindTenantG(ctx context.Context, iD int64, selectCols ...string) (*Tenant, error) {
	return FindTenant(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindTenant retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTenant(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*Tenant, error) {
	tenantObj := &Tenant{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"tenants\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, tenantObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "master: unable to select from tenants")
	}

	if err = tenantObj.doAfterSelectHooks(ctx, exec); err != nil {
		return tenantObj, err
	}

	return tenantObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Tenant) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Tenant) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("master: no tenants provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(tenantColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	tenantInsertCacheMut.RLock()
	cache, cached := tenantInsertCache[key]
	tenantInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			tenantAllColumns,
			tenantColumnsWithDefault,
			tenantColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(tenantType, tenantMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(tenantType, tenantMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"tenants\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"tenants\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "master: unable to insert into tenants")
	}

	if !cached {
		tenantInsertCacheMut.Lock()
		tenantInsertCache[key] = cache
		tenantInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single Tenant record using the global executor.
// See Update for more documentation.
func (o *Tenant) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the Tenant.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Tenant) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	tenantUpdateCacheMut.RLock()
	cache, cached := tenantUpdateCache[key]
	tenantUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			tenantAllColumns,
			tenantPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("master: unable to update tenants, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"tenants\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, tenantPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(tenantType, tenantMapping, append(wl, tenantPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to update tenants row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "master: failed to get rows affected by update for tenants")
	}

	if !cached {
		tenantUpdateCacheMut.Lock()
		tenantUpdateCache[key] = cache
		tenantUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q tenantQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q tenantQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to update all for tenants")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to retrieve rows affected for tenants")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o TenantSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TenantSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("master: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tenantPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"tenants\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, tenantPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to update all in tenant slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to retrieve rows affected all in update all tenant")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Tenant) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Tenant) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("master: no tenants provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(tenantColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	tenantUpsertCacheMut.RLock()
	cache, cached := tenantUpsertCache[key]
	tenantUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			tenantAllColumns,
			tenantColumnsWithDefault,
			tenantColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			tenantAllColumns,
			tenantPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("master: unable to upsert tenants, could not build update column list")
		}

		ret := strmangle.SetComplement(tenantAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(tenantPrimaryKeyColumns) == 0 {
				return errors.New("master: unable to upsert tenants, could not build conflict column list")
			}

			conflict = make([]string, len(tenantPrimaryKeyColumns))
			copy(conflict, tenantPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"tenants\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(tenantType, tenantMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(tenantType, tenantMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "master: unable to upsert tenants")
	}

	if !cached {
		tenantUpsertCacheMut.Lock()
		tenantUpsertCache[key] = cache
		tenantUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single Tenant record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Tenant) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single Tenant record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Tenant) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("master: no Tenant provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), tenantPrimaryKeyMapping)
	sql := "DELETE FROM \"tenants\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to delete from tenants")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "master: failed to get rows affected by delete for tenants")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q tenantQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q tenantQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("master: no tenantQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to delete all from tenants")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "master: failed to get rows affected by deleteall for tenants")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o TenantSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TenantSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(tenantBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tenantPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"tenants\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, tenantPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "master: unable to delete all from tenant slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "master: failed to get rows affected by deleteall for tenants")
	}

	if len(tenantAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Tenant) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("master: no Tenant provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Tenant) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindTenant(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TenantSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("master: empty TenantSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TenantSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := TenantSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tenantPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"tenants\".* FROM \"tenants\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, tenantPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "master: unable to reload all in TenantSlice")
	}

	*o = slice

	return nil
}

// TenantExistsG checks if the Tenant row exists.
func TenantExistsG(ctx context.Context, iD int64) (bool, error) {
	return TenantExists(ctx, boil.GetContextDB(), iD)
}

// TenantExists checks if the Tenant row exists.
func TenantExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"tenants\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "master: unable to check if tenants exists")
	}

	return exists, nil
}

// Exists checks if the Tenant row exists.
func (o *Tenant) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return TenantExists(ctx, exec, o.ID)
}
