{
 "title": "Logs Api",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RAM usada total",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dockerstats_memory_usage_bytes{container_name=~\"noa-gestion|mariadb-noa|prometheus|grafana|noa_redis\"})\n"
    }
   ]
  },
  {
   "title": "CPU usada %",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dockerstats_cpu_usage_ratio{name=~\"noa-gestion|mariadb-noa|prometheus|grafana|noa_redis\"})\n"
    }
   ]
  },
  {
   "title": "Errores críticos (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n  count_over_time (\n    {container=\"/noa-gestion\", stream=\"stderr\"} |= \"panic:\"\n    [$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Intentos fallidos",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n  count_over_time (\n    {container=\"/noa-gestion\"}\n      |= \"Request from\"\n      != \"/metrics\"\n      | regexp `Request from (?P<ip>.*?): \\w+ (?P<endpoint>/\\S+) (?P<status>\\d{3}) took (?P<duration>[\\d.]+)ms`\n      | status=~\"4..|5..\"\n    [$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Promedio tiempo respuesta",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time(\n  {container=\"/noa-gestion\"}\n  != \"/metrics\"\n  | regexp `took (?P<duration>[0-9.]+)ms`\n  | unwrap duration [$__range]\n)"
    }
   ]
  },
  {
   "title": "últimas 24 horas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({container=\"/noa-gestion\"} |= \"Request from\" != \"GET /metrics\" [24h])"
    }
   ]
  },
  {
   "title": "Promedio de peticiones por dia (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=\"/noa-gestion\"} |= \"Request from\" != \"/metrics\" [7d])) / 7"
    }
   ]
  },
  {
   "title": "CPU usado",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (name) (dockerstats_cpu_usage_ratio{container_name=~\"noa-gestion|mariadb-noa|prometheus|grafana|noa_redis\"})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"/noa-gestion\"} |~ \"(ERROR|FATAL|CRITICAL|PANIC|WARN)\""
    }
   ]
  },
  {
   "title": "Ram usada",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (name) (dockerstats_memory_usage_bytes{name=~\"noa-gestion|mariadb-noa|prometheus|grafana|noa_redis\"}) / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Peticiones lentas (>300ms)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container_name=\"noa-gestion\"} |= \"request completed\""
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"noa-gestion\"} |= \"request completed\" != \"/metrics\"\n| regexp `^(?P<datetime>\\S+\\s+\\S+)\\s+INF\\s+request completed duration_ms=(?P<duration>[\\d.]+)\\s+ip=(?P<ip>\\S*)\\s+method=(?P<method>\\S+)\\s+path=(?P<path>\\S+)\\s+status=(?P<status>\\d+)`"
    }
   ]
  },
  {
   "title": "Endpoint mas usados (7d)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10,\n  sum by (path) (\n    count_over_time(\n      {container=\"noa-gestion\"}\n      |= \"request completed\"\n      != \"/metrics\"\n      | regexp `path=(?P<path>/\\S+)`\n      [7d]\n    )\n  )\n)\n"
    }
   ]
  }
 ]
}