// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package tenant

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ExpenseBuyItem is an object representing the database table.
type ExpenseBuyItem struct {
	ID           int64         `boil:"id" json:"id" toml:"id" yaml:"id"`
	ExpenseBuyID int64         `boil:"expense_buy_id" json:"expense_buy_id" toml:"expense_buy_id" yaml:"expense_buy_id"`
	ProductID    int64         `boil:"product_id" json:"product_id" toml:"product_id" yaml:"product_id"`
	Amount       types.Decimal `boil:"amount" json:"amount" toml:"amount" yaml:"amount"`
	Price        types.Decimal `boil:"price" json:"price" toml:"price" yaml:"price"`
	Discount     types.Decimal `boil:"discount" json:"discount" toml:"discount" yaml:"discount"`
	TypeDiscount string        `boil:"type_discount" json:"type_discount" toml:"type_discount" yaml:"type_discount"`
	Subtotal     types.Decimal `boil:"subtotal" json:"subtotal" toml:"subtotal" yaml:"subtotal"`
	Total        types.Decimal `boil:"total" json:"total" toml:"total" yaml:"total"`
	CreatedAt    time.Time     `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt    time.Time     `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *expenseBuyItemR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L expenseBuyItemL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ExpenseBuyItemColumns = struct {
	ID           string
	ExpenseBuyID string
	ProductID    string
	Amount       string
	Price        string
	Discount     string
	TypeDiscount string
	Subtotal     string
	Total        string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "id",
	ExpenseBuyID: "expense_buy_id",
	ProductID:    "product_id",
	Amount:       "amount",
	Price:        "price",
	Discount:     "discount",
	TypeDiscount: "type_discount",
	Subtotal:     "subtotal",
	Total:        "total",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
}

var ExpenseBuyItemTableColumns = struct {
	ID           string
	ExpenseBuyID string
	ProductID    string
	Amount       string
	Price        string
	Discount     string
	TypeDiscount string
	Subtotal     string
	Total        string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "expense_buy_items.id",
	ExpenseBuyID: "expense_buy_items.expense_buy_id",
	ProductID:    "expense_buy_items.product_id",
	Amount:       "expense_buy_items.amount",
	Price:        "expense_buy_items.price",
	Discount:     "expense_buy_items.discount",
	TypeDiscount: "expense_buy_items.type_discount",
	Subtotal:     "expense_buy_items.subtotal",
	Total:        "expense_buy_items.total",
	CreatedAt:    "expense_buy_items.created_at",
	UpdatedAt:    "expense_buy_items.updated_at",
}

// Generated where

var ExpenseBuyItemWhere = struct {
	ID           whereHelperint64
	ExpenseBuyID whereHelperint64
	ProductID    whereHelperint64
	Amount       whereHelpertypes_Decimal
	Price        whereHelpertypes_Decimal
	Discount     whereHelpertypes_Decimal
	TypeDiscount whereHelperstring
	Subtotal     whereHelpertypes_Decimal
	Total        whereHelpertypes_Decimal
	CreatedAt    whereHelpertime_Time
	UpdatedAt    whereHelpertime_Time
}{
	ID:           whereHelperint64{field: "\"expense_buy_items\".\"id\""},
	ExpenseBuyID: whereHelperint64{field: "\"expense_buy_items\".\"expense_buy_id\""},
	ProductID:    whereHelperint64{field: "\"expense_buy_items\".\"product_id\""},
	Amount:       whereHelpertypes_Decimal{field: "\"expense_buy_items\".\"amount\""},
	Price:        whereHelpertypes_Decimal{field: "\"expense_buy_items\".\"price\""},
	Discount:     whereHelpertypes_Decimal{field: "\"expense_buy_items\".\"discount\""},
	TypeDiscount: whereHelperstring{field: "\"expense_buy_items\".\"type_discount\""},
	Subtotal:     whereHelpertypes_Decimal{field: "\"expense_buy_items\".\"subtotal\""},
	Total:        whereHelpertypes_Decimal{field: "\"expense_buy_items\".\"total\""},
	CreatedAt:    whereHelpertime_Time{field: "\"expense_buy_items\".\"created_at\""},
	UpdatedAt:    whereHelpertime_Time{field: "\"expense_buy_items\".\"updated_at\""},
}

// ExpenseBuyItemRels is where relationship names are stored.
var ExpenseBuyItemRels = struct {
	Product    string
	ExpenseBuy string
}{
	Product:    "Product",
	ExpenseBuy: "ExpenseBuy",
}

// expenseBuyItemR is where relationships are stored.
type expenseBuyItemR struct {
	Product    *Product    `boil:"Product" json:"Product" toml:"Product" yaml:"Product"`
	ExpenseBuy *ExpenseBuy `boil:"ExpenseBuy" json:"ExpenseBuy" toml:"ExpenseBuy" yaml:"ExpenseBuy"`
}

// NewStruct creates a new relationship struct
func (*expenseBuyItemR) NewStruct() *expenseBuyItemR {
	return &expenseBuyItemR{}
}

func (o *ExpenseBuyItem) GetProduct() *Product {
	if o == nil {
		return nil
	}

	return o.R.GetProduct()
}

func (r *expenseBuyItemR) GetProduct() *Product {
	if r == nil {
		return nil
	}

	return r.Product
}

func (o *ExpenseBuyItem) GetExpenseBuy() *ExpenseBuy {
	if o == nil {
		return nil
	}

	return o.R.GetExpenseBuy()
}

func (r *expenseBuyItemR) GetExpenseBuy() *ExpenseBuy {
	if r == nil {
		return nil
	}

	return r.ExpenseBuy
}

// expenseBuyItemL is where Load methods for each relationship are stored.
type expenseBuyItemL struct{}

var (
	expenseBuyItemAllColumns            = []string{"id", "expense_buy_id", "product_id", "amount", "price", "discount", "type_discount", "subtotal", "total", "created_at", "updated_at"}
	expenseBuyItemColumnsWithoutDefault = []string{"expense_buy_id", "product_id", "amount", "price", "subtotal", "total"}
	expenseBuyItemColumnsWithDefault    = []string{"id", "discount", "type_discount", "created_at", "updated_at"}
	expenseBuyItemPrimaryKeyColumns     = []string{"id"}
	expenseBuyItemGeneratedColumns      = []string{}
)

type (
	// ExpenseBuyItemSlice is an alias for a slice of pointers to ExpenseBuyItem.
	// This should almost always be used instead of []ExpenseBuyItem.
	ExpenseBuyItemSlice []*ExpenseBuyItem
	// ExpenseBuyItemHook is the signature for custom ExpenseBuyItem hook methods
	ExpenseBuyItemHook func(context.Context, boil.ContextExecutor, *ExpenseBuyItem) error

	expenseBuyItemQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	expenseBuyItemType                 = reflect.TypeOf(&ExpenseBuyItem{})
	expenseBuyItemMapping              = queries.MakeStructMapping(expenseBuyItemType)
	expenseBuyItemPrimaryKeyMapping, _ = queries.BindMapping(expenseBuyItemType, expenseBuyItemMapping, expenseBuyItemPrimaryKeyColumns)
	expenseBuyItemInsertCacheMut       sync.RWMutex
	expenseBuyItemInsertCache          = make(map[string]insertCache)
	expenseBuyItemUpdateCacheMut       sync.RWMutex
	expenseBuyItemUpdateCache          = make(map[string]updateCache)
	expenseBuyItemUpsertCacheMut       sync.RWMutex
	expenseBuyItemUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var expenseBuyItemAfterSelectMu sync.Mutex
var expenseBuyItemAfterSelectHooks []ExpenseBuyItemHook

var expenseBuyItemBeforeInsertMu sync.Mutex
var expenseBuyItemBeforeInsertHooks []ExpenseBuyItemHook
var expenseBuyItemAfterInsertMu sync.Mutex
var expenseBuyItemAfterInsertHooks []ExpenseBuyItemHook

var expenseBuyItemBeforeUpdateMu sync.Mutex
var expenseBuyItemBeforeUpdateHooks []ExpenseBuyItemHook
var expenseBuyItemAfterUpdateMu sync.Mutex
var expenseBuyItemAfterUpdateHooks []ExpenseBuyItemHook

var expenseBuyItemBeforeDeleteMu sync.Mutex
var expenseBuyItemBeforeDeleteHooks []ExpenseBuyItemHook
var expenseBuyItemAfterDeleteMu sync.Mutex
var expenseBuyItemAfterDeleteHooks []ExpenseBuyItemHook

var expenseBuyItemBeforeUpsertMu sync.Mutex
var expenseBuyItemBeforeUpsertHooks []ExpenseBuyItemHook
var expenseBuyItemAfterUpsertMu sync.Mutex
var expenseBuyItemAfterUpsertHooks []ExpenseBuyItemHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ExpenseBuyItem) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range expenseBuyItemAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ExpenseBuyItem) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range expenseBuyItemBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ExpenseBuyItem) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range expenseBuyItemAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ExpenseBuyItem) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range expenseBuyItemBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ExpenseBuyItem) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range expenseBuyItemAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ExpenseBuyItem) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range expenseBuyItemBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ExpenseBuyItem) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range expenseBuyItemAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ExpenseBuyItem) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range expenseBuyItemBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ExpenseBuyItem) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range expenseBuyItemAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddExpenseBuyItemHook registers your hook function for all future operations.
func AddExpenseBuyItemHook(hookPoint boil.HookPoint, expenseBuyItemHook ExpenseBuyItemHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		expenseBuyItemAfterSelectMu.Lock()
		expenseBuyItemAfterSelectHooks = append(expenseBuyItemAfterSelectHooks, expenseBuyItemHook)
		expenseBuyItemAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		expenseBuyItemBeforeInsertMu.Lock()
		expenseBuyItemBeforeInsertHooks = append(expenseBuyItemBeforeInsertHooks, expenseBuyItemHook)
		expenseBuyItemBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		expenseBuyItemAfterInsertMu.Lock()
		expenseBuyItemAfterInsertHooks = append(expenseBuyItemAfterInsertHooks, expenseBuyItemHook)
		expenseBuyItemAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		expenseBuyItemBeforeUpdateMu.Lock()
		expenseBuyItemBeforeUpdateHooks = append(expenseBuyItemBeforeUpdateHooks, expenseBuyItemHook)
		expenseBuyItemBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		expenseBuyItemAfterUpdateMu.Lock()
		expenseBuyItemAfterUpdateHooks = append(expenseBuyItemAfterUpdateHooks, expenseBuyItemHook)
		expenseBuyItemAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		expenseBuyItemBeforeDeleteMu.Lock()
		expenseBuyItemBeforeDeleteHooks = append(expenseBuyItemBeforeDeleteHooks, expenseBuyItemHook)
		expenseBuyItemBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		expenseBuyItemAfterDeleteMu.Lock()
		expenseBuyItemAfterDeleteHooks = append(expenseBuyItemAfterDeleteHooks, expenseBuyItemHook)
		expenseBuyItemAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		expenseBuyItemBeforeUpsertMu.Lock()
		expenseBuyItemBeforeUpsertHooks = append(expenseBuyItemBeforeUpsertHooks, expenseBuyItemHook)
		expenseBuyItemBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		expenseBuyItemAfterUpsertMu.Lock()
		expenseBuyItemAfterUpsertHooks = append(expenseBuyItemAfterUpsertHooks, expenseBuyItemHook)
		expenseBuyItemAfterUpsertMu.Unlock()
	}
}

// OneG returns a single expenseBuyItem record from the query using the global executor.
func (q expenseBuyItemQuery) OneG(ctx context.Context) (*ExpenseBuyItem, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single expenseBuyItem record from the query.
func (q expenseBuyItemQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ExpenseBuyItem, error) {
	o := &ExpenseBuyItem{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "tenant: failed to execute a one query for expense_buy_items")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all ExpenseBuyItem records from the query using the global executor.
func (q expenseBuyItemQuery) AllG(ctx context.Context) (ExpenseBuyItemSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all ExpenseBuyItem records from the query.
func (q expenseBuyItemQuery) All(ctx context.Context, exec boil.ContextExecutor) (ExpenseBuyItemSlice, error) {
	var o []*ExpenseBuyItem

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "tenant: failed to assign all query results to ExpenseBuyItem slice")
	}

	if len(expenseBuyItemAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all ExpenseBuyItem records in the query using the global executor
func (q expenseBuyItemQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all ExpenseBuyItem records in the query.
func (q expenseBuyItemQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to count expense_buy_items rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q expenseBuyItemQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q expenseBuyItemQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "tenant: failed to check if expense_buy_items exists")
	}

	return count > 0, nil
}

// Product pointed to by the foreign key.
func (o *ExpenseBuyItem) Product(mods ...qm.QueryMod) productQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ProductID),
	}

	queryMods = append(queryMods, mods...)

	return Products(queryMods...)
}

// ExpenseBuy pointed to by the foreign key.
func (o *ExpenseBuyItem) ExpenseBuy(mods ...qm.QueryMod) expenseBuyQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ExpenseBuyID),
	}

	queryMods = append(queryMods, mods...)

	return ExpenseBuys(queryMods...)
}

// LoadProduct allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (expenseBuyItemL) LoadProduct(ctx context.Context, e boil.ContextExecutor, singular bool, maybeExpenseBuyItem any, mods queries.Applicator) error {
	var slice []*ExpenseBuyItem
	var object *ExpenseBuyItem

	if singular {
		var ok bool
		object, ok = maybeExpenseBuyItem.(*ExpenseBuyItem)
		if !ok {
			object = new(ExpenseBuyItem)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeExpenseBuyItem)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeExpenseBuyItem))
			}
		}
	} else {
		s, ok := maybeExpenseBuyItem.(*[]*ExpenseBuyItem)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeExpenseBuyItem)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeExpenseBuyItem))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &expenseBuyItemR{}
		}
		args[object.ProductID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &expenseBuyItemR{}
			}

			args[obj.ProductID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`products`),
		qm.WhereIn(`products.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Product")
	}

	var resultSlice []*Product
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Product")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for products")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for products")
	}

	if len(productAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Product = foreign
		if foreign.R == nil {
			foreign.R = &productR{}
		}
		foreign.R.ExpenseBuyItems = append(foreign.R.ExpenseBuyItems, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ProductID == foreign.ID {
				local.R.Product = foreign
				if foreign.R == nil {
					foreign.R = &productR{}
				}
				foreign.R.ExpenseBuyItems = append(foreign.R.ExpenseBuyItems, local)
				break
			}
		}
	}

	return nil
}

// LoadExpenseBuy allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (expenseBuyItemL) LoadExpenseBuy(ctx context.Context, e boil.ContextExecutor, singular bool, maybeExpenseBuyItem any, mods queries.Applicator) error {
	var slice []*ExpenseBuyItem
	var object *ExpenseBuyItem

	if singular {
		var ok bool
		object, ok = maybeExpenseBuyItem.(*ExpenseBuyItem)
		if !ok {
			object = new(ExpenseBuyItem)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeExpenseBuyItem)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeExpenseBuyItem))
			}
		}
	} else {
		s, ok := maybeExpenseBuyItem.(*[]*ExpenseBuyItem)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeExpenseBuyItem)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeExpenseBuyItem))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &expenseBuyItemR{}
		}
		args[object.ExpenseBuyID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &expenseBuyItemR{}
			}

			args[obj.ExpenseBuyID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`expense_buys`),
		qm.WhereIn(`expense_buys.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ExpenseBuy")
	}

	var resultSlice []*ExpenseBuy
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ExpenseBuy")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for expense_buys")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for expense_buys")
	}

	if len(expenseBuyAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ExpenseBuy = foreign
		if foreign.R == nil {
			foreign.R = &expenseBuyR{}
		}
		foreign.R.ExpenseBuyItems = append(foreign.R.ExpenseBuyItems, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ExpenseBuyID == foreign.ID {
				local.R.ExpenseBuy = foreign
				if foreign.R == nil {
					foreign.R = &expenseBuyR{}
				}
				foreign.R.ExpenseBuyItems = append(foreign.R.ExpenseBuyItems, local)
				break
			}
		}
	}

	return nil
}

// SetProductG of the expenseBuyItem to the related item.
// Sets o.R.Product to related.
// Adds o to related.R.ExpenseBuyItems.
// Uses the global database handle.
func (o *ExpenseBuyItem) SetProductG(ctx context.Context, insert bool, related *Product) error {
	return o.SetProduct(ctx, boil.GetContextDB(), insert, related)
}

// SetProduct of the expenseBuyItem to the related item.
// Sets o.R.Product to related.
// Adds o to related.R.ExpenseBuyItems.
func (o *ExpenseBuyItem) SetProduct(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Product) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"expense_buy_items\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"product_id"}),
		strmangle.WhereClause("\"", "\"", 2, expenseBuyItemPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ProductID = related.ID
	if o.R == nil {
		o.R = &expenseBuyItemR{
			Product: related,
		}
	} else {
		o.R.Product = related
	}

	if related.R == nil {
		related.R = &productR{
			ExpenseBuyItems: ExpenseBuyItemSlice{o},
		}
	} else {
		related.R.ExpenseBuyItems = append(related.R.ExpenseBuyItems, o)
	}

	return nil
}

// SetExpenseBuyG of the expenseBuyItem to the related item.
// Sets o.R.ExpenseBuy to related.
// Adds o to related.R.ExpenseBuyItems.
// Uses the global database handle.
func (o *ExpenseBuyItem) SetExpenseBuyG(ctx context.Context, insert bool, related *ExpenseBuy) error {
	return o.SetExpenseBuy(ctx, boil.GetContextDB(), insert, related)
}

// SetExpenseBuy of the expenseBuyItem to the related item.
// Sets o.R.ExpenseBuy to related.
// Adds o to related.R.ExpenseBuyItems.
func (o *ExpenseBuyItem) SetExpenseBuy(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ExpenseBuy) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"expense_buy_items\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"expense_buy_id"}),
		strmangle.WhereClause("\"", "\"", 2, expenseBuyItemPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ExpenseBuyID = related.ID
	if o.R == nil {
		o.R = &expenseBuyItemR{
			ExpenseBuy: related,
		}
	} else {
		o.R.ExpenseBuy = related
	}

	if related.R == nil {
		related.R = &expenseBuyR{
			ExpenseBuyItems: ExpenseBuyItemSlice{o},
		}
	} else {
		related.R.ExpenseBuyItems = append(related.R.ExpenseBuyItems, o)
	}

	return nil
}

// ExpenseBuyItems retrieves all the records using an executor.
func ExpenseBuyItems(mods ...qm.QueryMod) expenseBuyItemQuery {
	mods = append(mods, qm.From("\"expense_buy_items\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"expense_buy_items\".*"})
	}

	return expenseBuyItemQuery{q}
}

// FindExpenseBuyItemG retrieves a single record by ID.
func FindExpenseBuyItemG(ctx context.Context, iD int64, selectCols ...string) (*ExpenseBuyItem, error) {
	return FindExpenseBuyItem(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindExpenseBuyItem retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindExpenseBuyItem(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*ExpenseBuyItem, error) {
	expenseBuyItemObj := &ExpenseBuyItem{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"expense_buy_items\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, expenseBuyItemObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "tenant: unable to select from expense_buy_items")
	}

	if err = expenseBuyItemObj.doAfterSelectHooks(ctx, exec); err != nil {
		return expenseBuyItemObj, err
	}

	return expenseBuyItemObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *ExpenseBuyItem) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ExpenseBuyItem) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("tenant: no expense_buy_items provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(expenseBuyItemColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	expenseBuyItemInsertCacheMut.RLock()
	cache, cached := expenseBuyItemInsertCache[key]
	expenseBuyItemInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			expenseBuyItemAllColumns,
			expenseBuyItemColumnsWithDefault,
			expenseBuyItemColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(expenseBuyItemType, expenseBuyItemMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(expenseBuyItemType, expenseBuyItemMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"expense_buy_items\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"expense_buy_items\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "tenant: unable to insert into expense_buy_items")
	}

	if !cached {
		expenseBuyItemInsertCacheMut.Lock()
		expenseBuyItemInsertCache[key] = cache
		expenseBuyItemInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single ExpenseBuyItem record using the global executor.
// See Update for more documentation.
func (o *ExpenseBuyItem) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the ExpenseBuyItem.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ExpenseBuyItem) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	expenseBuyItemUpdateCacheMut.RLock()
	cache, cached := expenseBuyItemUpdateCache[key]
	expenseBuyItemUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			expenseBuyItemAllColumns,
			expenseBuyItemPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("tenant: unable to update expense_buy_items, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"expense_buy_items\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, expenseBuyItemPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(expenseBuyItemType, expenseBuyItemMapping, append(wl, expenseBuyItemPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to update expense_buy_items row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to get rows affected by update for expense_buy_items")
	}

	if !cached {
		expenseBuyItemUpdateCacheMut.Lock()
		expenseBuyItemUpdateCache[key] = cache
		expenseBuyItemUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q expenseBuyItemQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q expenseBuyItemQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to update all for expense_buy_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to retrieve rows affected for expense_buy_items")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o ExpenseBuyItemSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ExpenseBuyItemSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("tenant: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), expenseBuyItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"expense_buy_items\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, expenseBuyItemPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to update all in expenseBuyItem slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to retrieve rows affected all in update all expenseBuyItem")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *ExpenseBuyItem) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ExpenseBuyItem) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("tenant: no expense_buy_items provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(expenseBuyItemColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	expenseBuyItemUpsertCacheMut.RLock()
	cache, cached := expenseBuyItemUpsertCache[key]
	expenseBuyItemUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			expenseBuyItemAllColumns,
			expenseBuyItemColumnsWithDefault,
			expenseBuyItemColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			expenseBuyItemAllColumns,
			expenseBuyItemPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("tenant: unable to upsert expense_buy_items, could not build update column list")
		}

		ret := strmangle.SetComplement(expenseBuyItemAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(expenseBuyItemPrimaryKeyColumns) == 0 {
				return errors.New("tenant: unable to upsert expense_buy_items, could not build conflict column list")
			}

			conflict = make([]string, len(expenseBuyItemPrimaryKeyColumns))
			copy(conflict, expenseBuyItemPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"expense_buy_items\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(expenseBuyItemType, expenseBuyItemMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(expenseBuyItemType, expenseBuyItemMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "tenant: unable to upsert expense_buy_items")
	}

	if !cached {
		expenseBuyItemUpsertCacheMut.Lock()
		expenseBuyItemUpsertCache[key] = cache
		expenseBuyItemUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single ExpenseBuyItem record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *ExpenseBuyItem) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single ExpenseBuyItem record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ExpenseBuyItem) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("tenant: no ExpenseBuyItem provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), expenseBuyItemPrimaryKeyMapping)
	sql := "DELETE FROM \"expense_buy_items\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to delete from expense_buy_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to get rows affected by delete for expense_buy_items")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q expenseBuyItemQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q expenseBuyItemQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("tenant: no expenseBuyItemQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to delete all from expense_buy_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to get rows affected by deleteall for expense_buy_items")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o ExpenseBuyItemSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ExpenseBuyItemSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(expenseBuyItemBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), expenseBuyItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"expense_buy_items\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, expenseBuyItemPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to delete all from expenseBuyItem slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to get rows affected by deleteall for expense_buy_items")
	}

	if len(expenseBuyItemAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *ExpenseBuyItem) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("tenant: no ExpenseBuyItem provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ExpenseBuyItem) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindExpenseBuyItem(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ExpenseBuyItemSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("tenant: empty ExpenseBuyItemSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ExpenseBuyItemSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ExpenseBuyItemSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), expenseBuyItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"expense_buy_items\".* FROM \"expense_buy_items\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, expenseBuyItemPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "tenant: unable to reload all in ExpenseBuyItemSlice")
	}

	*o = slice

	return nil
}

// ExpenseBuyItemExistsG checks if the ExpenseBuyItem row exists.
func ExpenseBuyItemExistsG(ctx context.Context, iD int64) (bool, error) {
	return ExpenseBuyItemExists(ctx, boil.GetContextDB(), iD)
}

// ExpenseBuyItemExists checks if the ExpenseBuyItem row exists.
func ExpenseBuyItemExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"expense_buy_items\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "tenant: unable to check if expense_buy_items exists")
	}

	return exists, nil
}

// Exists checks if the ExpenseBuyItem row exists.
func (o *ExpenseBuyItem) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ExpenseBuyItemExists(ctx, exec, o.ID)
}
