// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package tenant

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// IncomeEcommerce is an object representing the database table.
type IncomeEcommerce struct {
	ID                int64         `boil:"id" json:"id" toml:"id" yaml:"id"`
	PaymentID         string        `boil:"payment_id" json:"payment_id" toml:"payment_id" yaml:"payment_id"`
	ExternalReference string        `boil:"external_reference" json:"external_reference" toml:"external_reference" yaml:"external_reference"`
	Status            string        `boil:"status" json:"status" toml:"status" yaml:"status"`
	Total             types.Decimal `boil:"total" json:"total" toml:"total" yaml:"total"`
	DeliveryStatus    string        `boil:"delivery_status" json:"delivery_status" toml:"delivery_status" yaml:"delivery_status"`
	DeliveryID        string        `boil:"delivery_id" json:"delivery_id" toml:"delivery_id" yaml:"delivery_id"`
	DateCreated       string        `boil:"date_created" json:"date_created" toml:"date_created" yaml:"date_created"`
	DateApproved      string        `boil:"date_approved" json:"date_approved" toml:"date_approved" yaml:"date_approved"`
	TransactionAmount types.Decimal `boil:"transaction_amount" json:"transaction_amount" toml:"transaction_amount" yaml:"transaction_amount"`
	NetReceivedAmount types.Decimal `boil:"net_received_amount" json:"net_received_amount" toml:"net_received_amount" yaml:"net_received_amount"`
	PayerFirstName    string        `boil:"payer_first_name" json:"payer_first_name" toml:"payer_first_name" yaml:"payer_first_name"`
	PayerLastName     string        `boil:"payer_last_name" json:"payer_last_name" toml:"payer_last_name" yaml:"payer_last_name"`
	PayerEmail        string        `boil:"payer_email" json:"payer_email" toml:"payer_email" yaml:"payer_email"`
	PayMethod         string        `boil:"pay_method" json:"pay_method" toml:"pay_method" yaml:"pay_method"`
	OperationType     string        `boil:"operation_type" json:"operation_type" toml:"operation_type" yaml:"operation_type"`
	Message           null.String   `boil:"message" json:"message,omitempty" toml:"message" yaml:"message,omitempty"`
	CreatedAt         time.Time     `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt         time.Time     `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *incomeEcommerceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L incomeEcommerceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var IncomeEcommerceColumns = struct {
	ID                string
	PaymentID         string
	ExternalReference string
	Status            string
	Total             string
	DeliveryStatus    string
	DeliveryID        string
	DateCreated       string
	DateApproved      string
	TransactionAmount string
	NetReceivedAmount string
	PayerFirstName    string
	PayerLastName     string
	PayerEmail        string
	PayMethod         string
	OperationType     string
	Message           string
	CreatedAt         string
	UpdatedAt         string
}{
	ID:                "id",
	PaymentID:         "payment_id",
	ExternalReference: "external_reference",
	Status:            "status",
	Total:             "total",
	DeliveryStatus:    "delivery_status",
	DeliveryID:        "delivery_id",
	DateCreated:       "date_created",
	DateApproved:      "date_approved",
	TransactionAmount: "transaction_amount",
	NetReceivedAmount: "net_received_amount",
	PayerFirstName:    "payer_first_name",
	PayerLastName:     "payer_last_name",
	PayerEmail:        "payer_email",
	PayMethod:         "pay_method",
	OperationType:     "operation_type",
	Message:           "message",
	CreatedAt:         "created_at",
	UpdatedAt:         "updated_at",
}

var IncomeEcommerceTableColumns = struct {
	ID                string
	PaymentID         string
	ExternalReference string
	Status            string
	Total             string
	DeliveryStatus    string
	DeliveryID        string
	DateCreated       string
	DateApproved      string
	TransactionAmount string
	NetReceivedAmount string
	PayerFirstName    string
	PayerLastName     string
	PayerEmail        string
	PayMethod         string
	OperationType     string
	Message           string
	CreatedAt         string
	UpdatedAt         string
}{
	ID:                "income_ecommerces.id",
	PaymentID:         "income_ecommerces.payment_id",
	ExternalReference: "income_ecommerces.external_reference",
	Status:            "income_ecommerces.status",
	Total:             "income_ecommerces.total",
	DeliveryStatus:    "income_ecommerces.delivery_status",
	DeliveryID:        "income_ecommerces.delivery_id",
	DateCreated:       "income_ecommerces.date_created",
	DateApproved:      "income_ecommerces.date_approved",
	TransactionAmount: "income_ecommerces.transaction_amount",
	NetReceivedAmount: "income_ecommerces.net_received_amount",
	PayerFirstName:    "income_ecommerces.payer_first_name",
	PayerLastName:     "income_ecommerces.payer_last_name",
	PayerEmail:        "income_ecommerces.payer_email",
	PayMethod:         "income_ecommerces.pay_method",
	OperationType:     "income_ecommerces.operation_type",
	Message:           "income_ecommerces.message",
	CreatedAt:         "income_ecommerces.created_at",
	UpdatedAt:         "income_ecommerces.updated_at",
}

// Generated where

var IncomeEcommerceWhere = struct {
	ID                whereHelperint64
	PaymentID         whereHelperstring
	ExternalReference whereHelperstring
	Status            whereHelperstring
	Total             whereHelpertypes_Decimal
	DeliveryStatus    whereHelperstring
	DeliveryID        whereHelperstring
	DateCreated       whereHelperstring
	DateApproved      whereHelperstring
	TransactionAmount whereHelpertypes_Decimal
	NetReceivedAmount whereHelpertypes_Decimal
	PayerFirstName    whereHelperstring
	PayerLastName     whereHelperstring
	PayerEmail        whereHelperstring
	PayMethod         whereHelperstring
	OperationType     whereHelperstring
	Message           whereHelpernull_String
	CreatedAt         whereHelpertime_Time
	UpdatedAt         whereHelpertime_Time
}{
	ID:                whereHelperint64{field: "\"income_ecommerces\".\"id\""},
	PaymentID:         whereHelperstring{field: "\"income_ecommerces\".\"payment_id\""},
	ExternalReference: whereHelperstring{field: "\"income_ecommerces\".\"external_reference\""},
	Status:            whereHelperstring{field: "\"income_ecommerces\".\"status\""},
	Total:             whereHelpertypes_Decimal{field: "\"income_ecommerces\".\"total\""},
	DeliveryStatus:    whereHelperstring{field: "\"income_ecommerces\".\"delivery_status\""},
	DeliveryID:        whereHelperstring{field: "\"income_ecommerces\".\"delivery_id\""},
	DateCreated:       whereHelperstring{field: "\"income_ecommerces\".\"date_created\""},
	DateApproved:      whereHelperstring{field: "\"income_ecommerces\".\"date_approved\""},
	TransactionAmount: whereHelpertypes_Decimal{field: "\"income_ecommerces\".\"transaction_amount\""},
	NetReceivedAmount: whereHelpertypes_Decimal{field: "\"income_ecommerces\".\"net_received_amount\""},
	PayerFirstName:    whereHelperstring{field: "\"income_ecommerces\".\"payer_first_name\""},
	PayerLastName:     whereHelperstring{field: "\"income_ecommerces\".\"payer_last_name\""},
	PayerEmail:        whereHelperstring{field: "\"income_ecommerces\".\"payer_email\""},
	PayMethod:         whereHelperstring{field: "\"income_ecommerces\".\"pay_method\""},
	OperationType:     whereHelperstring{field: "\"income_ecommerces\".\"operation_type\""},
	Message:           whereHelpernull_String{field: "\"income_ecommerces\".\"message\""},
	CreatedAt:         whereHelpertime_Time{field: "\"income_ecommerces\".\"created_at\""},
	UpdatedAt:         whereHelpertime_Time{field: "\"income_ecommerces\".\"updated_at\""},
}

// IncomeEcommerceRels is where relationship names are stored.
var IncomeEcommerceRels = struct {
	IncomeEcommerceItems string
}{
	IncomeEcommerceItems: "IncomeEcommerceItems",
}

// incomeEcommerceR is where relationships are stored.
type incomeEcommerceR struct {
	IncomeEcommerceItems IncomeEcommerceItemSlice `boil:"IncomeEcommerceItems" json:"IncomeEcommerceItems" toml:"IncomeEcommerceItems" yaml:"IncomeEcommerceItems"`
}

// NewStruct creates a new relationship struct
func (*incomeEcommerceR) NewStruct() *incomeEcommerceR {
	return &incomeEcommerceR{}
}

func (o *IncomeEcommerce) GetIncomeEcommerceItems() IncomeEcommerceItemSlice {
	if o == nil {
		return nil
	}

	return o.R.GetIncomeEcommerceItems()
}

func (r *incomeEcommerceR) GetIncomeEcommerceItems() IncomeEcommerceItemSlice {
	if r == nil {
		return nil
	}

	return r.IncomeEcommerceItems
}

// incomeEcommerceL is where Load methods for each relationship are stored.
type incomeEcommerceL struct{}

var (
	incomeEcommerceAllColumns            = []string{"id", "payment_id", "external_reference", "status", "total", "delivery_status", "delivery_id", "date_created", "date_approved", "transaction_amount", "net_received_amount", "payer_first_name", "payer_last_name", "payer_email", "pay_method", "operation_type", "message", "created_at", "updated_at"}
	incomeEcommerceColumnsWithoutDefault = []string{"payment_id", "external_reference", "status", "total", "delivery_status", "delivery_id", "date_created", "date_approved", "transaction_amount", "net_received_amount", "payer_first_name", "payer_last_name", "payer_email", "pay_method", "operation_type"}
	incomeEcommerceColumnsWithDefault    = []string{"id", "message", "created_at", "updated_at"}
	incomeEcommercePrimaryKeyColumns     = []string{"id"}
	incomeEcommerceGeneratedColumns      = []string{}
)

type (
	// IncomeEcommerceSlice is an alias for a slice of pointers to IncomeEcommerce.
	// This should almost always be used instead of []IncomeEcommerce.
	IncomeEcommerceSlice []*IncomeEcommerce
	// IncomeEcommerceHook is the signature for custom IncomeEcommerce hook methods
	IncomeEcommerceHook func(context.Context, boil.ContextExecutor, *IncomeEcommerce) error

	incomeEcommerceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	incomeEcommerceType                 = reflect.TypeOf(&IncomeEcommerce{})
	incomeEcommerceMapping              = queries.MakeStructMapping(incomeEcommerceType)
	incomeEcommercePrimaryKeyMapping, _ = queries.BindMapping(incomeEcommerceType, incomeEcommerceMapping, incomeEcommercePrimaryKeyColumns)
	incomeEcommerceInsertCacheMut       sync.RWMutex
	incomeEcommerceInsertCache          = make(map[string]insertCache)
	incomeEcommerceUpdateCacheMut       sync.RWMutex
	incomeEcommerceUpdateCache          = make(map[string]updateCache)
	incomeEcommerceUpsertCacheMut       sync.RWMutex
	incomeEcommerceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var incomeEcommerceAfterSelectMu sync.Mutex
var incomeEcommerceAfterSelectHooks []IncomeEcommerceHook

var incomeEcommerceBeforeInsertMu sync.Mutex
var incomeEcommerceBeforeInsertHooks []IncomeEcommerceHook
var incomeEcommerceAfterInsertMu sync.Mutex
var incomeEcommerceAfterInsertHooks []IncomeEcommerceHook

var incomeEcommerceBeforeUpdateMu sync.Mutex
var incomeEcommerceBeforeUpdateHooks []IncomeEcommerceHook
var incomeEcommerceAfterUpdateMu sync.Mutex
var incomeEcommerceAfterUpdateHooks []IncomeEcommerceHook

var incomeEcommerceBeforeDeleteMu sync.Mutex
var incomeEcommerceBeforeDeleteHooks []IncomeEcommerceHook
var incomeEcommerceAfterDeleteMu sync.Mutex
var incomeEcommerceAfterDeleteHooks []IncomeEcommerceHook

var incomeEcommerceBeforeUpsertMu sync.Mutex
var incomeEcommerceBeforeUpsertHooks []IncomeEcommerceHook
var incomeEcommerceAfterUpsertMu sync.Mutex
var incomeEcommerceAfterUpsertHooks []IncomeEcommerceHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *IncomeEcommerce) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range incomeEcommerceAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *IncomeEcommerce) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range incomeEcommerceBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *IncomeEcommerce) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range incomeEcommerceAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *IncomeEcommerce) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range incomeEcommerceBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *IncomeEcommerce) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range incomeEcommerceAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *IncomeEcommerce) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range incomeEcommerceBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *IncomeEcommerce) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range incomeEcommerceAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *IncomeEcommerce) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range incomeEcommerceBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *IncomeEcommerce) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range incomeEcommerceAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddIncomeEcommerceHook registers your hook function for all future operations.
func AddIncomeEcommerceHook(hookPoint boil.HookPoint, incomeEcommerceHook IncomeEcommerceHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		incomeEcommerceAfterSelectMu.Lock()
		incomeEcommerceAfterSelectHooks = append(incomeEcommerceAfterSelectHooks, incomeEcommerceHook)
		incomeEcommerceAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		incomeEcommerceBeforeInsertMu.Lock()
		incomeEcommerceBeforeInsertHooks = append(incomeEcommerceBeforeInsertHooks, incomeEcommerceHook)
		incomeEcommerceBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		incomeEcommerceAfterInsertMu.Lock()
		incomeEcommerceAfterInsertHooks = append(incomeEcommerceAfterInsertHooks, incomeEcommerceHook)
		incomeEcommerceAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		incomeEcommerceBeforeUpdateMu.Lock()
		incomeEcommerceBeforeUpdateHooks = append(incomeEcommerceBeforeUpdateHooks, incomeEcommerceHook)
		incomeEcommerceBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		incomeEcommerceAfterUpdateMu.Lock()
		incomeEcommerceAfterUpdateHooks = append(incomeEcommerceAfterUpdateHooks, incomeEcommerceHook)
		incomeEcommerceAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		incomeEcommerceBeforeDeleteMu.Lock()
		incomeEcommerceBeforeDeleteHooks = append(incomeEcommerceBeforeDeleteHooks, incomeEcommerceHook)
		incomeEcommerceBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		incomeEcommerceAfterDeleteMu.Lock()
		incomeEcommerceAfterDeleteHooks = append(incomeEcommerceAfterDeleteHooks, incomeEcommerceHook)
		incomeEcommerceAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		incomeEcommerceBeforeUpsertMu.Lock()
		incomeEcommerceBeforeUpsertHooks = append(incomeEcommerceBeforeUpsertHooks, incomeEcommerceHook)
		incomeEcommerceBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		incomeEcommerceAfterUpsertMu.Lock()
		incomeEcommerceAfterUpsertHooks = append(incomeEcommerceAfterUpsertHooks, incomeEcommerceHook)
		incomeEcommerceAfterUpsertMu.Unlock()
	}
}

// OneG returns a single incomeEcommerce record from the query using the global executor.
func (q incomeEcommerceQuery) OneG(ctx context.Context) (*IncomeEcommerce, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single incomeEcommerce record from the query.
func (q incomeEcommerceQuery) One(ctx context.Context, exec boil.ContextExecutor) (*IncomeEcommerce, error) {
	o := &IncomeEcommerce{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "tenant: failed to execute a one query for income_ecommerces")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all IncomeEcommerce records from the query using the global executor.
func (q incomeEcommerceQuery) AllG(ctx context.Context) (IncomeEcommerceSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all IncomeEcommerce records from the query.
func (q incomeEcommerceQuery) All(ctx context.Context, exec boil.ContextExecutor) (IncomeEcommerceSlice, error) {
	var o []*IncomeEcommerce

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "tenant: failed to assign all query results to IncomeEcommerce slice")
	}

	if len(incomeEcommerceAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all IncomeEcommerce records in the query using the global executor
func (q incomeEcommerceQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all IncomeEcommerce records in the query.
func (q incomeEcommerceQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to count income_ecommerces rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q incomeEcommerceQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q incomeEcommerceQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "tenant: failed to check if income_ecommerces exists")
	}

	return count > 0, nil
}

// IncomeEcommerceItems retrieves all the income_ecommerce_item's IncomeEcommerceItems with an executor.
func (o *IncomeEcommerce) IncomeEcommerceItems(mods ...qm.QueryMod) incomeEcommerceItemQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"income_ecommerce_items\".\"income_ecommerce_id\"=?", o.ID),
	)

	return IncomeEcommerceItems(queryMods...)
}

// LoadIncomeEcommerceItems allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (incomeEcommerceL) LoadIncomeEcommerceItems(ctx context.Context, e boil.ContextExecutor, singular bool, maybeIncomeEcommerce any, mods queries.Applicator) error {
	var slice []*IncomeEcommerce
	var object *IncomeEcommerce

	if singular {
		var ok bool
		object, ok = maybeIncomeEcommerce.(*IncomeEcommerce)
		if !ok {
			object = new(IncomeEcommerce)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeIncomeEcommerce)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeIncomeEcommerce))
			}
		}
	} else {
		s, ok := maybeIncomeEcommerce.(*[]*IncomeEcommerce)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeIncomeEcommerce)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeIncomeEcommerce))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &incomeEcommerceR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &incomeEcommerceR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`income_ecommerce_items`),
		qm.WhereIn(`income_ecommerce_items.income_ecommerce_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load income_ecommerce_items")
	}

	var resultSlice []*IncomeEcommerceItem
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice income_ecommerce_items")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on income_ecommerce_items")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for income_ecommerce_items")
	}

	if len(incomeEcommerceItemAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.IncomeEcommerceItems = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &incomeEcommerceItemR{}
			}
			foreign.R.IncomeEcommerce = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.IncomeEcommerceID) {
				local.R.IncomeEcommerceItems = append(local.R.IncomeEcommerceItems, foreign)
				if foreign.R == nil {
					foreign.R = &incomeEcommerceItemR{}
				}
				foreign.R.IncomeEcommerce = local
				break
			}
		}
	}

	return nil
}

// AddIncomeEcommerceItemsG adds the given related objects to the existing relationships
// of the income_ecommerce, optionally inserting them as new records.
// Appends related to o.R.IncomeEcommerceItems.
// Sets related.R.IncomeEcommerce appropriately.
// Uses the global database handle.
func (o *IncomeEcommerce) AddIncomeEcommerceItemsG(ctx context.Context, insert bool, related ...*IncomeEcommerceItem) error {
	return o.AddIncomeEcommerceItems(ctx, boil.GetContextDB(), insert, related...)
}

// AddIncomeEcommerceItems adds the given related objects to the existing relationships
// of the income_ecommerce, optionally inserting them as new records.
// Appends related to o.R.IncomeEcommerceItems.
// Sets related.R.IncomeEcommerce appropriately.
func (o *IncomeEcommerce) AddIncomeEcommerceItems(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*IncomeEcommerceItem) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.IncomeEcommerceID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"income_ecommerce_items\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"income_ecommerce_id"}),
				strmangle.WhereClause("\"", "\"", 2, incomeEcommerceItemPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.IncomeEcommerceID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &incomeEcommerceR{
			IncomeEcommerceItems: related,
		}
	} else {
		o.R.IncomeEcommerceItems = append(o.R.IncomeEcommerceItems, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &incomeEcommerceItemR{
				IncomeEcommerce: o,
			}
		} else {
			rel.R.IncomeEcommerce = o
		}
	}
	return nil
}

// SetIncomeEcommerceItemsG removes all previously related items of the
// income_ecommerce replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.IncomeEcommerce's IncomeEcommerceItems accordingly.
// Replaces o.R.IncomeEcommerceItems with related.
// Sets related.R.IncomeEcommerce's IncomeEcommerceItems accordingly.
// Uses the global database handle.
func (o *IncomeEcommerce) SetIncomeEcommerceItemsG(ctx context.Context, insert bool, related ...*IncomeEcommerceItem) error {
	return o.SetIncomeEcommerceItems(ctx, boil.GetContextDB(), insert, related...)
}

// SetIncomeEcommerceItems removes all previously related items of the
// income_ecommerce replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.IncomeEcommerce's IncomeEcommerceItems accordingly.
// Replaces o.R.IncomeEcommerceItems with related.
// Sets related.R.IncomeEcommerce's IncomeEcommerceItems accordingly.
func (o *IncomeEcommerce) SetIncomeEcommerceItems(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*IncomeEcommerceItem) error {
	query := "update \"income_ecommerce_items\" set \"income_ecommerce_id\" = null where \"income_ecommerce_id\" = $1"
	values := []any{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.IncomeEcommerceItems {
			queries.SetScanner(&rel.IncomeEcommerceID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.IncomeEcommerce = nil
		}
		o.R.IncomeEcommerceItems = nil
	}

	return o.AddIncomeEcommerceItems(ctx, exec, insert, related...)
}

// RemoveIncomeEcommerceItemsG relationships from objects passed in.
// Removes related items from R.IncomeEcommerceItems (uses pointer comparison, removal does not keep order)
// Sets related.R.IncomeEcommerce.
// Uses the global database handle.
func (o *IncomeEcommerce) RemoveIncomeEcommerceItemsG(ctx context.Context, related ...*IncomeEcommerceItem) error {
	return o.RemoveIncomeEcommerceItems(ctx, boil.GetContextDB(), related...)
}

// RemoveIncomeEcommerceItems relationships from objects passed in.
// Removes related items from R.IncomeEcommerceItems (uses pointer comparison, removal does not keep order)
// Sets related.R.IncomeEcommerce.
func (o *IncomeEcommerce) RemoveIncomeEcommerceItems(ctx context.Context, exec boil.ContextExecutor, related ...*IncomeEcommerceItem) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.IncomeEcommerceID, nil)
		if rel.R != nil {
			rel.R.IncomeEcommerce = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("income_ecommerce_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.IncomeEcommerceItems {
			if rel != ri {
				continue
			}

			ln := len(o.R.IncomeEcommerceItems)
			if ln > 1 && i < ln-1 {
				o.R.IncomeEcommerceItems[i] = o.R.IncomeEcommerceItems[ln-1]
			}
			o.R.IncomeEcommerceItems = o.R.IncomeEcommerceItems[:ln-1]
			break
		}
	}

	return nil
}

// IncomeEcommerces retrieves all the records using an executor.
func IncomeEcommerces(mods ...qm.QueryMod) incomeEcommerceQuery {
	mods = append(mods, qm.From("\"income_ecommerces\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"income_ecommerces\".*"})
	}

	return incomeEcommerceQuery{q}
}

// FindIncomeEcommerceG retrieves a single record by ID.
func FindIncomeEcommerceG(ctx context.Context, iD int64, selectCols ...string) (*IncomeEcommerce, error) {
	return FindIncomeEcommerce(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindIncomeEcommerce retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindIncomeEcommerce(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*IncomeEcommerce, error) {
	incomeEcommerceObj := &IncomeEcommerce{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"income_ecommerces\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, incomeEcommerceObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "tenant: unable to select from income_ecommerces")
	}

	if err = incomeEcommerceObj.doAfterSelectHooks(ctx, exec); err != nil {
		return incomeEcommerceObj, err
	}

	return incomeEcommerceObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *IncomeEcommerce) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *IncomeEcommerce) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("tenant: no income_ecommerces provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(incomeEcommerceColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	incomeEcommerceInsertCacheMut.RLock()
	cache, cached := incomeEcommerceInsertCache[key]
	incomeEcommerceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			incomeEcommerceAllColumns,
			incomeEcommerceColumnsWithDefault,
			incomeEcommerceColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(incomeEcommerceType, incomeEcommerceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(incomeEcommerceType, incomeEcommerceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"income_ecommerces\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"income_ecommerces\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "tenant: unable to insert into income_ecommerces")
	}

	if !cached {
		incomeEcommerceInsertCacheMut.Lock()
		incomeEcommerceInsertCache[key] = cache
		incomeEcommerceInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single IncomeEcommerce record using the global executor.
// See Update for more documentation.
func (o *IncomeEcommerce) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the IncomeEcommerce.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *IncomeEcommerce) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	incomeEcommerceUpdateCacheMut.RLock()
	cache, cached := incomeEcommerceUpdateCache[key]
	incomeEcommerceUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			incomeEcommerceAllColumns,
			incomeEcommercePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("tenant: unable to update income_ecommerces, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"income_ecommerces\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, incomeEcommercePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(incomeEcommerceType, incomeEcommerceMapping, append(wl, incomeEcommercePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to update income_ecommerces row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to get rows affected by update for income_ecommerces")
	}

	if !cached {
		incomeEcommerceUpdateCacheMut.Lock()
		incomeEcommerceUpdateCache[key] = cache
		incomeEcommerceUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q incomeEcommerceQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q incomeEcommerceQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to update all for income_ecommerces")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to retrieve rows affected for income_ecommerces")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o IncomeEcommerceSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o IncomeEcommerceSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("tenant: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), incomeEcommercePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"income_ecommerces\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, incomeEcommercePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to update all in incomeEcommerce slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to retrieve rows affected all in update all incomeEcommerce")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *IncomeEcommerce) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *IncomeEcommerce) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("tenant: no income_ecommerces provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(incomeEcommerceColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	incomeEcommerceUpsertCacheMut.RLock()
	cache, cached := incomeEcommerceUpsertCache[key]
	incomeEcommerceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			incomeEcommerceAllColumns,
			incomeEcommerceColumnsWithDefault,
			incomeEcommerceColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			incomeEcommerceAllColumns,
			incomeEcommercePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("tenant: unable to upsert income_ecommerces, could not build update column list")
		}

		ret := strmangle.SetComplement(incomeEcommerceAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(incomeEcommercePrimaryKeyColumns) == 0 {
				return errors.New("tenant: unable to upsert income_ecommerces, could not build conflict column list")
			}

			conflict = make([]string, len(incomeEcommercePrimaryKeyColumns))
			copy(conflict, incomeEcommercePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"income_ecommerces\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(incomeEcommerceType, incomeEcommerceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(incomeEcommerceType, incomeEcommerceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "tenant: unable to upsert income_ecommerces")
	}

	if !cached {
		incomeEcommerceUpsertCacheMut.Lock()
		incomeEcommerceUpsertCache[key] = cache
		incomeEcommerceUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single IncomeEcommerce record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *IncomeEcommerce) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single IncomeEcommerce record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *IncomeEcommerce) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("tenant: no IncomeEcommerce provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), incomeEcommercePrimaryKeyMapping)
	sql := "DELETE FROM \"income_ecommerces\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to delete from income_ecommerces")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to get rows affected by delete for income_ecommerces")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q incomeEcommerceQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q incomeEcommerceQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("tenant: no incomeEcommerceQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to delete all from income_ecommerces")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to get rows affected by deleteall for income_ecommerces")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o IncomeEcommerceSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o IncomeEcommerceSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(incomeEcommerceBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), incomeEcommercePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"income_ecommerces\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, incomeEcommercePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to delete all from incomeEcommerce slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to get rows affected by deleteall for income_ecommerces")
	}

	if len(incomeEcommerceAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *IncomeEcommerce) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("tenant: no IncomeEcommerce provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *IncomeEcommerce) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindIncomeEcommerce(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *IncomeEcommerceSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("tenant: empty IncomeEcommerceSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *IncomeEcommerceSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := IncomeEcommerceSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), incomeEcommercePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"income_ecommerces\".* FROM \"income_ecommerces\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, incomeEcommercePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "tenant: unable to reload all in IncomeEcommerceSlice")
	}

	*o = slice

	return nil
}

// IncomeEcommerceExistsG checks if the IncomeEcommerce row exists.
func IncomeEcommerceExistsG(ctx context.Context, iD int64) (bool, error) {
	return IncomeEcommerceExists(ctx, boil.GetContextDB(), iD)
}

// IncomeEcommerceExists checks if the IncomeEcommerce row exists.
func IncomeEcommerceExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"income_ecommerces\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "tenant: unable to check if income_ecommerces exists")
	}

	return exists, nil
}

// Exists checks if the IncomeEcommerce row exists.
func (o *IncomeEcommerce) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return IncomeEcommerceExists(ctx, exec, o.ID)
}
