// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package tenant

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// PointSale is an object representing the database table.
type PointSale struct {
	ID          int64       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name        string      `boil:"name" json:"name" toml:"name" yaml:"name"`
	Description null.String `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`
	Number      int64       `boil:"number" json:"number" toml:"number" yaml:"number"`
	IsDeposit   bool        `boil:"is_deposit" json:"is_deposit" toml:"is_deposit" yaml:"is_deposit"`
	IsMain      bool        `boil:"is_main" json:"is_main" toml:"is_main" yaml:"is_main"`
	CreatedAt   time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt   time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DeleteAt    null.Time   `boil:"delete_at" json:"delete_at,omitempty" toml:"delete_at" yaml:"delete_at,omitempty"`

	R *pointSaleR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L pointSaleL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PointSaleColumns = struct {
	ID          string
	Name        string
	Description string
	Number      string
	IsDeposit   string
	IsMain      string
	CreatedAt   string
	UpdatedAt   string
	DeleteAt    string
}{
	ID:          "id",
	Name:        "name",
	Description: "description",
	Number:      "number",
	IsDeposit:   "is_deposit",
	IsMain:      "is_main",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
	DeleteAt:    "delete_at",
}

var PointSaleTableColumns = struct {
	ID          string
	Name        string
	Description string
	Number      string
	IsDeposit   string
	IsMain      string
	CreatedAt   string
	UpdatedAt   string
	DeleteAt    string
}{
	ID:          "point_sales.id",
	Name:        "point_sales.name",
	Description: "point_sales.description",
	Number:      "point_sales.number",
	IsDeposit:   "point_sales.is_deposit",
	IsMain:      "point_sales.is_main",
	CreatedAt:   "point_sales.created_at",
	UpdatedAt:   "point_sales.updated_at",
	DeleteAt:    "point_sales.delete_at",
}

// Generated where

var PointSaleWhere = struct {
	ID          whereHelperint64
	Name        whereHelperstring
	Description whereHelpernull_String
	Number      whereHelperint64
	IsDeposit   whereHelperbool
	IsMain      whereHelperbool
	CreatedAt   whereHelpertime_Time
	UpdatedAt   whereHelpertime_Time
	DeleteAt    whereHelpernull_Time
}{
	ID:          whereHelperint64{field: "\"point_sales\".\"id\""},
	Name:        whereHelperstring{field: "\"point_sales\".\"name\""},
	Description: whereHelpernull_String{field: "\"point_sales\".\"description\""},
	Number:      whereHelperint64{field: "\"point_sales\".\"number\""},
	IsDeposit:   whereHelperbool{field: "\"point_sales\".\"is_deposit\""},
	IsMain:      whereHelperbool{field: "\"point_sales\".\"is_main\""},
	CreatedAt:   whereHelpertime_Time{field: "\"point_sales\".\"created_at\""},
	UpdatedAt:   whereHelpertime_Time{field: "\"point_sales\".\"updated_at\""},
	DeleteAt:    whereHelpernull_Time{field: "\"point_sales\".\"delete_at\""},
}

// PointSaleRels is where relationship names are stored.
var PointSaleRels = struct {
	CashRegisters   string
	ExpenseOthers   string
	IncomeOthers    string
	IncomeSales     string
	Members         string
	StockPointSales string
}{
	CashRegisters:   "CashRegisters",
	ExpenseOthers:   "ExpenseOthers",
	IncomeOthers:    "IncomeOthers",
	IncomeSales:     "IncomeSales",
	Members:         "Members",
	StockPointSales: "StockPointSales",
}

// pointSaleR is where relationships are stored.
type pointSaleR struct {
	CashRegisters   CashRegisterSlice   `boil:"CashRegisters" json:"CashRegisters" toml:"CashRegisters" yaml:"CashRegisters"`
	ExpenseOthers   ExpenseOtherSlice   `boil:"ExpenseOthers" json:"ExpenseOthers" toml:"ExpenseOthers" yaml:"ExpenseOthers"`
	IncomeOthers    IncomeOtherSlice    `boil:"IncomeOthers" json:"IncomeOthers" toml:"IncomeOthers" yaml:"IncomeOthers"`
	IncomeSales     IncomeSaleSlice     `boil:"IncomeSales" json:"IncomeSales" toml:"IncomeSales" yaml:"IncomeSales"`
	Members         MemberSlice         `boil:"Members" json:"Members" toml:"Members" yaml:"Members"`
	StockPointSales StockPointSaleSlice `boil:"StockPointSales" json:"StockPointSales" toml:"StockPointSales" yaml:"StockPointSales"`
}

// NewStruct creates a new relationship struct
func (*pointSaleR) NewStruct() *pointSaleR {
	return &pointSaleR{}
}

func (o *PointSale) GetCashRegisters() CashRegisterSlice {
	if o == nil {
		return nil
	}

	return o.R.GetCashRegisters()
}

func (r *pointSaleR) GetCashRegisters() CashRegisterSlice {
	if r == nil {
		return nil
	}

	return r.CashRegisters
}

func (o *PointSale) GetExpenseOthers() ExpenseOtherSlice {
	if o == nil {
		return nil
	}

	return o.R.GetExpenseOthers()
}

func (r *pointSaleR) GetExpenseOthers() ExpenseOtherSlice {
	if r == nil {
		return nil
	}

	return r.ExpenseOthers
}

func (o *PointSale) GetIncomeOthers() IncomeOtherSlice {
	if o == nil {
		return nil
	}

	return o.R.GetIncomeOthers()
}

func (r *pointSaleR) GetIncomeOthers() IncomeOtherSlice {
	if r == nil {
		return nil
	}

	return r.IncomeOthers
}

func (o *PointSale) GetIncomeSales() IncomeSaleSlice {
	if o == nil {
		return nil
	}

	return o.R.GetIncomeSales()
}

func (r *pointSaleR) GetIncomeSales() IncomeSaleSlice {
	if r == nil {
		return nil
	}

	return r.IncomeSales
}

func (o *PointSale) GetMembers() MemberSlice {
	if o == nil {
		return nil
	}

	return o.R.GetMembers()
}

func (r *pointSaleR) GetMembers() MemberSlice {
	if r == nil {
		return nil
	}

	return r.Members
}

func (o *PointSale) GetStockPointSales() StockPointSaleSlice {
	if o == nil {
		return nil
	}

	return o.R.GetStockPointSales()
}

func (r *pointSaleR) GetStockPointSales() StockPointSaleSlice {
	if r == nil {
		return nil
	}

	return r.StockPointSales
}

// pointSaleL is where Load methods for each relationship are stored.
type pointSaleL struct{}

var (
	pointSaleAllColumns            = []string{"id", "name", "description", "number", "is_deposit", "is_main", "created_at", "updated_at", "delete_at"}
	pointSaleColumnsWithoutDefault = []string{"name", "number"}
	pointSaleColumnsWithDefault    = []string{"id", "description", "is_deposit", "is_main", "created_at", "updated_at", "delete_at"}
	pointSalePrimaryKeyColumns     = []string{"id"}
	pointSaleGeneratedColumns      = []string{}
)

type (
	// PointSaleSlice is an alias for a slice of pointers to PointSale.
	// This should almost always be used instead of []PointSale.
	PointSaleSlice []*PointSale
	// PointSaleHook is the signature for custom PointSale hook methods
	PointSaleHook func(context.Context, boil.ContextExecutor, *PointSale) error

	pointSaleQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	pointSaleType                 = reflect.TypeOf(&PointSale{})
	pointSaleMapping              = queries.MakeStructMapping(pointSaleType)
	pointSalePrimaryKeyMapping, _ = queries.BindMapping(pointSaleType, pointSaleMapping, pointSalePrimaryKeyColumns)
	pointSaleInsertCacheMut       sync.RWMutex
	pointSaleInsertCache          = make(map[string]insertCache)
	pointSaleUpdateCacheMut       sync.RWMutex
	pointSaleUpdateCache          = make(map[string]updateCache)
	pointSaleUpsertCacheMut       sync.RWMutex
	pointSaleUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var pointSaleAfterSelectMu sync.Mutex
var pointSaleAfterSelectHooks []PointSaleHook

var pointSaleBeforeInsertMu sync.Mutex
var pointSaleBeforeInsertHooks []PointSaleHook
var pointSaleAfterInsertMu sync.Mutex
var pointSaleAfterInsertHooks []PointSaleHook

var pointSaleBeforeUpdateMu sync.Mutex
var pointSaleBeforeUpdateHooks []PointSaleHook
var pointSaleAfterUpdateMu sync.Mutex
var pointSaleAfterUpdateHooks []PointSaleHook

var pointSaleBeforeDeleteMu sync.Mutex
var pointSaleBeforeDeleteHooks []PointSaleHook
var pointSaleAfterDeleteMu sync.Mutex
var pointSaleAfterDeleteHooks []PointSaleHook

var pointSaleBeforeUpsertMu sync.Mutex
var pointSaleBeforeUpsertHooks []PointSaleHook
var pointSaleAfterUpsertMu sync.Mutex
var pointSaleAfterUpsertHooks []PointSaleHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PointSale) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range pointSaleAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PointSale) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range pointSaleBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PointSale) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range pointSaleAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PointSale) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range pointSaleBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PointSale) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range pointSaleAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PointSale) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range pointSaleBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PointSale) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range pointSaleAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PointSale) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range pointSaleBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PointSale) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range pointSaleAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPointSaleHook registers your hook function for all future operations.
func AddPointSaleHook(hookPoint boil.HookPoint, pointSaleHook PointSaleHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		pointSaleAfterSelectMu.Lock()
		pointSaleAfterSelectHooks = append(pointSaleAfterSelectHooks, pointSaleHook)
		pointSaleAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		pointSaleBeforeInsertMu.Lock()
		pointSaleBeforeInsertHooks = append(pointSaleBeforeInsertHooks, pointSaleHook)
		pointSaleBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		pointSaleAfterInsertMu.Lock()
		pointSaleAfterInsertHooks = append(pointSaleAfterInsertHooks, pointSaleHook)
		pointSaleAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		pointSaleBeforeUpdateMu.Lock()
		pointSaleBeforeUpdateHooks = append(pointSaleBeforeUpdateHooks, pointSaleHook)
		pointSaleBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		pointSaleAfterUpdateMu.Lock()
		pointSaleAfterUpdateHooks = append(pointSaleAfterUpdateHooks, pointSaleHook)
		pointSaleAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		pointSaleBeforeDeleteMu.Lock()
		pointSaleBeforeDeleteHooks = append(pointSaleBeforeDeleteHooks, pointSaleHook)
		pointSaleBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		pointSaleAfterDeleteMu.Lock()
		pointSaleAfterDeleteHooks = append(pointSaleAfterDeleteHooks, pointSaleHook)
		pointSaleAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		pointSaleBeforeUpsertMu.Lock()
		pointSaleBeforeUpsertHooks = append(pointSaleBeforeUpsertHooks, pointSaleHook)
		pointSaleBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		pointSaleAfterUpsertMu.Lock()
		pointSaleAfterUpsertHooks = append(pointSaleAfterUpsertHooks, pointSaleHook)
		pointSaleAfterUpsertMu.Unlock()
	}
}

// OneG returns a single pointSale record from the query using the global executor.
func (q pointSaleQuery) OneG(ctx context.Context) (*PointSale, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single pointSale record from the query.
func (q pointSaleQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PointSale, error) {
	o := &PointSale{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "tenant: failed to execute a one query for point_sales")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all PointSale records from the query using the global executor.
func (q pointSaleQuery) AllG(ctx context.Context) (PointSaleSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all PointSale records from the query.
func (q pointSaleQuery) All(ctx context.Context, exec boil.ContextExecutor) (PointSaleSlice, error) {
	var o []*PointSale

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "tenant: failed to assign all query results to PointSale slice")
	}

	if len(pointSaleAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all PointSale records in the query using the global executor
func (q pointSaleQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all PointSale records in the query.
func (q pointSaleQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to count point_sales rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q pointSaleQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q pointSaleQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "tenant: failed to check if point_sales exists")
	}

	return count > 0, nil
}

// CashRegisters retrieves all the cash_register's CashRegisters with an executor.
func (o *PointSale) CashRegisters(mods ...qm.QueryMod) cashRegisterQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"cash_registers\".\"point_sale_id\"=?", o.ID),
	)

	return CashRegisters(queryMods...)
}

// ExpenseOthers retrieves all the expense_other's ExpenseOthers with an executor.
func (o *PointSale) ExpenseOthers(mods ...qm.QueryMod) expenseOtherQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"expense_others\".\"point_sale_id\"=?", o.ID),
	)

	return ExpenseOthers(queryMods...)
}

// IncomeOthers retrieves all the income_other's IncomeOthers with an executor.
func (o *PointSale) IncomeOthers(mods ...qm.QueryMod) incomeOtherQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"income_others\".\"point_sale_id\"=?", o.ID),
	)

	return IncomeOthers(queryMods...)
}

// IncomeSales retrieves all the income_sale's IncomeSales with an executor.
func (o *PointSale) IncomeSales(mods ...qm.QueryMod) incomeSaleQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"income_sales\".\"point_sale_id\"=?", o.ID),
	)

	return IncomeSales(queryMods...)
}

// Members retrieves all the member's Members with an executor.
func (o *PointSale) Members(mods ...qm.QueryMod) memberQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.InnerJoin("\"member_point_sales\" on \"members\".\"id\" = \"member_point_sales\".\"member_id\""),
		qm.Where("\"member_point_sales\".\"point_sale_id\"=?", o.ID),
	)

	return Members(queryMods...)
}

// StockPointSales retrieves all the stock_point_sale's StockPointSales with an executor.
func (o *PointSale) StockPointSales(mods ...qm.QueryMod) stockPointSaleQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"stock_point_sales\".\"point_sale_id\"=?", o.ID),
	)

	return StockPointSales(queryMods...)
}

// LoadCashRegisters allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (pointSaleL) LoadCashRegisters(ctx context.Context, e boil.ContextExecutor, singular bool, maybePointSale any, mods queries.Applicator) error {
	var slice []*PointSale
	var object *PointSale

	if singular {
		var ok bool
		object, ok = maybePointSale.(*PointSale)
		if !ok {
			object = new(PointSale)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePointSale)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePointSale))
			}
		}
	} else {
		s, ok := maybePointSale.(*[]*PointSale)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePointSale)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePointSale))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &pointSaleR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &pointSaleR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`cash_registers`),
		qm.WhereIn(`cash_registers.point_sale_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load cash_registers")
	}

	var resultSlice []*CashRegister
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice cash_registers")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on cash_registers")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for cash_registers")
	}

	if len(cashRegisterAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.CashRegisters = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &cashRegisterR{}
			}
			foreign.R.PointSale = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.PointSaleID {
				local.R.CashRegisters = append(local.R.CashRegisters, foreign)
				if foreign.R == nil {
					foreign.R = &cashRegisterR{}
				}
				foreign.R.PointSale = local
				break
			}
		}
	}

	return nil
}

// LoadExpenseOthers allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (pointSaleL) LoadExpenseOthers(ctx context.Context, e boil.ContextExecutor, singular bool, maybePointSale any, mods queries.Applicator) error {
	var slice []*PointSale
	var object *PointSale

	if singular {
		var ok bool
		object, ok = maybePointSale.(*PointSale)
		if !ok {
			object = new(PointSale)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePointSale)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePointSale))
			}
		}
	} else {
		s, ok := maybePointSale.(*[]*PointSale)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePointSale)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePointSale))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &pointSaleR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &pointSaleR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`expense_others`),
		qm.WhereIn(`expense_others.point_sale_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load expense_others")
	}

	var resultSlice []*ExpenseOther
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice expense_others")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on expense_others")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for expense_others")
	}

	if len(expenseOtherAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ExpenseOthers = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &expenseOtherR{}
			}
			foreign.R.PointSale = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.PointSaleID) {
				local.R.ExpenseOthers = append(local.R.ExpenseOthers, foreign)
				if foreign.R == nil {
					foreign.R = &expenseOtherR{}
				}
				foreign.R.PointSale = local
				break
			}
		}
	}

	return nil
}

// LoadIncomeOthers allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (pointSaleL) LoadIncomeOthers(ctx context.Context, e boil.ContextExecutor, singular bool, maybePointSale any, mods queries.Applicator) error {
	var slice []*PointSale
	var object *PointSale

	if singular {
		var ok bool
		object, ok = maybePointSale.(*PointSale)
		if !ok {
			object = new(PointSale)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePointSale)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePointSale))
			}
		}
	} else {
		s, ok := maybePointSale.(*[]*PointSale)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePointSale)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePointSale))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &pointSaleR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &pointSaleR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`income_others`),
		qm.WhereIn(`income_others.point_sale_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load income_others")
	}

	var resultSlice []*IncomeOther
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice income_others")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on income_others")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for income_others")
	}

	if len(incomeOtherAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.IncomeOthers = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &incomeOtherR{}
			}
			foreign.R.PointSale = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.PointSaleID) {
				local.R.IncomeOthers = append(local.R.IncomeOthers, foreign)
				if foreign.R == nil {
					foreign.R = &incomeOtherR{}
				}
				foreign.R.PointSale = local
				break
			}
		}
	}

	return nil
}

// LoadIncomeSales allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (pointSaleL) LoadIncomeSales(ctx context.Context, e boil.ContextExecutor, singular bool, maybePointSale any, mods queries.Applicator) error {
	var slice []*PointSale
	var object *PointSale

	if singular {
		var ok bool
		object, ok = maybePointSale.(*PointSale)
		if !ok {
			object = new(PointSale)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePointSale)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePointSale))
			}
		}
	} else {
		s, ok := maybePointSale.(*[]*PointSale)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePointSale)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePointSale))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &pointSaleR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &pointSaleR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`income_sales`),
		qm.WhereIn(`income_sales.point_sale_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load income_sales")
	}

	var resultSlice []*IncomeSale
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice income_sales")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on income_sales")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for income_sales")
	}

	if len(incomeSaleAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.IncomeSales = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &incomeSaleR{}
			}
			foreign.R.PointSale = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.PointSaleID {
				local.R.IncomeSales = append(local.R.IncomeSales, foreign)
				if foreign.R == nil {
					foreign.R = &incomeSaleR{}
				}
				foreign.R.PointSale = local
				break
			}
		}
	}

	return nil
}

// LoadMembers allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (pointSaleL) LoadMembers(ctx context.Context, e boil.ContextExecutor, singular bool, maybePointSale any, mods queries.Applicator) error {
	var slice []*PointSale
	var object *PointSale

	if singular {
		var ok bool
		object, ok = maybePointSale.(*PointSale)
		if !ok {
			object = new(PointSale)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePointSale)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePointSale))
			}
		}
	} else {
		s, ok := maybePointSale.(*[]*PointSale)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePointSale)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePointSale))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &pointSaleR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &pointSaleR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.Select("\"members\".\"id\", \"members\".\"first_name\", \"members\".\"last_name\", \"members\".\"username\", \"members\".\"email\", \"members\".\"password\", \"members\".\"address\", \"members\".\"phone\", \"members\".\"is_admin\", \"members\".\"is_active\", \"members\".\"role_id\", \"members\".\"created_at\", \"members\".\"updated_at\", \"members\".\"deleted_at\", \"a\".\"point_sale_id\""),
		qm.From("\"members\""),
		qm.InnerJoin("\"member_point_sales\" as \"a\" on \"members\".\"id\" = \"a\".\"member_id\""),
		qm.WhereIn("\"a\".\"point_sale_id\" in ?", argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load members")
	}

	var resultSlice []*Member

	var localJoinCols []int64
	for results.Next() {
		one := new(Member)
		var localJoinCol int64

		err = results.Scan(&one.ID, &one.FirstName, &one.LastName, &one.Username, &one.Email, &one.Password, &one.Address, &one.Phone, &one.IsAdmin, &one.IsActive, &one.RoleID, &one.CreatedAt, &one.UpdatedAt, &one.DeletedAt, &localJoinCol)
		if err != nil {
			return errors.Wrap(err, "failed to scan eager loaded results for members")
		}
		if err = results.Err(); err != nil {
			return errors.Wrap(err, "failed to plebian-bind eager loaded slice members")
		}

		resultSlice = append(resultSlice, one)
		localJoinCols = append(localJoinCols, localJoinCol)
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on members")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for members")
	}

	if len(memberAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Members = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &memberR{}
			}
			foreign.R.PointSales = append(foreign.R.PointSales, object)
		}
		return nil
	}

	for i, foreign := range resultSlice {
		localJoinCol := localJoinCols[i]
		for _, local := range slice {
			if local.ID == localJoinCol {
				local.R.Members = append(local.R.Members, foreign)
				if foreign.R == nil {
					foreign.R = &memberR{}
				}
				foreign.R.PointSales = append(foreign.R.PointSales, local)
				break
			}
		}
	}

	return nil
}

// LoadStockPointSales allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (pointSaleL) LoadStockPointSales(ctx context.Context, e boil.ContextExecutor, singular bool, maybePointSale any, mods queries.Applicator) error {
	var slice []*PointSale
	var object *PointSale

	if singular {
		var ok bool
		object, ok = maybePointSale.(*PointSale)
		if !ok {
			object = new(PointSale)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePointSale)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePointSale))
			}
		}
	} else {
		s, ok := maybePointSale.(*[]*PointSale)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePointSale)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePointSale))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &pointSaleR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &pointSaleR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`stock_point_sales`),
		qm.WhereIn(`stock_point_sales.point_sale_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load stock_point_sales")
	}

	var resultSlice []*StockPointSale
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice stock_point_sales")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on stock_point_sales")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for stock_point_sales")
	}

	if len(stockPointSaleAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.StockPointSales = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &stockPointSaleR{}
			}
			foreign.R.PointSale = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.PointSaleID {
				local.R.StockPointSales = append(local.R.StockPointSales, foreign)
				if foreign.R == nil {
					foreign.R = &stockPointSaleR{}
				}
				foreign.R.PointSale = local
				break
			}
		}
	}

	return nil
}

// AddCashRegistersG adds the given related objects to the existing relationships
// of the point_sale, optionally inserting them as new records.
// Appends related to o.R.CashRegisters.
// Sets related.R.PointSale appropriately.
// Uses the global database handle.
func (o *PointSale) AddCashRegistersG(ctx context.Context, insert bool, related ...*CashRegister) error {
	return o.AddCashRegisters(ctx, boil.GetContextDB(), insert, related...)
}

// AddCashRegisters adds the given related objects to the existing relationships
// of the point_sale, optionally inserting them as new records.
// Appends related to o.R.CashRegisters.
// Sets related.R.PointSale appropriately.
func (o *PointSale) AddCashRegisters(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*CashRegister) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.PointSaleID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"cash_registers\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"point_sale_id"}),
				strmangle.WhereClause("\"", "\"", 2, cashRegisterPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.PointSaleID = o.ID
		}
	}

	if o.R == nil {
		o.R = &pointSaleR{
			CashRegisters: related,
		}
	} else {
		o.R.CashRegisters = append(o.R.CashRegisters, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &cashRegisterR{
				PointSale: o,
			}
		} else {
			rel.R.PointSale = o
		}
	}
	return nil
}

// AddExpenseOthersG adds the given related objects to the existing relationships
// of the point_sale, optionally inserting them as new records.
// Appends related to o.R.ExpenseOthers.
// Sets related.R.PointSale appropriately.
// Uses the global database handle.
func (o *PointSale) AddExpenseOthersG(ctx context.Context, insert bool, related ...*ExpenseOther) error {
	return o.AddExpenseOthers(ctx, boil.GetContextDB(), insert, related...)
}

// AddExpenseOthers adds the given related objects to the existing relationships
// of the point_sale, optionally inserting them as new records.
// Appends related to o.R.ExpenseOthers.
// Sets related.R.PointSale appropriately.
func (o *PointSale) AddExpenseOthers(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ExpenseOther) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.PointSaleID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"expense_others\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"point_sale_id"}),
				strmangle.WhereClause("\"", "\"", 2, expenseOtherPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.PointSaleID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &pointSaleR{
			ExpenseOthers: related,
		}
	} else {
		o.R.ExpenseOthers = append(o.R.ExpenseOthers, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &expenseOtherR{
				PointSale: o,
			}
		} else {
			rel.R.PointSale = o
		}
	}
	return nil
}

// SetExpenseOthersG removes all previously related items of the
// point_sale replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.PointSale's ExpenseOthers accordingly.
// Replaces o.R.ExpenseOthers with related.
// Sets related.R.PointSale's ExpenseOthers accordingly.
// Uses the global database handle.
func (o *PointSale) SetExpenseOthersG(ctx context.Context, insert bool, related ...*ExpenseOther) error {
	return o.SetExpenseOthers(ctx, boil.GetContextDB(), insert, related...)
}

// SetExpenseOthers removes all previously related items of the
// point_sale replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.PointSale's ExpenseOthers accordingly.
// Replaces o.R.ExpenseOthers with related.
// Sets related.R.PointSale's ExpenseOthers accordingly.
func (o *PointSale) SetExpenseOthers(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ExpenseOther) error {
	query := "update \"expense_others\" set \"point_sale_id\" = null where \"point_sale_id\" = $1"
	values := []any{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.ExpenseOthers {
			queries.SetScanner(&rel.PointSaleID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.PointSale = nil
		}
		o.R.ExpenseOthers = nil
	}

	return o.AddExpenseOthers(ctx, exec, insert, related...)
}

// RemoveExpenseOthersG relationships from objects passed in.
// Removes related items from R.ExpenseOthers (uses pointer comparison, removal does not keep order)
// Sets related.R.PointSale.
// Uses the global database handle.
func (o *PointSale) RemoveExpenseOthersG(ctx context.Context, related ...*ExpenseOther) error {
	return o.RemoveExpenseOthers(ctx, boil.GetContextDB(), related...)
}

// RemoveExpenseOthers relationships from objects passed in.
// Removes related items from R.ExpenseOthers (uses pointer comparison, removal does not keep order)
// Sets related.R.PointSale.
func (o *PointSale) RemoveExpenseOthers(ctx context.Context, exec boil.ContextExecutor, related ...*ExpenseOther) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.PointSaleID, nil)
		if rel.R != nil {
			rel.R.PointSale = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("point_sale_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.ExpenseOthers {
			if rel != ri {
				continue
			}

			ln := len(o.R.ExpenseOthers)
			if ln > 1 && i < ln-1 {
				o.R.ExpenseOthers[i] = o.R.ExpenseOthers[ln-1]
			}
			o.R.ExpenseOthers = o.R.ExpenseOthers[:ln-1]
			break
		}
	}

	return nil
}

// AddIncomeOthersG adds the given related objects to the existing relationships
// of the point_sale, optionally inserting them as new records.
// Appends related to o.R.IncomeOthers.
// Sets related.R.PointSale appropriately.
// Uses the global database handle.
func (o *PointSale) AddIncomeOthersG(ctx context.Context, insert bool, related ...*IncomeOther) error {
	return o.AddIncomeOthers(ctx, boil.GetContextDB(), insert, related...)
}

// AddIncomeOthers adds the given related objects to the existing relationships
// of the point_sale, optionally inserting them as new records.
// Appends related to o.R.IncomeOthers.
// Sets related.R.PointSale appropriately.
func (o *PointSale) AddIncomeOthers(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*IncomeOther) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.PointSaleID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"income_others\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"point_sale_id"}),
				strmangle.WhereClause("\"", "\"", 2, incomeOtherPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.PointSaleID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &pointSaleR{
			IncomeOthers: related,
		}
	} else {
		o.R.IncomeOthers = append(o.R.IncomeOthers, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &incomeOtherR{
				PointSale: o,
			}
		} else {
			rel.R.PointSale = o
		}
	}
	return nil
}

// SetIncomeOthersG removes all previously related items of the
// point_sale replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.PointSale's IncomeOthers accordingly.
// Replaces o.R.IncomeOthers with related.
// Sets related.R.PointSale's IncomeOthers accordingly.
// Uses the global database handle.
func (o *PointSale) SetIncomeOthersG(ctx context.Context, insert bool, related ...*IncomeOther) error {
	return o.SetIncomeOthers(ctx, boil.GetContextDB(), insert, related...)
}

// SetIncomeOthers removes all previously related items of the
// point_sale replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.PointSale's IncomeOthers accordingly.
// Replaces o.R.IncomeOthers with related.
// Sets related.R.PointSale's IncomeOthers accordingly.
func (o *PointSale) SetIncomeOthers(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*IncomeOther) error {
	query := "update \"income_others\" set \"point_sale_id\" = null where \"point_sale_id\" = $1"
	values := []any{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.IncomeOthers {
			queries.SetScanner(&rel.PointSaleID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.PointSale = nil
		}
		o.R.IncomeOthers = nil
	}

	return o.AddIncomeOthers(ctx, exec, insert, related...)
}

// RemoveIncomeOthersG relationships from objects passed in.
// Removes related items from R.IncomeOthers (uses pointer comparison, removal does not keep order)
// Sets related.R.PointSale.
// Uses the global database handle.
func (o *PointSale) RemoveIncomeOthersG(ctx context.Context, related ...*IncomeOther) error {
	return o.RemoveIncomeOthers(ctx, boil.GetContextDB(), related...)
}

// RemoveIncomeOthers relationships from objects passed in.
// Removes related items from R.IncomeOthers (uses pointer comparison, removal does not keep order)
// Sets related.R.PointSale.
func (o *PointSale) RemoveIncomeOthers(ctx context.Context, exec boil.ContextExecutor, related ...*IncomeOther) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.PointSaleID, nil)
		if rel.R != nil {
			rel.R.PointSale = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("point_sale_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.IncomeOthers {
			if rel != ri {
				continue
			}

			ln := len(o.R.IncomeOthers)
			if ln > 1 && i < ln-1 {
				o.R.IncomeOthers[i] = o.R.IncomeOthers[ln-1]
			}
			o.R.IncomeOthers = o.R.IncomeOthers[:ln-1]
			break
		}
	}

	return nil
}

// AddIncomeSalesG adds the given related objects to the existing relationships
// of the point_sale, optionally inserting them as new records.
// Appends related to o.R.IncomeSales.
// Sets related.R.PointSale appropriately.
// Uses the global database handle.
func (o *PointSale) AddIncomeSalesG(ctx context.Context, insert bool, related ...*IncomeSale) error {
	return o.AddIncomeSales(ctx, boil.GetContextDB(), insert, related...)
}

// AddIncomeSales adds the given related objects to the existing relationships
// of the point_sale, optionally inserting them as new records.
// Appends related to o.R.IncomeSales.
// Sets related.R.PointSale appropriately.
func (o *PointSale) AddIncomeSales(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*IncomeSale) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.PointSaleID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"income_sales\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"point_sale_id"}),
				strmangle.WhereClause("\"", "\"", 2, incomeSalePrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.PointSaleID = o.ID
		}
	}

	if o.R == nil {
		o.R = &pointSaleR{
			IncomeSales: related,
		}
	} else {
		o.R.IncomeSales = append(o.R.IncomeSales, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &incomeSaleR{
				PointSale: o,
			}
		} else {
			rel.R.PointSale = o
		}
	}
	return nil
}

// AddMembersG adds the given related objects to the existing relationships
// of the point_sale, optionally inserting them as new records.
// Appends related to o.R.Members.
// Sets related.R.PointSales appropriately.
// Uses the global database handle.
func (o *PointSale) AddMembersG(ctx context.Context, insert bool, related ...*Member) error {
	return o.AddMembers(ctx, boil.GetContextDB(), insert, related...)
}

// AddMembers adds the given related objects to the existing relationships
// of the point_sale, optionally inserting them as new records.
// Appends related to o.R.Members.
// Sets related.R.PointSales appropriately.
func (o *PointSale) AddMembers(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Member) error {
	var err error
	for _, rel := range related {
		if insert {
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		}
	}

	for _, rel := range related {
		query := "insert into \"member_point_sales\" (\"point_sale_id\", \"member_id\") values ($1, $2)"
		values := []any{o.ID, rel.ID}

		if boil.IsDebug(ctx) {
			writer := boil.DebugWriterFrom(ctx)
			fmt.Fprintln(writer, query)
			fmt.Fprintln(writer, values)
		}
		_, err = exec.ExecContext(ctx, query, values...)
		if err != nil {
			return errors.Wrap(err, "failed to insert into join table")
		}
	}
	if o.R == nil {
		o.R = &pointSaleR{
			Members: related,
		}
	} else {
		o.R.Members = append(o.R.Members, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &memberR{
				PointSales: PointSaleSlice{o},
			}
		} else {
			rel.R.PointSales = append(rel.R.PointSales, o)
		}
	}
	return nil
}

// SetMembersG removes all previously related items of the
// point_sale replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.PointSales's Members accordingly.
// Replaces o.R.Members with related.
// Sets related.R.PointSales's Members accordingly.
// Uses the global database handle.
func (o *PointSale) SetMembersG(ctx context.Context, insert bool, related ...*Member) error {
	return o.SetMembers(ctx, boil.GetContextDB(), insert, related...)
}

// SetMembers removes all previously related items of the
// point_sale replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.PointSales's Members accordingly.
// Replaces o.R.Members with related.
// Sets related.R.PointSales's Members accordingly.
func (o *PointSale) SetMembers(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Member) error {
	query := "delete from \"member_point_sales\" where \"point_sale_id\" = $1"
	values := []any{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	removeMembersFromPointSalesSlice(o, related)
	if o.R != nil {
		o.R.Members = nil
	}

	return o.AddMembers(ctx, exec, insert, related...)
}

// RemoveMembersG relationships from objects passed in.
// Removes related items from R.Members (uses pointer comparison, removal does not keep order)
// Sets related.R.PointSales.
// Uses the global database handle.
func (o *PointSale) RemoveMembersG(ctx context.Context, related ...*Member) error {
	return o.RemoveMembers(ctx, boil.GetContextDB(), related...)
}

// RemoveMembers relationships from objects passed in.
// Removes related items from R.Members (uses pointer comparison, removal does not keep order)
// Sets related.R.PointSales.
func (o *PointSale) RemoveMembers(ctx context.Context, exec boil.ContextExecutor, related ...*Member) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	query := fmt.Sprintf(
		"delete from \"member_point_sales\" where \"point_sale_id\" = $1 and \"member_id\" in (%s)",
		strmangle.Placeholders(dialect.UseIndexPlaceholders, len(related), 2, 1),
	)
	values := []any{o.ID}
	for _, rel := range related {
		values = append(values, rel.ID)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}
	removeMembersFromPointSalesSlice(o, related)
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.Members {
			if rel != ri {
				continue
			}

			ln := len(o.R.Members)
			if ln > 1 && i < ln-1 {
				o.R.Members[i] = o.R.Members[ln-1]
			}
			o.R.Members = o.R.Members[:ln-1]
			break
		}
	}

	return nil
}

func removeMembersFromPointSalesSlice(o *PointSale, related []*Member) {
	for _, rel := range related {
		if rel.R == nil {
			continue
		}
		for i, ri := range rel.R.PointSales {
			if o.ID != ri.ID {
				continue
			}

			ln := len(rel.R.PointSales)
			if ln > 1 && i < ln-1 {
				rel.R.PointSales[i] = rel.R.PointSales[ln-1]
			}
			rel.R.PointSales = rel.R.PointSales[:ln-1]
			break
		}
	}
}

// AddStockPointSalesG adds the given related objects to the existing relationships
// of the point_sale, optionally inserting them as new records.
// Appends related to o.R.StockPointSales.
// Sets related.R.PointSale appropriately.
// Uses the global database handle.
func (o *PointSale) AddStockPointSalesG(ctx context.Context, insert bool, related ...*StockPointSale) error {
	return o.AddStockPointSales(ctx, boil.GetContextDB(), insert, related...)
}

// AddStockPointSales adds the given related objects to the existing relationships
// of the point_sale, optionally inserting them as new records.
// Appends related to o.R.StockPointSales.
// Sets related.R.PointSale appropriately.
func (o *PointSale) AddStockPointSales(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*StockPointSale) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.PointSaleID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"stock_point_sales\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"point_sale_id"}),
				strmangle.WhereClause("\"", "\"", 2, stockPointSalePrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.PointSaleID = o.ID
		}
	}

	if o.R == nil {
		o.R = &pointSaleR{
			StockPointSales: related,
		}
	} else {
		o.R.StockPointSales = append(o.R.StockPointSales, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &stockPointSaleR{
				PointSale: o,
			}
		} else {
			rel.R.PointSale = o
		}
	}
	return nil
}

// PointSales retrieves all the records using an executor.
func PointSales(mods ...qm.QueryMod) pointSaleQuery {
	mods = append(mods, qm.From("\"point_sales\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"point_sales\".*"})
	}

	return pointSaleQuery{q}
}

// FindPointSaleG retrieves a single record by ID.
func FindPointSaleG(ctx context.Context, iD int64, selectCols ...string) (*PointSale, error) {
	return FindPointSale(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindPointSale retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPointSale(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*PointSale, error) {
	pointSaleObj := &PointSale{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"point_sales\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, pointSaleObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "tenant: unable to select from point_sales")
	}

	if err = pointSaleObj.doAfterSelectHooks(ctx, exec); err != nil {
		return pointSaleObj, err
	}

	return pointSaleObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *PointSale) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PointSale) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("tenant: no point_sales provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(pointSaleColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	pointSaleInsertCacheMut.RLock()
	cache, cached := pointSaleInsertCache[key]
	pointSaleInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			pointSaleAllColumns,
			pointSaleColumnsWithDefault,
			pointSaleColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(pointSaleType, pointSaleMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(pointSaleType, pointSaleMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"point_sales\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"point_sales\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "tenant: unable to insert into point_sales")
	}

	if !cached {
		pointSaleInsertCacheMut.Lock()
		pointSaleInsertCache[key] = cache
		pointSaleInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single PointSale record using the global executor.
// See Update for more documentation.
func (o *PointSale) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the PointSale.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PointSale) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	pointSaleUpdateCacheMut.RLock()
	cache, cached := pointSaleUpdateCache[key]
	pointSaleUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			pointSaleAllColumns,
			pointSalePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("tenant: unable to update point_sales, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"point_sales\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, pointSalePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(pointSaleType, pointSaleMapping, append(wl, pointSalePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to update point_sales row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to get rows affected by update for point_sales")
	}

	if !cached {
		pointSaleUpdateCacheMut.Lock()
		pointSaleUpdateCache[key] = cache
		pointSaleUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q pointSaleQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q pointSaleQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to update all for point_sales")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to retrieve rows affected for point_sales")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o PointSaleSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PointSaleSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("tenant: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), pointSalePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"point_sales\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, pointSalePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to update all in pointSale slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to retrieve rows affected all in update all pointSale")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *PointSale) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PointSale) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("tenant: no point_sales provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(pointSaleColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	pointSaleUpsertCacheMut.RLock()
	cache, cached := pointSaleUpsertCache[key]
	pointSaleUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			pointSaleAllColumns,
			pointSaleColumnsWithDefault,
			pointSaleColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			pointSaleAllColumns,
			pointSalePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("tenant: unable to upsert point_sales, could not build update column list")
		}

		ret := strmangle.SetComplement(pointSaleAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(pointSalePrimaryKeyColumns) == 0 {
				return errors.New("tenant: unable to upsert point_sales, could not build conflict column list")
			}

			conflict = make([]string, len(pointSalePrimaryKeyColumns))
			copy(conflict, pointSalePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"point_sales\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(pointSaleType, pointSaleMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(pointSaleType, pointSaleMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "tenant: unable to upsert point_sales")
	}

	if !cached {
		pointSaleUpsertCacheMut.Lock()
		pointSaleUpsertCache[key] = cache
		pointSaleUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single PointSale record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *PointSale) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single PointSale record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PointSale) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("tenant: no PointSale provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), pointSalePrimaryKeyMapping)
	sql := "DELETE FROM \"point_sales\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to delete from point_sales")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to get rows affected by delete for point_sales")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q pointSaleQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q pointSaleQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("tenant: no pointSaleQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to delete all from point_sales")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to get rows affected by deleteall for point_sales")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o PointSaleSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PointSaleSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(pointSaleBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), pointSalePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"point_sales\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, pointSalePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to delete all from pointSale slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to get rows affected by deleteall for point_sales")
	}

	if len(pointSaleAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *PointSale) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("tenant: no PointSale provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PointSale) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPointSale(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PointSaleSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("tenant: empty PointSaleSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PointSaleSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PointSaleSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), pointSalePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"point_sales\".* FROM \"point_sales\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, pointSalePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "tenant: unable to reload all in PointSaleSlice")
	}

	*o = slice

	return nil
}

// PointSaleExistsG checks if the PointSale row exists.
func PointSaleExistsG(ctx context.Context, iD int64) (bool, error) {
	return PointSaleExists(ctx, boil.GetContextDB(), iD)
}

// PointSaleExists checks if the PointSale row exists.
func PointSaleExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"point_sales\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "tenant: unable to check if point_sales exists")
	}

	return exists, nil
}

// Exists checks if the PointSale row exists.
func (o *PointSale) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PointSaleExists(ctx, exec, o.ID)
}
