// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package tenant

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// StockPointSale is an object representing the database table.
type StockPointSale struct {
	ID          int64         `boil:"id" json:"id" toml:"id" yaml:"id"`
	ProductID   int64         `boil:"product_id" json:"product_id" toml:"product_id" yaml:"product_id"`
	PointSaleID int64         `boil:"point_sale_id" json:"point_sale_id" toml:"point_sale_id" yaml:"point_sale_id"`
	Stock       types.Decimal `boil:"stock" json:"stock" toml:"stock" yaml:"stock"`
	CreatedAt   time.Time     `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt   time.Time     `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *stockPointSaleR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L stockPointSaleL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var StockPointSaleColumns = struct {
	ID          string
	ProductID   string
	PointSaleID string
	Stock       string
	CreatedAt   string
	UpdatedAt   string
}{
	ID:          "id",
	ProductID:   "product_id",
	PointSaleID: "point_sale_id",
	Stock:       "stock",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

var StockPointSaleTableColumns = struct {
	ID          string
	ProductID   string
	PointSaleID string
	Stock       string
	CreatedAt   string
	UpdatedAt   string
}{
	ID:          "stock_point_sales.id",
	ProductID:   "stock_point_sales.product_id",
	PointSaleID: "stock_point_sales.point_sale_id",
	Stock:       "stock_point_sales.stock",
	CreatedAt:   "stock_point_sales.created_at",
	UpdatedAt:   "stock_point_sales.updated_at",
}

// Generated where

var StockPointSaleWhere = struct {
	ID          whereHelperint64
	ProductID   whereHelperint64
	PointSaleID whereHelperint64
	Stock       whereHelpertypes_Decimal
	CreatedAt   whereHelpertime_Time
	UpdatedAt   whereHelpertime_Time
}{
	ID:          whereHelperint64{field: "\"stock_point_sales\".\"id\""},
	ProductID:   whereHelperint64{field: "\"stock_point_sales\".\"product_id\""},
	PointSaleID: whereHelperint64{field: "\"stock_point_sales\".\"point_sale_id\""},
	Stock:       whereHelpertypes_Decimal{field: "\"stock_point_sales\".\"stock\""},
	CreatedAt:   whereHelpertime_Time{field: "\"stock_point_sales\".\"created_at\""},
	UpdatedAt:   whereHelpertime_Time{field: "\"stock_point_sales\".\"updated_at\""},
}

// StockPointSaleRels is where relationship names are stored.
var StockPointSaleRels = struct {
	Product   string
	PointSale string
}{
	Product:   "Product",
	PointSale: "PointSale",
}

// stockPointSaleR is where relationships are stored.
type stockPointSaleR struct {
	Product   *Product   `boil:"Product" json:"Product" toml:"Product" yaml:"Product"`
	PointSale *PointSale `boil:"PointSale" json:"PointSale" toml:"PointSale" yaml:"PointSale"`
}

// NewStruct creates a new relationship struct
func (*stockPointSaleR) NewStruct() *stockPointSaleR {
	return &stockPointSaleR{}
}

func (o *StockPointSale) GetProduct() *Product {
	if o == nil {
		return nil
	}

	return o.R.GetProduct()
}

func (r *stockPointSaleR) GetProduct() *Product {
	if r == nil {
		return nil
	}

	return r.Product
}

func (o *StockPointSale) GetPointSale() *PointSale {
	if o == nil {
		return nil
	}

	return o.R.GetPointSale()
}

func (r *stockPointSaleR) GetPointSale() *PointSale {
	if r == nil {
		return nil
	}

	return r.PointSale
}

// stockPointSaleL is where Load methods for each relationship are stored.
type stockPointSaleL struct{}

var (
	stockPointSaleAllColumns            = []string{"id", "product_id", "point_sale_id", "stock", "created_at", "updated_at"}
	stockPointSaleColumnsWithoutDefault = []string{"product_id", "point_sale_id"}
	stockPointSaleColumnsWithDefault    = []string{"id", "stock", "created_at", "updated_at"}
	stockPointSalePrimaryKeyColumns     = []string{"id"}
	stockPointSaleGeneratedColumns      = []string{}
)

type (
	// StockPointSaleSlice is an alias for a slice of pointers to StockPointSale.
	// This should almost always be used instead of []StockPointSale.
	StockPointSaleSlice []*StockPointSale
	// StockPointSaleHook is the signature for custom StockPointSale hook methods
	StockPointSaleHook func(context.Context, boil.ContextExecutor, *StockPointSale) error

	stockPointSaleQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	stockPointSaleType                 = reflect.TypeOf(&StockPointSale{})
	stockPointSaleMapping              = queries.MakeStructMapping(stockPointSaleType)
	stockPointSalePrimaryKeyMapping, _ = queries.BindMapping(stockPointSaleType, stockPointSaleMapping, stockPointSalePrimaryKeyColumns)
	stockPointSaleInsertCacheMut       sync.RWMutex
	stockPointSaleInsertCache          = make(map[string]insertCache)
	stockPointSaleUpdateCacheMut       sync.RWMutex
	stockPointSaleUpdateCache          = make(map[string]updateCache)
	stockPointSaleUpsertCacheMut       sync.RWMutex
	stockPointSaleUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var stockPointSaleAfterSelectMu sync.Mutex
var stockPointSaleAfterSelectHooks []StockPointSaleHook

var stockPointSaleBeforeInsertMu sync.Mutex
var stockPointSaleBeforeInsertHooks []StockPointSaleHook
var stockPointSaleAfterInsertMu sync.Mutex
var stockPointSaleAfterInsertHooks []StockPointSaleHook

var stockPointSaleBeforeUpdateMu sync.Mutex
var stockPointSaleBeforeUpdateHooks []StockPointSaleHook
var stockPointSaleAfterUpdateMu sync.Mutex
var stockPointSaleAfterUpdateHooks []StockPointSaleHook

var stockPointSaleBeforeDeleteMu sync.Mutex
var stockPointSaleBeforeDeleteHooks []StockPointSaleHook
var stockPointSaleAfterDeleteMu sync.Mutex
var stockPointSaleAfterDeleteHooks []StockPointSaleHook

var stockPointSaleBeforeUpsertMu sync.Mutex
var stockPointSaleBeforeUpsertHooks []StockPointSaleHook
var stockPointSaleAfterUpsertMu sync.Mutex
var stockPointSaleAfterUpsertHooks []StockPointSaleHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *StockPointSale) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stockPointSaleAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *StockPointSale) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stockPointSaleBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *StockPointSale) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stockPointSaleAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *StockPointSale) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stockPointSaleBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *StockPointSale) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stockPointSaleAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *StockPointSale) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stockPointSaleBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *StockPointSale) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stockPointSaleAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *StockPointSale) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stockPointSaleBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *StockPointSale) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stockPointSaleAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddStockPointSaleHook registers your hook function for all future operations.
func AddStockPointSaleHook(hookPoint boil.HookPoint, stockPointSaleHook StockPointSaleHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		stockPointSaleAfterSelectMu.Lock()
		stockPointSaleAfterSelectHooks = append(stockPointSaleAfterSelectHooks, stockPointSaleHook)
		stockPointSaleAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		stockPointSaleBeforeInsertMu.Lock()
		stockPointSaleBeforeInsertHooks = append(stockPointSaleBeforeInsertHooks, stockPointSaleHook)
		stockPointSaleBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		stockPointSaleAfterInsertMu.Lock()
		stockPointSaleAfterInsertHooks = append(stockPointSaleAfterInsertHooks, stockPointSaleHook)
		stockPointSaleAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		stockPointSaleBeforeUpdateMu.Lock()
		stockPointSaleBeforeUpdateHooks = append(stockPointSaleBeforeUpdateHooks, stockPointSaleHook)
		stockPointSaleBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		stockPointSaleAfterUpdateMu.Lock()
		stockPointSaleAfterUpdateHooks = append(stockPointSaleAfterUpdateHooks, stockPointSaleHook)
		stockPointSaleAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		stockPointSaleBeforeDeleteMu.Lock()
		stockPointSaleBeforeDeleteHooks = append(stockPointSaleBeforeDeleteHooks, stockPointSaleHook)
		stockPointSaleBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		stockPointSaleAfterDeleteMu.Lock()
		stockPointSaleAfterDeleteHooks = append(stockPointSaleAfterDeleteHooks, stockPointSaleHook)
		stockPointSaleAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		stockPointSaleBeforeUpsertMu.Lock()
		stockPointSaleBeforeUpsertHooks = append(stockPointSaleBeforeUpsertHooks, stockPointSaleHook)
		stockPointSaleBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		stockPointSaleAfterUpsertMu.Lock()
		stockPointSaleAfterUpsertHooks = append(stockPointSaleAfterUpsertHooks, stockPointSaleHook)
		stockPointSaleAfterUpsertMu.Unlock()
	}
}

// OneG returns a single stockPointSale record from the query using the global executor.
func (q stockPointSaleQuery) OneG(ctx context.Context) (*StockPointSale, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single stockPointSale record from the query.
func (q stockPointSaleQuery) One(ctx context.Context, exec boil.ContextExecutor) (*StockPointSale, error) {
	o := &StockPointSale{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "tenant: failed to execute a one query for stock_point_sales")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all StockPointSale records from the query using the global executor.
func (q stockPointSaleQuery) AllG(ctx context.Context) (StockPointSaleSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all StockPointSale records from the query.
func (q stockPointSaleQuery) All(ctx context.Context, exec boil.ContextExecutor) (StockPointSaleSlice, error) {
	var o []*StockPointSale

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "tenant: failed to assign all query results to StockPointSale slice")
	}

	if len(stockPointSaleAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all StockPointSale records in the query using the global executor
func (q stockPointSaleQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all StockPointSale records in the query.
func (q stockPointSaleQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to count stock_point_sales rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q stockPointSaleQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q stockPointSaleQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "tenant: failed to check if stock_point_sales exists")
	}

	return count > 0, nil
}

// Product pointed to by the foreign key.
func (o *StockPointSale) Product(mods ...qm.QueryMod) productQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ProductID),
	}

	queryMods = append(queryMods, mods...)

	return Products(queryMods...)
}

// PointSale pointed to by the foreign key.
func (o *StockPointSale) PointSale(mods ...qm.QueryMod) pointSaleQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.PointSaleID),
	}

	queryMods = append(queryMods, mods...)

	return PointSales(queryMods...)
}

// LoadProduct allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (stockPointSaleL) LoadProduct(ctx context.Context, e boil.ContextExecutor, singular bool, maybeStockPointSale any, mods queries.Applicator) error {
	var slice []*StockPointSale
	var object *StockPointSale

	if singular {
		var ok bool
		object, ok = maybeStockPointSale.(*StockPointSale)
		if !ok {
			object = new(StockPointSale)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeStockPointSale)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeStockPointSale))
			}
		}
	} else {
		s, ok := maybeStockPointSale.(*[]*StockPointSale)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeStockPointSale)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeStockPointSale))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &stockPointSaleR{}
		}
		args[object.ProductID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &stockPointSaleR{}
			}

			args[obj.ProductID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`products`),
		qm.WhereIn(`products.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Product")
	}

	var resultSlice []*Product
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Product")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for products")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for products")
	}

	if len(productAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Product = foreign
		if foreign.R == nil {
			foreign.R = &productR{}
		}
		foreign.R.StockPointSales = append(foreign.R.StockPointSales, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ProductID == foreign.ID {
				local.R.Product = foreign
				if foreign.R == nil {
					foreign.R = &productR{}
				}
				foreign.R.StockPointSales = append(foreign.R.StockPointSales, local)
				break
			}
		}
	}

	return nil
}

// LoadPointSale allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (stockPointSaleL) LoadPointSale(ctx context.Context, e boil.ContextExecutor, singular bool, maybeStockPointSale any, mods queries.Applicator) error {
	var slice []*StockPointSale
	var object *StockPointSale

	if singular {
		var ok bool
		object, ok = maybeStockPointSale.(*StockPointSale)
		if !ok {
			object = new(StockPointSale)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeStockPointSale)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeStockPointSale))
			}
		}
	} else {
		s, ok := maybeStockPointSale.(*[]*StockPointSale)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeStockPointSale)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeStockPointSale))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &stockPointSaleR{}
		}
		args[object.PointSaleID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &stockPointSaleR{}
			}

			args[obj.PointSaleID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`point_sales`),
		qm.WhereIn(`point_sales.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load PointSale")
	}

	var resultSlice []*PointSale
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice PointSale")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for point_sales")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for point_sales")
	}

	if len(pointSaleAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.PointSale = foreign
		if foreign.R == nil {
			foreign.R = &pointSaleR{}
		}
		foreign.R.StockPointSales = append(foreign.R.StockPointSales, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.PointSaleID == foreign.ID {
				local.R.PointSale = foreign
				if foreign.R == nil {
					foreign.R = &pointSaleR{}
				}
				foreign.R.StockPointSales = append(foreign.R.StockPointSales, local)
				break
			}
		}
	}

	return nil
}

// SetProductG of the stockPointSale to the related item.
// Sets o.R.Product to related.
// Adds o to related.R.StockPointSales.
// Uses the global database handle.
func (o *StockPointSale) SetProductG(ctx context.Context, insert bool, related *Product) error {
	return o.SetProduct(ctx, boil.GetContextDB(), insert, related)
}

// SetProduct of the stockPointSale to the related item.
// Sets o.R.Product to related.
// Adds o to related.R.StockPointSales.
func (o *StockPointSale) SetProduct(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Product) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"stock_point_sales\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"product_id"}),
		strmangle.WhereClause("\"", "\"", 2, stockPointSalePrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ProductID = related.ID
	if o.R == nil {
		o.R = &stockPointSaleR{
			Product: related,
		}
	} else {
		o.R.Product = related
	}

	if related.R == nil {
		related.R = &productR{
			StockPointSales: StockPointSaleSlice{o},
		}
	} else {
		related.R.StockPointSales = append(related.R.StockPointSales, o)
	}

	return nil
}

// SetPointSaleG of the stockPointSale to the related item.
// Sets o.R.PointSale to related.
// Adds o to related.R.StockPointSales.
// Uses the global database handle.
func (o *StockPointSale) SetPointSaleG(ctx context.Context, insert bool, related *PointSale) error {
	return o.SetPointSale(ctx, boil.GetContextDB(), insert, related)
}

// SetPointSale of the stockPointSale to the related item.
// Sets o.R.PointSale to related.
// Adds o to related.R.StockPointSales.
func (o *StockPointSale) SetPointSale(ctx context.Context, exec boil.ContextExecutor, insert bool, related *PointSale) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"stock_point_sales\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"point_sale_id"}),
		strmangle.WhereClause("\"", "\"", 2, stockPointSalePrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.PointSaleID = related.ID
	if o.R == nil {
		o.R = &stockPointSaleR{
			PointSale: related,
		}
	} else {
		o.R.PointSale = related
	}

	if related.R == nil {
		related.R = &pointSaleR{
			StockPointSales: StockPointSaleSlice{o},
		}
	} else {
		related.R.StockPointSales = append(related.R.StockPointSales, o)
	}

	return nil
}

// StockPointSales retrieves all the records using an executor.
func StockPointSales(mods ...qm.QueryMod) stockPointSaleQuery {
	mods = append(mods, qm.From("\"stock_point_sales\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"stock_point_sales\".*"})
	}

	return stockPointSaleQuery{q}
}

// FindStockPointSaleG retrieves a single record by ID.
func FindStockPointSaleG(ctx context.Context, iD int64, selectCols ...string) (*StockPointSale, error) {
	return FindStockPointSale(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindStockPointSale retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindStockPointSale(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*StockPointSale, error) {
	stockPointSaleObj := &StockPointSale{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"stock_point_sales\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, stockPointSaleObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "tenant: unable to select from stock_point_sales")
	}

	if err = stockPointSaleObj.doAfterSelectHooks(ctx, exec); err != nil {
		return stockPointSaleObj, err
	}

	return stockPointSaleObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *StockPointSale) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *StockPointSale) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("tenant: no stock_point_sales provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(stockPointSaleColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	stockPointSaleInsertCacheMut.RLock()
	cache, cached := stockPointSaleInsertCache[key]
	stockPointSaleInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			stockPointSaleAllColumns,
			stockPointSaleColumnsWithDefault,
			stockPointSaleColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(stockPointSaleType, stockPointSaleMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(stockPointSaleType, stockPointSaleMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"stock_point_sales\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"stock_point_sales\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "tenant: unable to insert into stock_point_sales")
	}

	if !cached {
		stockPointSaleInsertCacheMut.Lock()
		stockPointSaleInsertCache[key] = cache
		stockPointSaleInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single StockPointSale record using the global executor.
// See Update for more documentation.
func (o *StockPointSale) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the StockPointSale.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *StockPointSale) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	stockPointSaleUpdateCacheMut.RLock()
	cache, cached := stockPointSaleUpdateCache[key]
	stockPointSaleUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			stockPointSaleAllColumns,
			stockPointSalePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("tenant: unable to update stock_point_sales, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"stock_point_sales\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, stockPointSalePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(stockPointSaleType, stockPointSaleMapping, append(wl, stockPointSalePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to update stock_point_sales row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to get rows affected by update for stock_point_sales")
	}

	if !cached {
		stockPointSaleUpdateCacheMut.Lock()
		stockPointSaleUpdateCache[key] = cache
		stockPointSaleUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q stockPointSaleQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q stockPointSaleQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to update all for stock_point_sales")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to retrieve rows affected for stock_point_sales")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o StockPointSaleSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o StockPointSaleSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("tenant: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), stockPointSalePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"stock_point_sales\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, stockPointSalePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to update all in stockPointSale slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to retrieve rows affected all in update all stockPointSale")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *StockPointSale) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *StockPointSale) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("tenant: no stock_point_sales provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(stockPointSaleColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	stockPointSaleUpsertCacheMut.RLock()
	cache, cached := stockPointSaleUpsertCache[key]
	stockPointSaleUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			stockPointSaleAllColumns,
			stockPointSaleColumnsWithDefault,
			stockPointSaleColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			stockPointSaleAllColumns,
			stockPointSalePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("tenant: unable to upsert stock_point_sales, could not build update column list")
		}

		ret := strmangle.SetComplement(stockPointSaleAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(stockPointSalePrimaryKeyColumns) == 0 {
				return errors.New("tenant: unable to upsert stock_point_sales, could not build conflict column list")
			}

			conflict = make([]string, len(stockPointSalePrimaryKeyColumns))
			copy(conflict, stockPointSalePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"stock_point_sales\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(stockPointSaleType, stockPointSaleMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(stockPointSaleType, stockPointSaleMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "tenant: unable to upsert stock_point_sales")
	}

	if !cached {
		stockPointSaleUpsertCacheMut.Lock()
		stockPointSaleUpsertCache[key] = cache
		stockPointSaleUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single StockPointSale record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *StockPointSale) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single StockPointSale record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *StockPointSale) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("tenant: no StockPointSale provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), stockPointSalePrimaryKeyMapping)
	sql := "DELETE FROM \"stock_point_sales\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to delete from stock_point_sales")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to get rows affected by delete for stock_point_sales")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q stockPointSaleQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q stockPointSaleQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("tenant: no stockPointSaleQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to delete all from stock_point_sales")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to get rows affected by deleteall for stock_point_sales")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o StockPointSaleSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o StockPointSaleSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(stockPointSaleBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), stockPointSalePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"stock_point_sales\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, stockPointSalePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to delete all from stockPointSale slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to get rows affected by deleteall for stock_point_sales")
	}

	if len(stockPointSaleAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *StockPointSale) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("tenant: no StockPointSale provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *StockPointSale) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindStockPointSale(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *StockPointSaleSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("tenant: empty StockPointSaleSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *StockPointSaleSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := StockPointSaleSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), stockPointSalePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"stock_point_sales\".* FROM \"stock_point_sales\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, stockPointSalePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "tenant: unable to reload all in StockPointSaleSlice")
	}

	*o = slice

	return nil
}

// StockPointSaleExistsG checks if the StockPointSale row exists.
func StockPointSaleExistsG(ctx context.Context, iD int64) (bool, error) {
	return StockPointSaleExists(ctx, boil.GetContextDB(), iD)
}

// StockPointSaleExists checks if the StockPointSale row exists.
func StockPointSaleExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"stock_point_sales\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "tenant: unable to check if stock_point_sales exists")
	}

	return exists, nil
}

// Exists checks if the StockPointSale row exists.
func (o *StockPointSale) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return StockPointSaleExists(ctx, exec, o.ID)
}
