// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package tenant

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// TypeIncome is an object representing the database table.
type TypeIncome struct {
	ID   int64  `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name string `boil:"name" json:"name" toml:"name" yaml:"name"`

	R *typeIncomeR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L typeIncomeL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TypeIncomeColumns = struct {
	ID   string
	Name string
}{
	ID:   "id",
	Name: "name",
}

var TypeIncomeTableColumns = struct {
	ID   string
	Name string
}{
	ID:   "type_incomes.id",
	Name: "type_incomes.name",
}

// Generated where

var TypeIncomeWhere = struct {
	ID   whereHelperint64
	Name whereHelperstring
}{
	ID:   whereHelperint64{field: "\"type_incomes\".\"id\""},
	Name: whereHelperstring{field: "\"type_incomes\".\"name\""},
}

// TypeIncomeRels is where relationship names are stored.
var TypeIncomeRels = struct {
	IncomeOthers string
}{
	IncomeOthers: "IncomeOthers",
}

// typeIncomeR is where relationships are stored.
type typeIncomeR struct {
	IncomeOthers IncomeOtherSlice `boil:"IncomeOthers" json:"IncomeOthers" toml:"IncomeOthers" yaml:"IncomeOthers"`
}

// NewStruct creates a new relationship struct
func (*typeIncomeR) NewStruct() *typeIncomeR {
	return &typeIncomeR{}
}

func (o *TypeIncome) GetIncomeOthers() IncomeOtherSlice {
	if o == nil {
		return nil
	}

	return o.R.GetIncomeOthers()
}

func (r *typeIncomeR) GetIncomeOthers() IncomeOtherSlice {
	if r == nil {
		return nil
	}

	return r.IncomeOthers
}

// typeIncomeL is where Load methods for each relationship are stored.
type typeIncomeL struct{}

var (
	typeIncomeAllColumns            = []string{"id", "name"}
	typeIncomeColumnsWithoutDefault = []string{"name"}
	typeIncomeColumnsWithDefault    = []string{"id"}
	typeIncomePrimaryKeyColumns     = []string{"id"}
	typeIncomeGeneratedColumns      = []string{}
)

type (
	// TypeIncomeSlice is an alias for a slice of pointers to TypeIncome.
	// This should almost always be used instead of []TypeIncome.
	TypeIncomeSlice []*TypeIncome
	// TypeIncomeHook is the signature for custom TypeIncome hook methods
	TypeIncomeHook func(context.Context, boil.ContextExecutor, *TypeIncome) error

	typeIncomeQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	typeIncomeType                 = reflect.TypeOf(&TypeIncome{})
	typeIncomeMapping              = queries.MakeStructMapping(typeIncomeType)
	typeIncomePrimaryKeyMapping, _ = queries.BindMapping(typeIncomeType, typeIncomeMapping, typeIncomePrimaryKeyColumns)
	typeIncomeInsertCacheMut       sync.RWMutex
	typeIncomeInsertCache          = make(map[string]insertCache)
	typeIncomeUpdateCacheMut       sync.RWMutex
	typeIncomeUpdateCache          = make(map[string]updateCache)
	typeIncomeUpsertCacheMut       sync.RWMutex
	typeIncomeUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var typeIncomeAfterSelectMu sync.Mutex
var typeIncomeAfterSelectHooks []TypeIncomeHook

var typeIncomeBeforeInsertMu sync.Mutex
var typeIncomeBeforeInsertHooks []TypeIncomeHook
var typeIncomeAfterInsertMu sync.Mutex
var typeIncomeAfterInsertHooks []TypeIncomeHook

var typeIncomeBeforeUpdateMu sync.Mutex
var typeIncomeBeforeUpdateHooks []TypeIncomeHook
var typeIncomeAfterUpdateMu sync.Mutex
var typeIncomeAfterUpdateHooks []TypeIncomeHook

var typeIncomeBeforeDeleteMu sync.Mutex
var typeIncomeBeforeDeleteHooks []TypeIncomeHook
var typeIncomeAfterDeleteMu sync.Mutex
var typeIncomeAfterDeleteHooks []TypeIncomeHook

var typeIncomeBeforeUpsertMu sync.Mutex
var typeIncomeBeforeUpsertHooks []TypeIncomeHook
var typeIncomeAfterUpsertMu sync.Mutex
var typeIncomeAfterUpsertHooks []TypeIncomeHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *TypeIncome) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range typeIncomeAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *TypeIncome) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range typeIncomeBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *TypeIncome) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range typeIncomeAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *TypeIncome) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range typeIncomeBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *TypeIncome) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range typeIncomeAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *TypeIncome) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range typeIncomeBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *TypeIncome) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range typeIncomeAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *TypeIncome) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range typeIncomeBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *TypeIncome) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range typeIncomeAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTypeIncomeHook registers your hook function for all future operations.
func AddTypeIncomeHook(hookPoint boil.HookPoint, typeIncomeHook TypeIncomeHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		typeIncomeAfterSelectMu.Lock()
		typeIncomeAfterSelectHooks = append(typeIncomeAfterSelectHooks, typeIncomeHook)
		typeIncomeAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		typeIncomeBeforeInsertMu.Lock()
		typeIncomeBeforeInsertHooks = append(typeIncomeBeforeInsertHooks, typeIncomeHook)
		typeIncomeBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		typeIncomeAfterInsertMu.Lock()
		typeIncomeAfterInsertHooks = append(typeIncomeAfterInsertHooks, typeIncomeHook)
		typeIncomeAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		typeIncomeBeforeUpdateMu.Lock()
		typeIncomeBeforeUpdateHooks = append(typeIncomeBeforeUpdateHooks, typeIncomeHook)
		typeIncomeBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		typeIncomeAfterUpdateMu.Lock()
		typeIncomeAfterUpdateHooks = append(typeIncomeAfterUpdateHooks, typeIncomeHook)
		typeIncomeAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		typeIncomeBeforeDeleteMu.Lock()
		typeIncomeBeforeDeleteHooks = append(typeIncomeBeforeDeleteHooks, typeIncomeHook)
		typeIncomeBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		typeIncomeAfterDeleteMu.Lock()
		typeIncomeAfterDeleteHooks = append(typeIncomeAfterDeleteHooks, typeIncomeHook)
		typeIncomeAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		typeIncomeBeforeUpsertMu.Lock()
		typeIncomeBeforeUpsertHooks = append(typeIncomeBeforeUpsertHooks, typeIncomeHook)
		typeIncomeBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		typeIncomeAfterUpsertMu.Lock()
		typeIncomeAfterUpsertHooks = append(typeIncomeAfterUpsertHooks, typeIncomeHook)
		typeIncomeAfterUpsertMu.Unlock()
	}
}

// OneG returns a single typeIncome record from the query using the global executor.
func (q typeIncomeQuery) OneG(ctx context.Context) (*TypeIncome, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single typeIncome record from the query.
func (q typeIncomeQuery) One(ctx context.Context, exec boil.ContextExecutor) (*TypeIncome, error) {
	o := &TypeIncome{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "tenant: failed to execute a one query for type_incomes")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all TypeIncome records from the query using the global executor.
func (q typeIncomeQuery) AllG(ctx context.Context) (TypeIncomeSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all TypeIncome records from the query.
func (q typeIncomeQuery) All(ctx context.Context, exec boil.ContextExecutor) (TypeIncomeSlice, error) {
	var o []*TypeIncome

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "tenant: failed to assign all query results to TypeIncome slice")
	}

	if len(typeIncomeAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all TypeIncome records in the query using the global executor
func (q typeIncomeQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all TypeIncome records in the query.
func (q typeIncomeQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to count type_incomes rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q typeIncomeQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q typeIncomeQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "tenant: failed to check if type_incomes exists")
	}

	return count > 0, nil
}

// IncomeOthers retrieves all the income_other's IncomeOthers with an executor.
func (o *TypeIncome) IncomeOthers(mods ...qm.QueryMod) incomeOtherQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"income_others\".\"type_income_id\"=?", o.ID),
	)

	return IncomeOthers(queryMods...)
}

// LoadIncomeOthers allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (typeIncomeL) LoadIncomeOthers(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTypeIncome any, mods queries.Applicator) error {
	var slice []*TypeIncome
	var object *TypeIncome

	if singular {
		var ok bool
		object, ok = maybeTypeIncome.(*TypeIncome)
		if !ok {
			object = new(TypeIncome)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTypeIncome)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTypeIncome))
			}
		}
	} else {
		s, ok := maybeTypeIncome.(*[]*TypeIncome)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTypeIncome)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTypeIncome))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &typeIncomeR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &typeIncomeR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`income_others`),
		qm.WhereIn(`income_others.type_income_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load income_others")
	}

	var resultSlice []*IncomeOther
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice income_others")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on income_others")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for income_others")
	}

	if len(incomeOtherAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.IncomeOthers = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &incomeOtherR{}
			}
			foreign.R.TypeIncome = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.TypeIncomeID {
				local.R.IncomeOthers = append(local.R.IncomeOthers, foreign)
				if foreign.R == nil {
					foreign.R = &incomeOtherR{}
				}
				foreign.R.TypeIncome = local
				break
			}
		}
	}

	return nil
}

// AddIncomeOthersG adds the given related objects to the existing relationships
// of the type_income, optionally inserting them as new records.
// Appends related to o.R.IncomeOthers.
// Sets related.R.TypeIncome appropriately.
// Uses the global database handle.
func (o *TypeIncome) AddIncomeOthersG(ctx context.Context, insert bool, related ...*IncomeOther) error {
	return o.AddIncomeOthers(ctx, boil.GetContextDB(), insert, related...)
}

// AddIncomeOthers adds the given related objects to the existing relationships
// of the type_income, optionally inserting them as new records.
// Appends related to o.R.IncomeOthers.
// Sets related.R.TypeIncome appropriately.
func (o *TypeIncome) AddIncomeOthers(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*IncomeOther) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.TypeIncomeID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"income_others\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"type_income_id"}),
				strmangle.WhereClause("\"", "\"", 2, incomeOtherPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.TypeIncomeID = o.ID
		}
	}

	if o.R == nil {
		o.R = &typeIncomeR{
			IncomeOthers: related,
		}
	} else {
		o.R.IncomeOthers = append(o.R.IncomeOthers, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &incomeOtherR{
				TypeIncome: o,
			}
		} else {
			rel.R.TypeIncome = o
		}
	}
	return nil
}

// TypeIncomes retrieves all the records using an executor.
func TypeIncomes(mods ...qm.QueryMod) typeIncomeQuery {
	mods = append(mods, qm.From("\"type_incomes\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"type_incomes\".*"})
	}

	return typeIncomeQuery{q}
}

// FindTypeIncomeG retrieves a single record by ID.
func FindTypeIncomeG(ctx context.Context, iD int64, selectCols ...string) (*TypeIncome, error) {
	return FindTypeIncome(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindTypeIncome retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTypeIncome(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*TypeIncome, error) {
	typeIncomeObj := &TypeIncome{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"type_incomes\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, typeIncomeObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "tenant: unable to select from type_incomes")
	}

	if err = typeIncomeObj.doAfterSelectHooks(ctx, exec); err != nil {
		return typeIncomeObj, err
	}

	return typeIncomeObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *TypeIncome) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *TypeIncome) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("tenant: no type_incomes provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(typeIncomeColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	typeIncomeInsertCacheMut.RLock()
	cache, cached := typeIncomeInsertCache[key]
	typeIncomeInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			typeIncomeAllColumns,
			typeIncomeColumnsWithDefault,
			typeIncomeColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(typeIncomeType, typeIncomeMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(typeIncomeType, typeIncomeMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"type_incomes\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"type_incomes\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "tenant: unable to insert into type_incomes")
	}

	if !cached {
		typeIncomeInsertCacheMut.Lock()
		typeIncomeInsertCache[key] = cache
		typeIncomeInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single TypeIncome record using the global executor.
// See Update for more documentation.
func (o *TypeIncome) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the TypeIncome.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *TypeIncome) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	typeIncomeUpdateCacheMut.RLock()
	cache, cached := typeIncomeUpdateCache[key]
	typeIncomeUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			typeIncomeAllColumns,
			typeIncomePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("tenant: unable to update type_incomes, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"type_incomes\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, typeIncomePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(typeIncomeType, typeIncomeMapping, append(wl, typeIncomePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to update type_incomes row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to get rows affected by update for type_incomes")
	}

	if !cached {
		typeIncomeUpdateCacheMut.Lock()
		typeIncomeUpdateCache[key] = cache
		typeIncomeUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q typeIncomeQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q typeIncomeQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to update all for type_incomes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to retrieve rows affected for type_incomes")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o TypeIncomeSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TypeIncomeSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("tenant: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), typeIncomePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"type_incomes\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, typeIncomePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to update all in typeIncome slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to retrieve rows affected all in update all typeIncome")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *TypeIncome) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *TypeIncome) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("tenant: no type_incomes provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(typeIncomeColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	typeIncomeUpsertCacheMut.RLock()
	cache, cached := typeIncomeUpsertCache[key]
	typeIncomeUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			typeIncomeAllColumns,
			typeIncomeColumnsWithDefault,
			typeIncomeColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			typeIncomeAllColumns,
			typeIncomePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("tenant: unable to upsert type_incomes, could not build update column list")
		}

		ret := strmangle.SetComplement(typeIncomeAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(typeIncomePrimaryKeyColumns) == 0 {
				return errors.New("tenant: unable to upsert type_incomes, could not build conflict column list")
			}

			conflict = make([]string, len(typeIncomePrimaryKeyColumns))
			copy(conflict, typeIncomePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"type_incomes\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(typeIncomeType, typeIncomeMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(typeIncomeType, typeIncomeMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "tenant: unable to upsert type_incomes")
	}

	if !cached {
		typeIncomeUpsertCacheMut.Lock()
		typeIncomeUpsertCache[key] = cache
		typeIncomeUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single TypeIncome record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *TypeIncome) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single TypeIncome record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *TypeIncome) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("tenant: no TypeIncome provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), typeIncomePrimaryKeyMapping)
	sql := "DELETE FROM \"type_incomes\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to delete from type_incomes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to get rows affected by delete for type_incomes")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q typeIncomeQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q typeIncomeQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("tenant: no typeIncomeQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to delete all from type_incomes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to get rows affected by deleteall for type_incomes")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o TypeIncomeSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TypeIncomeSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(typeIncomeBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), typeIncomePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"type_incomes\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, typeIncomePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "tenant: unable to delete all from typeIncome slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tenant: failed to get rows affected by deleteall for type_incomes")
	}

	if len(typeIncomeAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *TypeIncome) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("tenant: no TypeIncome provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *TypeIncome) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindTypeIncome(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TypeIncomeSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("tenant: empty TypeIncomeSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TypeIncomeSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := TypeIncomeSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), typeIncomePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"type_incomes\".* FROM \"type_incomes\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, typeIncomePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "tenant: unable to reload all in TypeIncomeSlice")
	}

	*o = slice

	return nil
}

// TypeIncomeExistsG checks if the TypeIncome row exists.
func TypeIncomeExistsG(ctx context.Context, iD int64) (bool, error) {
	return TypeIncomeExists(ctx, boil.GetContextDB(), iD)
}

// TypeIncomeExists checks if the TypeIncome row exists.
func TypeIncomeExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"type_incomes\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "tenant: unable to check if type_incomes exists")
	}

	return exists, nil
}

// Exists checks if the TypeIncome row exists.
func (o *TypeIncome) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return TypeIncomeExists(ctx, exec, o.ID)
}
