CREATE TABLE deposits (
    id BIGSERIAL PRIMARY KEY,
    product_id BIGINT NOT NULL,
    stock NUMERIC(15, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_deposits_product FOREIGN KEY (product_id) REFERENCES products(id)
);
